package com.peter.apt.compiler;

import com.google.auto.service.AutoService;
import com.peter.apt.annotation.Bindable;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.Elements;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.util.Collections;
import java.util.Set;

/**
 * 注解处理器 - 生成绑定类
 */
@AutoService(Processor.class)
public class BindableProcessor extends AbstractProcessor {

    private Elements elementUtils;

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        elementUtils = processingEnv.getElementUtils();
    }

    @Override
    public Set<String> getSupportedAnnotationTypes() {
        return Collections.singleton(Bindable.class.getCanonicalName());
    }

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latestSupported();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (Element element : roundEnv.getElementsAnnotatedWith(Bindable.class)) {
            TypeElement typeElement = (TypeElement) element;
            try {
                generateBindingClass(typeElement);
            } catch (IOException e) {
                processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, 
                    "Failed to generate binding class: " + e.getMessage(), element);
            }
        }
        return false;
    }

    private void generateBindingClass(TypeElement typeElement) throws IOException {
        String packageName = elementUtils.getPackageOf(typeElement).getQualifiedName().toString();
        String className = typeElement.getSimpleName().toString();
        String bindingClassName = className + "_Binding";

        // 创建 bind 方法
        MethodSpec bindMethod = MethodSpec.methodBuilder("bind")
                .addModifiers(javax.lang.model.element.Modifier.PUBLIC, javax.lang.model.element.Modifier.STATIC)
                .returns(void.class)
                .addParameter(com.squareup.javapoet.ClassName.get(typeElement), "target")
                .addStatement("// TODO: implement binding logic")
                .build();

        // 创建绑定类
        TypeSpec bindingClass = TypeSpec.classBuilder(bindingClassName)
                .addModifiers(javax.lang.model.element.Modifier.PUBLIC)
                .addMethod(bindMethod)
                .build();

        // 生成 Java 文件
        JavaFile javaFile = JavaFile.builder(packageName, bindingClass)
                .addFileComment("Generated by APT. Do not modify!")
                .build();

        javaFile.writeTo(processingEnv.getFiler());
        
        // 打印信息
        System.out.println("========================================");
        System.out.println("Generated: " + packageName + "." + bindingClassName);
        System.out.println("Target: " + typeElement.getQualifiedName());
        System.out.println("========================================");
    }
}
