package com.peter.apt.compiler;

import com.google.auto.service.AutoService;
import com.peter.apt.annotation.Bindable;
import com.peter.apt.annotation.BindView;
import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedOptions;
import javax.annotation.processing.SupportedSourceVersion;
import javax.annotation.processing.Generated;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.util.Elements;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.util.Set;

/**
 * 注解处理器 - 生成绑定类
 * 
 * 支持的选项：
 * - apt.debug: 是否打印调试信息 (true/false)
 * - apt.logLevel: 日志级别 (0=none, 1=info, 2=debug)
 */
@AutoService(Processor.class)
@SupportedAnnotationTypes({
    "com.peter.apt.annotation.Bindable",
    "com.peter.apt.annotation.BindView"
})
@SupportedSourceVersion(SourceVersion.RELEASE_11)
@SupportedOptions({
    "apt.debug",
    "apt.logLevel"
})
public class BindableProcessor extends AbstractProcessor {

    private Elements elementUtils;
    private boolean debugMode = false;
    private int logLevel = 1;

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        elementUtils = processingEnv.getElementUtils();
        
        // 读取选项配置
        String debugOption = processingEnv.getOptions().get("apt.debug");
        if (debugOption != null) {
            debugMode = Boolean.parseBoolean(debugOption);
        }
        
        String logLevelOption = processingEnv.getOptions().get("apt.logLevel");
        if (logLevelOption != null) {
            logLevel = Integer.parseInt(logLevelOption);
        }
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        // 处理所有被 @Bindable 标记的类
        for (Element element : roundEnv.getElementsAnnotatedWith(Bindable.class)) {
            TypeElement typeElement = (TypeElement) element;
            try {
                generateBindingClass(typeElement);
            } catch (IOException e) {
                processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "Failed to generate binding class: " + e.getMessage(), element);
            }
        }
        return false;
    }

    private void generateBindingClass(TypeElement typeElement) throws IOException {
        String packageName = elementUtils.getPackageOf(typeElement).getQualifiedName().toString();
        String className = typeElement.getSimpleName().toString();
        String bindingClassName = className + "_Binding";

        // 创建 bind 方法
        MethodSpec.Builder bindMethodBuilder = MethodSpec.methodBuilder("bind")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(void.class)
                .addParameter(ClassName.get(typeElement), "target");

        // 查找该类中所有被 @BindView 标记的字段
        for (Element enclosedElement : typeElement.getEnclosedElements()) {
            if (enclosedElement.getKind() == ElementKind.FIELD) {
                VariableElement field = (VariableElement) enclosedElement;
                BindView bindView = field.getAnnotation(BindView.class);
                if (bindView != null) {
                    String fieldName = field.getSimpleName().toString();
                    String fieldType = field.asType().toString();
                    int viewId = bindView.value();

                    // 直接使用资源ID
                    bindMethodBuilder.addStatement(
                            "target.$L = ($L) target.findViewById($L)",
                            fieldName,
                            fieldType,
                            viewId
                    );
                }
            }
        }

        // 创建绑定类，添加 @Generated 注解
        TypeSpec bindingClass = TypeSpec.classBuilder(bindingClassName)
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(AnnotationSpec.builder(Generated.class)
                        .addMember("value", "$S", BindableProcessor.class.getName())
                        .addMember("comments", "$S", "Generated by APT")
                        .build())
                .addMethod(bindMethodBuilder.build())
                .build();

        // 生成 Java 文件
        JavaFile javaFile = JavaFile.builder(packageName, bindingClass)
                .addFileComment("Generated by APT. Do not modify!")
                .build();

        javaFile.writeTo(processingEnv.getFiler());
        
        // 根据配置打印日志
        if (logLevel >= 1) {
            System.out.println("========================================");
            System.out.println("Generated: " + packageName + "." + bindingClassName);
            System.out.println("Target: " + typeElement.getQualifiedName());
            if (debugMode && logLevel >= 2) {
                System.out.println("Debug: debugMode=" + debugMode);
            }
            System.out.println("========================================");
        }
    }
}