package com.peter.window.demo.activitythread.deep

import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.os.Message
import android.util.Log
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import com.peter.window.demo.R

/**
 * ActivityThread 深入篇 - Handler 消息机制
 *
 * === H 类详解 ===
 *
 * ActivityThread 内部有一个 H 类继承自 Handler，
 * 它是主线程消息处理的核心。所有四大组件的生命周期
 * 都是通过 H 类来分发的。
 *
 * 【H 类的定义】
 * ```java
 * class H extends Handler {
 *     public static final int LAUNCH_ACTIVITY         = 100;
 *     public static final int PAUSE_ACTIVITY          = 101;
 *     public static final int PAUSE_ACTIVITY_FINISHING= 102;
 *     public static final int STOP_ACTIVITY_SHOW      = 103;
 *     public static final int STOP_ACTIVITY_HIDE      = 104;
 *     public static final int SHOW_WINDOW             = 105;
 *     public static final int HIDE_WINDOW             = 106;
 *     public static final int RESUME_ACTIVITY         = 107;
 *     public static final int SEND_RESULT             = 108;
 *     public static final int DESTROY_ACTIVITY        = 109;
 *     // ... 更多消息类型
 * }
 * ```
 */
class HandlerMessageActivity : AppCompatActivity() {

    companion object {
        private const val TAG = "HandlerMessage"
    }

    private val sb = StringBuilder()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_handler_message)
        
        showHClassDefinition()
        showMessageTypes()
        showHandleMessage()
        showMessageFlow()
        showCustomHandler()
        
        findViewById<TextView>(R.id.tvContent).text = sb.toString()
    }

    /**
     * H 类定义
     */
    private fun showHClassDefinition() {
        sb.appendLine("═══════════════════════════════════════════════════")
        sb.appendLine("              H 类定义与作用")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【H 类完整定义】\n")
        sb.appendLine("```java")
        sb.appendLine("// ActivityThread.java - 内部类")
        sb.appendLine("class H extends Handler {")
        sb.appendLine("    ")
        sb.appendLine("    // ============ Activity 相关 ============")
        sb.appendLine("    public static final int LAUNCH_ACTIVITY         = 100;")
        sb.appendLine("    public static final int PAUSE_ACTIVITY          = 101;")
        sb.appendLine("    public static final int PAUSE_ACTIVITY_FINISHING= 102;")
        sb.appendLine("    public static final int STOP_ACTIVITY_SHOW      = 103;")
        sb.appendLine("    public static final int STOP_ACTIVITY_HIDE      = 104;")
        sb.appendLine("    public static final int SHOW_WINDOW             = 105;")
        sb.appendLine("    public static final int HIDE_WINDOW             = 106;")
        sb.appendLine("    public static final int RESUME_ACTIVITY         = 107;")
        sb.appendLine("    public static final int SEND_RESULT             = 108;")
        sb.appendLine("    public static final int DESTROY_ACTIVITY        = 109;")
        sb.appendLine("    public static final int NEW_INTENT              = 112;")
        sb.appendLine("    public static final int CREATE_SERVICE          = 114;")
        sb.appendLine("    public static final int STOP_SERVICE            = 116;")
        sb.appendLine("    public static final int BIND_SERVICE            = 121;")
        sb.appendLine("    public static final int UNBIND_SERVICE          = 122;")
        sb.appendLine("    ")
        sb.appendLine("    // ============ Application 相关 ============")
        sb.appendLine("    public static final int BIND_APPLICATION        = 110;")
        sb.appendLine("    public static final int EXIT_APPLICATION        = 111;")
        sb.appendLine("    ")
        sb.appendLine("    // ============ Provider 相关 ============")
        sb.appendLine("    public static final int INSTALL_PROVIDER        = 131;")
        sb.appendLine("    ")
        sb.appendLine("    // ============ 配置变更相关 ============")
        sb.appendLine("    public static final int CONFIGURATION_CHANGED   = 113;")
        sb.appendLine("    public static final int LOW_MEMORY              = 118;")
        sb.appendLine("    public static final int DUMP_HEAP               = 128;")
        sb.appendLine("    ")
        sb.appendLine("    // ============ UI 相关 ============")
        sb.appendLine("    public static final int RELAUNCH_ACTIVITY       = 126;")
        sb.appendLine("    public static final int EXECUTE_TRANSACTION     = 159;")
        sb.appendLine("    ")
        sb.appendLine("    // 构造函数")
        sb.appendLine("    public H(Looper looper) {")
        sb.appendLine("        super(looper, null, true);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void handleMessage(Message msg) {")
        sb.appendLine("        switch (msg.what) {")
        sb.appendLine("            case LAUNCH_ACTIVITY: {")
        sb.appendLine("                handleLaunchActivity(...);")
        sb.appendLine("                break;")
        sb.appendLine("            }")
        sb.appendLine("            case PAUSE_ACTIVITY: {")
        sb.appendLine("                handlePauseActivity(...);")
        sb.appendLine("                break;")
        sb.appendLine("            }")
        sb.appendLine("            case RESUME_ACTIVITY: {")
        sb.appendLine("                handleResumeActivity(...);")
        sb.appendLine("                break;")
        sb.appendLine("            }")
        sb.appendLine("            // ... 更多 case")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【H 类的作用】\n")
        sb.appendLine("┌─────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                         H 类                            │\n")
        sb.appendLine("├─────────────────────────────────────────────────────────┤\n")
        sb.appendLine("│ 1. 接收来自 ApplicationThread 的消息                    │\n")
        sb.appendLine("│ 2. 分发 Activity 生命周期消息                           │\n")
        sb.appendLine("│ 3. 分发 Service 生命周期消息                            │\n")
        sb.appendLine("│ 4. 分发 Provider 相关消息                               │\n")
        sb.appendLine("│ 5. 处理配置变更消息                                     │\n")
        sb.appendLine("│ 6. 处理内存低警告                                       │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────┘\n")
    }

    /**
     * 消息类型
     */
    private fun showMessageTypes() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("              消息类型详解")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【Activity 相关消息】\n")
        sb.appendLine("┌──────────────────────────┬───────┬──────────────────────────────┐\n")
        sb.appendLine("│ 消息类型                 │ 值    │ 说明                         │\n")
        sb.appendLine("├──────────────────────────┼───────┼──────────────────────────────┤\n")
        sb.appendLine("│ LAUNCH_ACTIVITY          │ 100   │ 启动 Activity                │\n")
        sb.appendLine("│ PAUSE_ACTIVITY           │ 101   │ 暂停 Activity                │\n")
        sb.appendLine("│ PAUSE_ACTIVITY_FINISHING │ 102   │ 暂停并结束 Activity          │\n")
        sb.appendLine("│ STOP_ACTIVITY_SHOW       │ 103   │ 停止 Activity（显示）        │\n")
        sb.appendLine("│ STOP_ACTIVITY_HIDE       │ 104   │ 停止 Activity（隐藏）        │\n")
        sb.appendLine("│ RESUME_ACTIVITY          │ 107   │ 恢复 Activity                │\n")
        sb.appendLine("│ DESTROY_ACTIVITY         │ 109   │ 销毁 Activity                │\n")
        sb.appendLine("│ NEW_INTENT               │ 112   │ 新 Intent 到达              │\n")
        sb.appendLine("│ RELAUNCH_ACTIVITY        │ 126   │ 重启 Activity               │\n")
        sb.appendLine("└──────────────────────────┴───────┴──────────────────────────────┘\n")
        
        sb.appendLine("【Service 相关消息】\n")
        sb.appendLine("┌──────────────────────────┬───────┬──────────────────────────────┐\n")
        sb.appendLine("│ 消息类型                 │ 值    │ 说明                         │\n")
        sb.appendLine("├──────────────────────────┼───────┼──────────────────────────────┤\n")
        sb.appendLine("│ CREATE_SERVICE           │ 114   │ 创建 Service                 │\n")
        sb.appendLine("│ STOP_SERVICE             │ 116   │ 停止 Service                 │\n")
        sb.appendLine("│ BIND_SERVICE             │ 121   │ 绑定 Service                 │\n")
        sb.appendLine("│ UNBIND_SERVICE           │ 122   │ 解绑 Service                 │\n")
        sb.appendLine("│ SERVICE_ARGS             │ 115   │ Service 参数                 │\n")
        sb.appendLine("│ STOP_SERVICE_TOKEN       │ 143   │ 停止 Service Token           │\n")
        sb.appendLine("└──────────────────────────┴───────┴──────────────────────────────┘\n")
        
        sb.appendLine("【Application 相关消息】\n")
        sb.appendLine("┌──────────────────────────┬───────┬──────────────────────────────┐\n")
        sb.appendLine("│ 消息类型                 │ 值    │ 说明                         │\n")
        sb.appendLine("├──────────────────────────┼───────┼──────────────────────────────┤\n")
        sb.appendLine("│ BIND_APPLICATION         │ 110   │ 绑定 Application             │\n")
        sb.appendLine("│ EXIT_APPLICATION         │ 111   │ 退出 Application             │\n")
        sb.appendLine("│ TRIM_MEMORY              │ 120   │ 修剪内存                     │\n")
        sb.appendLine("│ DUMP_ACTIVITY            │ 123   │ Dump Activity                │\n")
        sb.appendLine("│ DUMP_PROVIDER            │ 124   │ Dump Provider               │\n")
        sb.appendLine("│ DUMP_SERVICE             │ 125   │ Dump Service                │\n")
        sb.appendLine("│ DUMP_HEAP                │ 128   │ Dump Heap                   │\n")
        sb.appendLine("└──────────────────────────┴───────┴──────────────────────────────┘\n")
        
        sb.appendLine("【系统事件消息】\n")
        sb.appendLine("┌──────────────────────────┬───────┬──────────────────────────────┐\n")
        sb.appendLine("│ 消息类型                 │ 值    │ 说明                         │\n")
        sb.appendLine("├──────────────────────────┼───────┼──────────────────────────────┤\n")
        sb.appendLine("│ CONFIGURATION_CHANGED    │ 113   │ 配置变更（屏幕旋转等）       │\n")
        sb.appendLine("│ LOW_MEMORY               │ 118   │ 内存不足警告                 │\n")
        sb.appendLine("│ PROFILER_CONTROL         │ 133   │ Profiler 控制                │\n")
        sb.appendLine("│ EXECUTE_TRANSACTION      │ 159   │ 执行事务                     │\n")
        sb.appendLine("└──────────────────────────┴───────┴──────────────────────────────┘\n")
    }

    /**
     * handleMessage 处理逻辑
     */
    private fun showHandleMessage() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("           handleMessage 处理逻辑")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【完整 handleMessage 实现】\n")
        sb.appendLine("```java")
        sb.appendLine("public void handleMessage(Message msg) {")
        sb.appendLine("    switch (msg.what) {")
        sb.appendLine("        ")
        sb.appendLine("        // ========== Activity 相关 ==========")
        sb.appendLine("        case LAUNCH_ACTIVITY: {")
        sb.appendLine("            ActivityClientRecord r = (ActivityClientRecord) msg.obj;")
        sb.appendLine("            r.packageInfo = getPackageInfoNoCheck(")
        sb.appendLine("                    r.activityInfo.applicationInfo, r.compatInfo);")
        sb.appendLine("            handleLaunchActivity(r, null, \"LAUNCH_ACTIVITY\");")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        case PAUSE_ACTIVITY: {")
        sb.appendLine("            SomeArgs args = (SomeArgs) msg.obj;")
        sb.appendLine("            handlePauseActivity((IBinder) args.arg1,")
        sb.appendLine("                    args.argi1 != 0, msg.arg1 != 0, args.argi2);")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        case RESUME_ACTIVITY: {")
        sb.appendLine("            handleResumeActivity((IBinder) msg.obj, true,")
        sb.appendLine("                    msg.arg1 != 0, true, msg.arg2, \"RESUME_ACTIVITY\");")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        case STOP_ACTIVITY_SHOW: {")
        sb.appendLine("            handleStopActivity((IBinder) msg.obj, true, msg.arg2);")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        case STOP_ACTIVITY_HIDE: {")
        sb.appendLine("            handleStopActivity((IBinder) msg.obj, false, msg.arg2);")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        case DESTROY_ACTIVITY: {")
        sb.appendLine("            handleDestroyActivity((IBinder) msg.obj, msg.arg1 != 0,")
        sb.appendLine("                    msg.arg2, false);")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        // ========== Service 相关 ==========")
        sb.appendLine("        case CREATE_SERVICE: {")
        sb.appendLine("            handleCreateService((CreateServiceData) msg.obj);")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        case BIND_SERVICE: {")
        sb.appendLine("            handleBindService((BindServiceData) msg.obj);")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        case UNBIND_SERVICE: {")
        sb.appendLine("            handleUnbindService((BindServiceData) msg.obj);")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        case STOP_SERVICE: {")
        sb.appendLine("            handleStopService((IBinder) msg.obj);")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        // ========== Application 相关 ==========")
        sb.appendLine("        case BIND_APPLICATION: {")
        sb.appendLine("            AppBindData data = (AppBindData) msg.obj;")
        sb.appendLine("            handleBindApplication(data);")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        case EXIT_APPLICATION: {")
        sb.appendLine("            if (mInitialApplication != null) {")
        sb.appendLine("                mInitialApplication.onTerminate();")
        sb.appendLine("            }")
        sb.appendLine("            Looper.myLooper().quit();")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        // ========== 系统事件 ==========")
        sb.appendLine("        case CONFIGURATION_CHANGED: {")
        sb.appendLine("            handleConfigurationChanged((Configuration) msg.obj);")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        case LOW_MEMORY: {")
        sb.appendLine("            handleLowMemory();")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        case TRIM_MEMORY: {")
        sb.appendLine("            handleTrimMemory(msg.arg1);")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        // ========== Provider 相关 ==========")
        sb.appendLine("        case INSTALL_PROVIDER: {")
        sb.appendLine("            handleInstallProvider((ProviderInfo) msg.obj);")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        // ========== 新版事务处理 ==========")
        sb.appendLine("        case EXECUTE_TRANSACTION: {")
        sb.appendLine("            final ClientTransaction transaction = (ClientTransaction) msg.obj;")
        sb.appendLine("            mTransactionExecutor.execute(transaction);")
        sb.appendLine("            if (isSystem()) {")
        sb.appendLine("                transaction.recycle();")
        sb.appendLine("            }")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【消息处理流程图】\n")
        sb.appendLine("```\n")
        sb.appendLine("ApplicationThread              H (Handler)              处理方法")
        sb.appendLine("       │                          │                        │")
        sb.appendLine("       │ scheduleLaunchActivity   │                        │")
        sb.appendLine("       │ sendMessage(LAUNCH)      │                        │")
        sb.appendLine("       │─────────────────────────>│                        │")
        sb.appendLine("       │                          │ handleMessage()        │")
        sb.appendLine("       │                          │ case LAUNCH_ACTIVITY:  │")
        sb.appendLine("       │                          │ handleLaunchActivity() │")
        sb.appendLine("       │                          │───────────────────────>│")
        sb.appendLine("       │                          │                        │")
        sb.appendLine("       │ schedulePauseActivity    │                        │")
        sb.appendLine("       │ sendMessage(PAUSE)       │                        │")
        sb.appendLine("       │─────────────────────────>│                        │")
        sb.appendLine("       │                          │ handleMessage()        │")
        sb.appendLine("       │                          │ case PAUSE_ACTIVITY:   │")
        sb.appendLine("       │                          │ handlePauseActivity()  │")
        sb.appendLine("       │                          │───────────────────────>│")
        sb.appendLine("```\n")
    }

    /**
     * 消息流转流程
     */
    private fun showMessageFlow() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("              消息流转完整流程")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【从 AMS 到 ActivityThread 的消息流转】\n")
        sb.appendLine("```")
        sb.appendLine("┌─────────────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                           System Server                             │\n")
        sb.appendLine("│  ┌─────────────────────────────────────────────────────────────┐   │\n")
        sb.appendLine("│  │                   ActivityManagerService                    │   │\n")
        sb.appendLine("│  │                                                             │   │\n")
        sb.appendLine("│  │  startActivity() ───> startActivityAsUser()                 │   │\n")
        sb.appendLine("│  │                              │                              │   │\n")
        sb.appendLine("│  │                              ▼                              │   │\n")
        sb.appendLine("│  │           调用 ApplicationThread.scheduleLaunchActivity()   │   │\n")
        sb.appendLine("│  │                                                             │   │\n")
        sb.appendLine("│  └─────────────────────────────────────────────────────────────┘   │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("                                 │")
        sb.appendLine("                                 │ Binder IPC")
        sb.appendLine("                                 ▼")
        sb.appendLine("┌─────────────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                            App 进程                                 │\n")
        sb.appendLine("│  ┌─────────────────────────────────────────────────────────────┐   │\n")
        sb.appendLine("│  │                ApplicationThread (Binder)                   │   │\n")
        sb.appendLine("│  │                                                             │   │\n")
        sb.appendLine("│  │  scheduleLaunchActivity() {                                 │   │\n")
        sb.appendLine("│  │      ActivityClientRecord r = new ActivityClientRecord();   │   │\n")
        sb.appendLine("│  │      r.token = token;                                       │   │\n")
        sb.appendLine("│  │      r.intent = intent;                                     │   │\n")
        sb.appendLine("│  │      ...                                                    │   │\n")
        sb.appendLine("│  │      sendMessage(H.LAUNCH_ACTIVITY, r);                     │   │\n")
        sb.appendLine("│  │  }                                                          │   │\n")
        sb.appendLine("│  │                                                             │   │\n")
        sb.appendLine("│  └─────────────────────────────────────────────────────────────┘   │\n")
        sb.appendLine("│                                 │                                  │\n")
        sb.appendLine("│                                 │ sendMessage()                    │\n")
        sb.appendLine("│                                 ▼                                  │\n")
        sb.appendLine("│  ┌─────────────────────────────────────────────────────────────┐   │\n")
        sb.appendLine("│  │                    MessageQueue                             │   │\n")
        sb.appendLine("│  │                                                             │   │\n")
        sb.appendLine("│  │  ┌──────┐  ┌──────┐  ┌──────┐  ┌──────┐                     │   │\n")
        sb.appendLine("│  │  │ LAUNCH│→│ RESUME│→│ PAUSE │→│ STOP │                     │   │\n")
        sb.appendLine("│  │  └──────┘  └──────┘  └──────┘  └──────┘                     │   │\n")
        sb.appendLine("│  │                                                             │   │\n")
        sb.appendLine("│  └─────────────────────────────────────────────────────────────┘   │\n")
        sb.appendLine("│                                 │                                  │\n")
        sb.appendLine("│                                 │ Looper.loop()                    │\n")
        sb.appendLine("│                                 ▼                                  │\n")
        sb.appendLine("│  ┌─────────────────────────────────────────────────────────────┐   │\n")
        sb.appendLine("│  │                       H (Handler)                           │   │\n")
        sb.appendLine("│  │                                                             │   │\n")
        sb.appendLine("│  │  handleMessage(Message msg) {                               │   │\n")
        sb.appendLine("│  │      switch (msg.what) {                                    │   │\n")
        sb.appendLine("│  │          case LAUNCH_ACTIVITY:                              │   │\n")
        sb.appendLine("│  │              handleLaunchActivity(r);                       │   │\n")
        sb.appendLine("│  │              break;                                         │   │\n")
        sb.appendLine("│  │      }                                                      │   │\n")
        sb.appendLine("│  │  }                                                          │   │\n")
        sb.appendLine("│  │                                                             │   │\n")
        sb.appendLine("│  └─────────────────────────────────────────────────────────────┘   │\n")
        sb.appendLine("│                                 │                                  │\n")
        sb.appendLine("│                                 │ handleLaunchActivity()           │\n")
        sb.appendLine("│                                 ▼                                  │\n")
        sb.appendLine("│  ┌─────────────────────────────────────────────────────────────┐   │\n")
        sb.appendLine("│  │                      Activity                               │   │\n")
        sb.appendLine("│  │                                                             │   │\n")
        sb.appendLine("│  │  performLaunchActivity() {                                  │   │\n")
        sb.appendLine("│  │      activity = mInstrumentation.newActivity(...);          │   │\n")
        sb.appendLine("│  │      activity.attach(...);                                  │   │\n")
        sb.appendLine("│  │      mInstrumentation.callActivityOnCreate(activity, ...);  │   │\n")
        sb.appendLine("│  │  }                                                          │   │\n")
        sb.appendLine("│  │                                                             │   │\n")
        sb.appendLine("│  │  → onCreate() → onStart() → onResume()                      │   │\n")
        sb.appendLine("│  │                                                             │   │\n")
        sb.appendLine("│  └─────────────────────────────────────────────────────────────┘   │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")
        
        sb.appendLine("【sendMessage 源码】\n")
        sb.appendLine("```java")
        sb.appendLine("// ActivityThread.java")
        sb.appendLine("private void sendMessage(int what, Object obj) {")
        sb.appendLine("    sendMessage(what, obj, 0, 0, false);")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("private void sendMessage(int what, Object obj, int arg1, int arg2, boolean async) {")
        sb.appendLine("    // 如果已经是主线程，直接发送")
        sb.appendLine("    if (DEBUG_MESSAGES) {")
        sb.appendLine("        Slog.v(TAG, \"SCHEDULE \" + what + \" \" + mH.codeToString(what)")
        sb.appendLine("                + \": \" + arg1 + \" / \" + obj);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    Message msg = Message.obtain();")
        sb.appendLine("    msg.what = what;")
        sb.appendLine("    msg.obj = obj;")
        sb.appendLine("    msg.arg1 = arg1;")
        sb.appendLine("    msg.arg2 = arg2;")
        sb.appendLine("    ")
        sb.appendLine("    if (async) {")
        sb.appendLine("        msg.setAsynchronous(true);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 发送到主线程消息队列")
        sb.appendLine("    mH.sendMessage(msg);")
        sb.appendLine("}")
        sb.appendLine("```\n")
    }

    /**
     * 自定义 Handler 演示
     */
    private fun showCustomHandler() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("              自定义 Handler 演示")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【如何 Hook H 类】\n")
        sb.appendLine("```java")
        sb.appendLine("public class HHook {")
        sb.appendLine("    ")
        sb.appendLine("    private static final String TAG = \"HHook\";")
        sb.appendLine("    ")
        sb.appendLine("    public static void hook() {")
        sb.appendLine("        try {")
        sb.appendLine("            // 1. 获取 ActivityThread 实例")
        sb.appendLine("            Class<?> activityThreadClass = Class.forName(\"android.app.ActivityThread\");")
        sb.appendLine("            Method currentActivityThreadMethod = ")
        sb.appendLine("                    activityThreadClass.getDeclaredMethod(\"currentActivityThread\");")
        sb.appendLine("            Object activityThread = currentActivityThreadMethod.invoke(null);")
        sb.appendLine("            ")
        sb.appendLine("            // 2. 获取原始的 H Handler")
        sb.appendLine("            Field mHField = activityThreadClass.getDeclaredField(\"mH\");")
        sb.appendLine("            mHField.setAccessible(true);")
        sb.appendLine("            Handler originalHandler = (Handler) mHField.get(activityThread);")
        sb.appendLine("            ")
        sb.appendLine("            // 3. 获取 Handler 的 mCallback 字段")
        sb.appendLine("            Field mCallbackField = Handler.class.getDeclaredField(\"mCallback\");")
        sb.appendLine("            mCallbackField.setAccessible(true);")
        sb.appendLine("            ")
        sb.appendLine("            // 4. 创建自定义 Callback")
        sb.appendLine("            Handler.Callback customCallback = new Handler.Callback() {")
        sb.appendLine("                @Override")
        sb.appendLine("                public boolean handleMessage(Message msg) {")
        sb.appendLine("                    // 拦截消息")
        sb.appendLine("                    Log.d(TAG, \"Intercepted message: \" + msg.what);")
        sb.appendLine("                    ")
        sb.appendLine("                    switch (msg.what) {")
        sb.appendLine("                        case 100: // LAUNCH_ACTIVITY")
        sb.appendLine("                            Log.d(TAG, \"Activity launching...\");")
        sb.appendLine("                            // 可以做一些监控")
        sb.appendLine("                            break;")
        sb.appendLine("                    }")
        sb.appendLine("                    ")
        sb.appendLine("                    // 返回 false 让原始 Handler 继续处理")
        sb.appendLine("                    return false;")
        sb.appendLine("                }")
        sb.appendLine("            };")
        sb.appendLine("            ")
        sb.appendLine("            // 5. 替换 Callback")
        sb.appendLine("            mCallbackField.set(originalHandler, customCallback);")
        sb.appendLine("            ")
        sb.appendLine("            Log.d(TAG, \"H Hook success!\");")
        sb.appendLine("            ")
        sb.appendLine("        } catch (Exception e) {")
        sb.appendLine("            Log.e(TAG, \"H Hook failed\", e);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【Handler.Callback 机制】\n")
        sb.appendLine("```java")
        sb.appendLine("// Handler.dispatchMessage() 源码")
        sb.appendLine("public void dispatchMessage(Message msg) {")
        sb.appendLine("    // 1. 优先处理 Message 自带的 callback")
        sb.appendLine("    if (msg.callback != null) {")
        sb.appendLine("        handleCallback(msg);")
        sb.appendLine("    } else {")
        sb.appendLine("        // 2. 其次处理 Handler 的 mCallback")
        sb.appendLine("        if (mCallback != null) {")
        sb.appendLine("            if (mCallback.handleMessage(msg)) {")
        sb.appendLine("                return; // 如果返回 true，不再执行 handleMessage")
        sb.appendLine("            }")
        sb.appendLine("        }")
        sb.appendLine("        // 3. 最后执行 Handler.handleMessage()")
        sb.appendLine("        handleMessage(msg);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【消息处理优先级】\n")
        sb.appendLine("```\n")
        sb.appendLine("┌─────────────────────────────────────────┐\n")
        sb.appendLine("│        Handler.dispatchMessage()        │\n")
        sb.appendLine("└─────────────────────────────────────────┘\n")
        sb.appendLine("                    │")
        sb.appendLine("                    ▼")
        sb.appendLine("        ┌───────────────────────┐")
        sb.appendLine("        │ msg.callback != null? │")
        sb.appendLine("        └───────────────────────┘")
        sb.appendLine("           │ Yes            │ No")
        sb.appendLine("           ▼                ▼")
        sb.appendLine("    ┌─────────────┐   ┌─────────────────────┐")
        sb.appendLine("    │ handleCallback│  │ mCallback != null?  │")
        sb.appendLine("    └─────────────┘   └─────────────────────┘")
        sb.appendLine("                          │ Yes      │ No")
        sb.appendLine("                          ▼          ▼")
        sb.appendLine("                 ┌──────────────┐  ┌─────────────────┐")
        sb.appendLine("                 │ mCallback.   │  │ handleMessage() │")
        sb.appendLine("                 │ handleMessage│  │                 │")
        sb.appendLine("                 └──────────────┘  └─────────────────┘")
        sb.appendLine("                          │")
        sb.appendLine("                          ▼")
        sb.appendLine("                 ┌─────────────────┐")
        sb.appendLine("                 │ return true?    │")
        sb.appendLine("                 └─────────────────┘")
        sb.appendLine("                   │ Yes      │ No")
        sb.appendLine("                   ▼          ▼")
        sb.appendLine("               ┌───────┐  ┌─────────────────┐")
        sb.appendLine("               │ return│  │ handleMessage() │")
        sb.appendLine("               └───────┘  └─────────────────┘")
        sb.appendLine("```\n")
    }
}
