package com.peter.window.demo.activitythread.deep

import android.app.Activity
import android.app.Instrumentation
import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.os.IBinder
import android.os.PersistableBundle
import android.util.Log
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import com.peter.window.demo.R

/**
 * ActivityThread 深入篇 - Instrumentation 与生命周期
 *
 * === Instrumentation 详解 ===
 *
 * Instrumentation 是 Android 中用于监控应用和系统交互的类。
 * 它负责调用 Activity 的所有生命周期方法。
 *
 * 【核心作用】
 * 1. 创建 Activity 实例
 * 2. 调用 Activity 的生命周期方法（onCreate, onStart, onResume 等）
 * 3. 调用 Application 的生命周期方法
 * 4. 支持测试框架（JUnit）
 *
 * 【与 ActivityThread 的关系】
 * ActivityThread 持有 Instrumentation 实例，
 * 所有生命周期回调都通过 Instrumentation 执行。
 */
class InstrumentationActivity : AppCompatActivity() {

    private val sb = StringBuilder()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_instrumentation)
        
        showInstrumentationOverview()
        showCoreMethods()
        showLifeCycleFlow()
        showActivityCreation()
        showHookInstrumentation()
        
        findViewById<TextView>(R.id.tvContent).text = sb.toString()
    }

    /**
     * Instrumentation 概述
     */
    private fun showInstrumentationOverview() {
        sb.appendLine("═══════════════════════════════════════════════════")
        sb.appendLine("           Instrumentation 概述")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【什么是 Instrumentation】\n")
        sb.appendLine("Instrumentation 是 Android 的监控类，负责：")
        sb.appendLine("- 创建 Activity、Application 实例")
        sb.appendLine("- 调用生命周期方法")
        sb.appendLine("- 监控应用和系统交互")
        sb.appendLine("- 支持 UI 测试框架\n")
        
        sb.appendLine("【类定义】\n")
        sb.appendLine("```java")
        sb.appendLine("public class Instrumentation {")
        sb.appendLine("    ")
        sb.appendLine("    // Activity 待启动列表")
        sb.appendLine("    private List<ActivityWaiter> mWaitingActivities;")
        sb.appendLine("    ")
        sb.appendLine("    // Activity 生命周期回调")
        sb.appendLine("    private List<ActivityLifecycleCallbacks> mActivityLifecycleCallbacks;")
        sb.appendLine("    ")
        sb.appendLine("    // Activity 创建计数")
        sb.appendLine("    private int mActivityCount;")
        sb.appendLine("    ")
        sb.appendLine("    // 线程")
        sb.appendLine("    private Thread mThread;")
        sb.appendLine("    ")
        sb.appendLine("    // Context")
        sb.appendLine("    private Context mAppContext;")
        sb.appendLine("    ")
        sb.appendLine("    // 组件名")
        sb.appendLine("    private ComponentName mComponent;")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【在 ActivityThread 中的位置】\n")
        sb.appendLine("```\n")
        sb.appendLine("┌─────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                     ActivityThread                      │\n")
        sb.appendLine("│                                                         │\n")
        sb.appendLine("│  ┌─────────────────────────────────────────────────┐   │\n")
        sb.appendLine("│  │ mInstrumentation: Instrumentation               │   │\n")
        sb.appendLine("│  │                                                 │   │\n")
        sb.appendLine("│  │   newActivity()    → 创建 Activity              │   │\n")
        sb.appendLine("│  │   callActivityOnCreate() → onCreate()           │   │\n")
        sb.appendLine("│  │   callActivityOnStart()   → onStart()           │   │\n")
        sb.appendLine("│  │   callActivityOnResume()  → onResume()          │   │\n")
        sb.appendLine("│  │   callActivityOnPause()   → onPause()           │   │\n")
        sb.appendLine("│  │   callActivityOnStop()    → onStop()            │   │\n")
        sb.appendLine("│  │   callActivityOnDestroy() → onDestroy()         │   │\n")
        sb.appendLine("│  │                                                 │   │\n")
        sb.appendLine("│  │   newApplication()   → 创建 Application         │   │\n")
        sb.appendLine("│  │   callApplicationOnCreate() → Application.onCreate()")
        sb.appendLine("│  │                                                 │   │\n")
        sb.appendLine("│  └─────────────────────────────────────────────────┘   │\n")
        sb.appendLine("│                         │                              │\n")
        sb.appendLine("│                         ▼                              │\n")
        sb.appendLine("│  ┌─────────────────────────────────────────────────┐   │\n")
        sb.appendLine("│  │                   Activity                      │   │\n")
        sb.appendLine("│  │                                                 │   │\n")
        sb.appendLine("│  │   onCreate() → onStart() → onResume()           │   │\n")
        sb.appendLine("│  │   onPause()  → onStop()  → onDestroy()          │   │\n")
        sb.appendLine("│  │                                                 │   │\n")
        sb.appendLine("│  └─────────────────────────────────────────────────┘   │\n")
        sb.appendLine("│                                                         │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")
    }

    /**
     * 核心方法
     */
    private fun showCoreMethods() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("           Instrumentation 核心方法")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【Activity 相关方法】\n")
        sb.appendLine("┌─────────────────────────────────┬────────────────────────────────┐\n")
        sb.appendLine("│ 方法名                          │ 说明                           │\n")
        sb.appendLine("├─────────────────────────────────┼────────────────────────────────┤\n")
        sb.appendLine("│ newActivity()                   │ 通过反射创建 Activity 实例      │\n")
        sb.appendLine("│ callActivityOnCreate()          │ 调用 onCreate()                │\n")
        sb.appendLine("│ callActivityOnStart()           │ 调用 onStart()                 │\n")
        sb.appendLine("│ callActivityOnResume()          │ 调用 onResume()                │\n")
        sb.appendLine("│ callActivityOnPause()           │ 调用 onPause()                 │\n")
        sb.appendLine("│ callActivityOnStop()            │ 调用 onStop()                  │\n")
        sb.appendLine("│ callActivityOnDestroy()         │ 调用 onDestroy()               │\n")
        sb.appendLine("│ callActivityOnRestoreInstanceState() │ 调用 onRestoreInstanceState() │\n")
        sb.appendLine("│ callActivityOnPostCreate()      │ 调用 onPostCreate()            │\n")
        sb.appendLine("│ callActivityOnNewIntent()       │ 调用 onNewIntent()             │\n")
        sb.appendLine("└─────────────────────────────────┴────────────────────────────────┘\n")
        
        sb.appendLine("【Application 相关方法】\n")
        sb.appendLine("┌─────────────────────────────────┬────────────────────────────────┐\n")
        sb.appendLine("│ 方法名                          │ 说明                           │\n")
        sb.appendLine("├─────────────────────────────────┼────────────────────────────────┤\n")
        sb.appendLine("│ newApplication()                │ 创建 Application 实例          │\n")
        sb.appendLine("│ callApplicationOnCreate()       │ 调用 Application.onCreate()    │\n")
        sb.appendLine("└─────────────────────────────────┴────────────────────────────────┘\n")
        
        sb.appendLine("【启动 Activity 相关方法】\n")
        sb.appendLine("┌─────────────────────────────────┬────────────────────────────────┐\n")
        sb.appendLine("│ 方法名                          │ 说明                           │\n")
        sb.appendLine("├─────────────────────────────────┼────────────────────────────────┤\n")
        sb.appendLine("│ execStartActivity()             │ 启动 Activity（入口）          │\n")
        sb.appendLine("│ execStartActivityFromAppTask()  │ 从 AppTask 启动               │\n")
        sb.appendLine("│ execStartActivityForResult()    │ startActivityForResult       │\n")
        sb.appendLine("│ execStartActivityAndWait()      │ 启动并等待                    │\n")
        sb.appendLine("│ validateActivityRequest()       │ 验证请求                      │\n")
        sb.appendLine("└─────────────────────────────────┴────────────────────────────────┘\n")
        
        sb.appendLine("【源码示例】\n")
        sb.appendLine("```java")
        sb.appendLine("// newActivity - 创建 Activity 实例")
        sb.appendLine("public Activity newActivity(Class<?> clazz, Context context,")
        sb.appendLine("        IBinder token, Application application, Intent intent,") 
        sb.appendLine("        ActivityInfo info, CharSequence title, Activity parent,")
        sb.appendLine("        String id, Object lastNonConfigurationInstance) throws Exception {")
        sb.appendLine("    Activity activity = (Activity) clazz.newInstance();")
        sb.appendLine("    ActivityThread aThread = null;")
        sb.appendLine("    activity.attach(context, aThread, this, token, 0 /* ident */,")
        sb.appendLine("            application, intent, info, title, parent, id,")
        sb.appendLine("            (NonConfigurationInstance) lastNonConfigurationInstance,")
        sb.appendLine("            new Configuration(), null /* referrer */, null /* voiceInteractor */);")
        sb.appendLine("    return activity;")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("// newActivity - 通过类名创建")
        sb.appendLine("public Activity newActivity(ClassLoader cl, String className, Intent intent)")
        sb.appendLine("        throws InstantiationException, IllegalAccessException,")
        sb.appendLine("        ClassNotFoundException {")
        sb.appendLine("    String pkg = intent != null && intent.getComponent() != null")
        sb.appendLine("            ? intent.getComponent().getPackageName() : null;")
        sb.appendLine("    return getFactory(pkg).instantiateActivity(cl, className, intent);")
        sb.appendLine("}")
        sb.appendLine("```\n")
    }

    /**
     * 生命周期调用流程
     */
    private fun showLifeCycleFlow() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("           生命周期调用流程")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【onCreate 调用链】\n")
        sb.appendLine("```java")
        sb.appendLine("// ActivityThread.performLaunchActivity()")
        sb.appendLine("private Activity performLaunchActivity(ActivityClientRecord r, Intent customIntent) {")
        sb.appendLine("    // ... 创建 Activity")
        sb.appendLine("    ")
        sb.appendLine("    // 调用 onCreate")
        sb.appendLine("    if (r.isPersistable()) {")
        sb.appendLine("        mInstrumentation.callActivityOnCreate(activity, r.state, r.persistentState);")
        sb.appendLine("    } else {")
        sb.appendLine("        mInstrumentation.callActivityOnCreate(activity, r.state);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("// Instrumentation.callActivityOnCreate()")
        sb.appendLine("public void callActivityOnCreate(Activity activity, Bundle icicle) {")
        sb.appendLine("    prePerformCreate(activity);")
        sb.appendLine("    activity.performCreate(icicle);")
        sb.appendLine("    postPerformCreate(activity);")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("// Activity.performCreate()")
        sb.appendLine("final void performCreate(Bundle icicle, PersistableBundle persistentState) {")
        sb.appendLine("    // 分发 Fragment 事件")
        sb.appendLine("    mFragments.restoreAllState(icicle, mFragments.dispatchActivityCreated());")
        sb.appendLine("    ")
        sb.appendLine("    // 调用 onCreate")
        sb.appendLine("    if (persistentState != null) {")
        sb.appendLine("        onCreate(icicle, persistentState);")
        sb.appendLine("    } else {")
        sb.appendLine("        onCreate(icicle);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 通知 Fragment")
        sb.appendLine("    mFragments.dispatchActivityCreated();")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【onResume 调用链】\n")
        sb.appendLine("```java")
        sb.appendLine("// ActivityThread.handleResumeActivity()")
        sb.appendLine("public void handleResumeActivity(IBinder token, boolean finalStateRequest,")
        sb.appendLine("        boolean isForward, String reason) {")
        sb.appendLine("    // 调用 performResume")
        sb.appendLine("    final ActivityClientRecord r = performResumeActivity(token, finalStateRequest, reason);")
        sb.appendLine("    ")
        sb.appendLine("    if (r != null) {")
        sb.appendLine("        final Activity a = r.activity;")
        sb.appendLine("        ")
        sb.appendLine("        // 添加 DecorView 到 WindowManager")
        sb.appendLine("        if (r.window == null && !a.mFinished && willBeVisible) {")
        sb.appendLine("            r.window = r.activity.getWindow();")
        sb.appendLine("            View decor = r.window.getDecorView();")
        sb.appendLine("            ViewManager wm = a.getWindowManager();")
        sb.appendLine("            WindowManager.LayoutParams l = r.window.getAttributes();")
        sb.appendLine("            wm.addView(decor, l);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("// ActivityThread.performResumeActivity()")
        sb.appendLine("public ActivityClientRecord performResumeActivity(IBinder token,")
        sb.appendLine("        boolean finalStateRequest, String reason) {")
        sb.appendLine("    ActivityClientRecord r = mActivities.get(token);")
        sb.appendLine("    r.activity.performResume();")
        sb.appendLine("    return r;")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("// Activity.performResume()")
        sb.appendLine("final void performResume() {")
        sb.appendLine("    performRestart();  // 会调用 onStart()")
        sb.appendLine("    ")
        sb.appendLine("    mFragments.execPendingActions();")
        sb.appendLine("    mLastNonConfigurationInstances = null;")
        sb.appendLine("    ")
        sb.appendLine("    // 调用 onResume")
        sb.appendLine("    mInstrumentation.callActivityOnResume(this);")
        sb.appendLine("    ")
        sb.appendLine("    // 通知 Fragment")
        sb.appendLine("    mFragments.dispatchResume();")
        sb.appendLine("    mFragments.execPendingActions();")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("// Instrumentation.callActivityOnResume()")
        sb.appendLine("public void callActivityOnResume(Activity activity) {")
        sb.appendLine("    activity.mResumed = true;")
        sb.appendLine("    activity.onResume();")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【完整生命周期时序图】\n")
        sb.appendLine("```\n")
        sb.appendLine("AMS              ActivityThread          Instrumentation        Activity")
        sb.appendLine(" │                      │                        │                   │")
        sb.appendLine(" │ scheduleLaunchActivity│                       │                   │")
        sb.appendLine(" │─────────────────────>│                        │                   │")
        sb.appendLine(" │                      │ performLaunchActivity │                   │")
        sb.appendLine(" │                      │───────────────────────>│                   │")
        sb.appendLine(" │                      │                        │ newActivity()     │")
        sb.appendLine(" │                      │                        │───────────────────>│")
        sb.appendLine(" │                      │                        │                   │ Activity 实例")
        sb.appendLine(" │                      │                        │                   │")
        sb.appendLine(" │                      │                        │ callActivityOnCreate")
        sb.appendLine(" │                      │                        │───────────────────>│")
        sb.appendLine(" │                      │                        │                   │ onCreate()")
        sb.appendLine(" │                      │                        │                   │")
        sb.appendLine(" │ scheduleResumeActivity│                       │                   │")
        sb.appendLine(" │─────────────────────>│                        │                   │")
        sb.appendLine(" │                      │ handleResumeActivity  │                   │")
        sb.appendLine(" │                      │ performResumeActivity │                   │")
        sb.appendLine(" │                      │───────────────────────>│                   │")
        sb.appendLine(" │                      │                        │ callActivityOnResume")
        sb.appendLine(" │                      │                        │───────────────────>│")
        sb.appendLine(" │                      │                        │                   │ onResume()")
        sb.appendLine("```\n")
    }

    /**
     * Activity 创建过程
     */
    private fun showActivityCreation() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("           Activity 创建完整过程")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【performLaunchActivity 完整流程】\n")
        sb.appendLine("```java")
        sb.appendLine("private Activity performLaunchActivity(ActivityClientRecord r, Intent customIntent) {")
        sb.appendLine("    ")
        sb.appendLine("    // Step 1: 获取 ActivityInfo")
        sb.appendLine("    ActivityInfo aInfo = r.activityInfo;")
        sb.appendLine("    if (r.packageInfo == null) {")
        sb.appendLine("        r.packageInfo = getPackageInfo(aInfo.applicationInfo,")
        sb.appendLine("                r.compatInfo, Context.CONTEXT_INCLUDE_CODE);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // Step 2: 创建 ComponentName")
        sb.appendLine("    ComponentName component = r.intent.getComponent();")
        sb.appendLine("    if (component == null) {")
        sb.appendLine("        component = r.intent.resolveActivity(")
        sb.appendLine("                mInitialApplication.getPackageManager());")
        sb.appendLine("        r.intent.setComponent(component);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    if (r.activityInfo.targetActivity != null) {")
        sb.appendLine("        component = new ComponentName(r.activityInfo.packageName,")
        sb.appendLine("                r.activityInfo.targetActivity);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // Step 3: 创建 Activity Context")
        sb.appendLine("    ContextImpl appContext = createBaseContextForActivity(r);")
        sb.appendLine("    Activity activity = null;")
        sb.appendLine("    ")
        sb.appendLine("    // Step 4: 创建 Activity 实例")
        sb.appendLine("    try {")
        sb.appendLine("        java.lang.ClassLoader cl = appContext.getClassLoader();")
        sb.appendLine("        activity = mInstrumentation.newActivity(cl, component.getClassName(), r.intent);")
        sb.appendLine("        StrictMode.incrementExpectedActivityCount(activity.getClass());")
        sb.appendLine("        r.intent.setExtrasClassLoader(cl);")
        sb.appendLine("        r.intent.prepareToEnterProcess();")
        sb.appendLine("        if (r.state != null) {")
        sb.appendLine("            r.state.setClassLoader(cl);")
        sb.appendLine("        }")
        sb.appendLine("    } catch (Exception e) {")
        sb.appendLine("        if (!mInstrumentation.onException(activity, e)) {")
        sb.appendLine("            throw new RuntimeException(")
        sb.appendLine("                \"Unable to instantiate activity \" + component")
        sb.appendLine("                + \": \" + e.toString(), e);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // Step 5: 获取/创建 Application")
        sb.appendLine("    try {")
        sb.appendLine("        Application app = r.packageInfo.makeApplication(false, mInstrumentation);")
        sb.appendLine("        ")
        sb.appendLine("        if (activity != null) {")
        sb.appendLine("            // Step 6: 创建 Activity 的 Window")
        sb.appendLine("            CharSequence title = r.activityInfo.loadLabel(appContext.getPackageManager());")
        sb.appendLine("            Configuration config = new Configuration(mCompatConfiguration);")
        sb.appendLine("            ")
        sb.appendLine("            // Step 7: 调用 activity.attach()")
        sb.appendLine("            activity.attach(appContext, this, getInstrumentation(), r.token,")
        sb.appendLine("                    r.ident, app, r.intent, r.activityInfo, title, r.parent,")
        sb.appendLine("                    r.embeddedID, r.lastNonConfigurationInstances, config,")
        sb.appendLine("                    r.referrer, r.voiceInteractor, window, r.configCallback,")
        sb.appendLine("                    r.assistToken, r.shareableActivityToken);")
        sb.appendLine("            ")
        sb.appendLine("            if (customIntent != null) {")
        sb.appendLine("                activity.mIntent = customIntent;")
        sb.appendLine("            }")
        sb.appendLine("            r.lastNonConfigurationInstances = null;")
        sb.appendLine("            checkAndBlockForNetworkAccess();")
        sb.appendLine("            activity.mStartedActivity = false;")
        sb.appendLine("            int theme = r.activityInfo.getThemeResource();")
        sb.appendLine("            if (theme != 0) {")
        sb.appendLine("                activity.setTheme(theme);")
        sb.appendLine("            }")
        sb.appendLine("            ")
        sb.appendLine("            activity.mCalled = false;")
        sb.appendLine("            ")
        sb.appendLine("            // Step 8: 调用 onCreate")
        sb.appendLine("            if (r.isPersistable()) {")
        sb.appendLine("                mInstrumentation.callActivityOnCreate(activity, r.state, r.persistentState);")
        sb.appendLine("            } else {")
        sb.appendLine("                mInstrumentation.callActivityOnCreate(activity, r.state);")
        sb.appendLine("            }")
        sb.appendLine("            ")
        sb.appendLine("            if (!activity.mCalled) {")
        sb.appendLine("                throw new SuperNotCalledException(")
        sb.appendLine("                    \"Activity \" + r.intent.getComponent().toShortString() +")
        sb.appendLine("                    \" did not call through to super.onCreate()\");")
        sb.appendLine("            }")
        sb.appendLine("            r.activity = activity;")
        sb.appendLine("            mLastStartedActivityActivityRecord = r;")
        sb.appendLine("        }")
        sb.appendLine("        r.setState(ON_CREATE);")
        sb.appendLine("        ")
        sb.appendLine("        // Step 9: 保存 Activity 记录")
        sb.appendLine("        mActivities.put(r.token, r);")
        sb.appendLine("        ")
        sb.appendLine("    } catch (SuperNotCalledException e) {")
        sb.appendLine("        throw e;")
        sb.appendLine("    } catch (Exception e) {")
        sb.appendLine("        if (!mInstrumentation.onException(activity, e)) {")
        sb.appendLine("            throw new RuntimeException(")
        sb.appendLine("                \"Unable to start activity \" + component")
        sb.appendLine("                + \": \" + e.toString(), e);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    return activity;")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【Activity 创建步骤总结】\n")
        sb.appendLine("```\n")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                 performLaunchActivity                       │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("                            │")
        sb.appendLine("        ┌───────────────────┼───────────────────┐")
        sb.appendLine("        ▼                   ▼                   ▼")
        sb.appendLine("┌───────────────┐   ┌───────────────┐   ┌───────────────┐\n")
        sb.appendLine("│ 1.获取ActivityInfo│   │ 2.创建ContextImpl│   │ 3.创建Activity │\n")
        sb.appendLine("│   packageInfo   │   │   appContext   │   │  (反射创建)   │\n")
        sb.appendLine("└───────────────┘   └───────────────┘   └───────────────┘\n")
        sb.appendLine("                                                │")
        sb.appendLine("                    ┌───────────────────────────┘")
        sb.appendLine("                    ▼")
        sb.appendLine("        ┌───────────────────────────────────────┐")
        sb.appendLine("        │ 4. activity.attach()                  │")
        sb.appendLine("        │   - 创建 PhoneWindow                  │")
        sb.appendLine("        │   - 设置 WindowManager               │")
        sb.appendLine("        │   - 绑定各种引用                      │")
        sb.appendLine("        └───────────────────────────────────────┘")
        sb.appendLine("                            │")
        sb.appendLine("                            ▼")
        sb.appendLine("        ┌───────────────────────────────────────┐")
        sb.appendLine("        │ 5. mInstrumentation.callActivityOnCreate()")
        sb.appendLine("        │   → activity.performCreate()          │")
        sb.appendLine("        │     → activity.onCreate()             │")
        sb.appendLine("        └───────────────────────────────────────┘")
        sb.appendLine("                            │")
        sb.appendLine("                            ▼")
        sb.appendLine("        ┌───────────────────────────────────────┐")
        sb.appendLine("        │ 6. mActivities.put(token, record)     │")
        sb.appendLine("        │    保存 Activity 记录                  │")
        sb.appendLine("        └───────────────────────────────────────┘")
        sb.appendLine("```\n")
    }

    /**
     * Hook Instrumentation
     */
    private fun showHookInstrumentation() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("           Hook Instrumentation 实践")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【为什么要 Hook Instrumentation】\n")
        sb.appendLine("- 监控所有 Activity 生命周期")
        sb.appendLine("- 实现 AOP（面向切面编程）")
        sb.appendLine("- 统计启动耗时")
        sb.appendLine("- 插件化框架基础\n")
        
        sb.appendLine("【自定义 Instrumentation】\n")
        sb.appendLine("```java")
        sb.appendLine("public class CustomInstrumentation extends Instrumentation {")
        sb.appendLine("    ")
        sb.appendLine("    private static final String TAG = \"CustomInstrumentation\";")
        sb.appendLine("    private Instrumentation mOriginal;")
        sb.appendLine("    ")
        sb.appendLine("    public CustomInstrumentation(Instrumentation original) {")
        sb.appendLine("        mOriginal = original;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void callActivityOnCreate(Activity activity, Bundle icicle) {")
        sb.appendLine("        long start = System.currentTimeMillis();")
        sb.appendLine("        Log.d(TAG, \"Before onCreate: \" + activity.getClass().getSimpleName());")
        sb.appendLine("        ")
        sb.appendLine("        super.callActivityOnCreate(activity, icicle);")
        sb.appendLine("        ")
        sb.appendLine("        long cost = System.currentTimeMillis() - start;")
        sb.appendLine("        Log.d(TAG, \"After onCreate: \" + activity.getClass().getSimpleName()")
        sb.appendLine("                + \", cost: \" + cost + \"ms\");")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void callActivityOnStart(Activity activity) {")
        sb.appendLine("        long start = System.currentTimeMillis();")
        sb.appendLine("        Log.d(TAG, \"Before onStart: \" + activity.getClass().getSimpleName());")
        sb.appendLine("        ")
        sb.appendLine("        super.callActivityOnStart(activity);")
        sb.appendLine("        ")
        sb.appendLine("        long cost = System.currentTimeMillis() - start;")
        sb.appendLine("        Log.d(TAG, \"After onStart: \" + activity.getClass().getSimpleName()")
        sb.appendLine("                + \", cost: \" + cost + \"ms\");")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void callActivityOnResume(Activity activity) {")
        sb.appendLine("        long start = System.currentTimeMillis();")
        sb.appendLine("        Log.d(TAG, \"Before onResume: \" + activity.getClass().getSimpleName());")
        sb.appendLine("        ")
        sb.appendLine("        super.callActivityOnResume(activity);")
        sb.appendLine("        ")
        sb.appendLine("        long cost = System.currentTimeMillis() - start;")
        sb.appendLine("        Log.d(TAG, \"After onResume: \" + activity.getClass().getSimpleName()")
        sb.appendLine("                + \", cost: \" + cost + \"ms\");")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void callActivityOnPause(Activity activity) {")
        sb.appendLine("        Log.d(TAG, \"onPause: \" + activity.getClass().getSimpleName());")
        sb.appendLine("        super.callActivityOnPause(activity);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void callActivityOnStop(Activity activity) {")
        sb.appendLine("        Log.d(TAG, \"onStop: \" + activity.getClass().getSimpleName());")
        sb.appendLine("        super.callActivityOnStop(activity);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void callActivityOnDestroy(Activity activity) {")
        sb.appendLine("        Log.d(TAG, \"onDestroy: \" + activity.getClass().getSimpleName());")
        sb.appendLine("        super.callActivityOnDestroy(activity);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public ActivityResult execStartActivity(")
        sb.appendLine("            Context who, IBinder contextThread, IBinder token, Activity target,")
        sb.appendLine("            Intent intent, int requestCode, Bundle options) {")
        sb.appendLine("        Log.d(TAG, \"execStartActivity: \" + intent.getComponent());")
        sb.appendLine("        ")
        sb.appendLine("        // 可以在这里做拦截，如插件化加载")
        sb.appendLine("        ")
        sb.appendLine("        try {")
        sb.appendLine("            Method method = Instrumentation.class.getDeclaredMethod(")
        sb.appendLine("                    \"execStartActivity\", Context.class, IBinder.class,")
        sb.appendLine("                    IBinder.class, Activity.class, Intent.class,")
        sb.appendLine("                    int.class, Bundle.class);")
        sb.appendLine("            method.setAccessible(true);")
        sb.appendLine("            return (ActivityResult) method.invoke(mOriginal, who,")
        sb.appendLine("                    contextThread, token, target, intent, requestCode, options);")
        sb.appendLine("        } catch (Exception e) {")
        sb.appendLine("            Log.e(TAG, \"execStartActivity failed\", e);")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        return null;")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【Hook Instrumentation 的方法】\n")
        sb.appendLine("```java")
        sb.appendLine("public class InstrumentationHook {")
        sb.appendLine("    ")
        sb.appendLine("    public static void hook() {")
        sb.appendLine("        try {")
        sb.appendLine("            // 1. 获取 ActivityThread 实例")
        sb.appendLine("            Class<?> activityThreadClass = Class.forName(\"android.app.ActivityThread\");")
        sb.appendLine("            Method currentActivityThreadMethod = ")
        sb.appendLine("                    activityThreadClass.getDeclaredMethod(\"currentActivityThread\");")
        sb.appendLine("            Object activityThread = currentActivityThreadMethod.invoke(null);")
        sb.appendLine("            ")
        sb.appendLine("            // 2. 获取原始的 Instrumentation")
        sb.appendLine("            Field mInstrumentationField = ")
        sb.appendLine("                    activityThreadClass.getDeclaredField(\"mInstrumentation\");")
        sb.appendLine("            mInstrumentationField.setAccessible(true);")
        sb.appendLine("            Instrumentation original = ")
        sb.appendLine("                    (Instrumentation) mInstrumentationField.get(activityThread);")
        sb.appendLine("            ")
        sb.appendLine("            // 3. 替换为自定义 Instrumentation")
        sb.appendLine("            CustomInstrumentation custom = new CustomInstrumentation(original);")
        sb.appendLine("            mInstrumentationField.set(activityThread, custom);")
        sb.appendLine("            ")
        sb.appendLine("            Log.d(\"Hook\", \"Instrumentation hooked successfully\");")
        sb.appendLine("            ")
        sb.appendLine("        } catch (Exception e) {")
        sb.appendLine("            Log.e(\"Hook\", \"Failed to hook Instrumentation\", e);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【Hook 后的调用流程】\n")
        sb.appendLine("```\n")
        sb.appendLine("ActivityThread           CustomInstrumentation        Activity")
        sb.appendLine("       │                        │                         │")
        sb.appendLine("       │ performLaunchActivity  │                         │")
        sb.appendLine("       │                        │                         │")
        sb.appendLine("       │ mInstrumentation.      │                         │")
        sb.appendLine("       │ callActivityOnCreate() │                         │")
        sb.appendLine("       │───────────────────────>│                         │")
        sb.appendLine("       │                        │ // 记录开始时间         │")
        sb.appendLine("       │                        │ Log.d(\"Before onCreate\")│")
        sb.appendLine("       │                        │                         │")
        sb.appendLine("       │                        │ super.callActivityOnCreate")
        sb.appendLine("       │                        │─────────────────────────>")
        sb.appendLine("       │                        │                         │ onCreate()")
        sb.appendLine("       │                        │                         │")
        sb.appendLine("       │                        │ // 记录结束时间         │")
        sb.appendLine("       │                        │ Log.d(\"After onCreate\") │")
        sb.appendLine("```\n")
    }
}
