package com.peter.window.demo.viewroot.advanced

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import com.peter.window.demo.databinding.ActivityMeasureLayoutDrawBinding

/**
 * 进阶篇：测量、布局、绘制流程详解
 * 
 * performTraversals() 是 ViewRootImpl 最核心的方法，
 * 它负责执行 View 树的测量、布局、绘制三个步骤。
 * 
 * 流程图：
 * performTraversals()
 *     ├── performMeasure() → measure() → onMeasure()
 *     ├── performLayout()  → layout()  → onLayout()
 *     └── performDraw()    → draw()    → onDraw()
 */
class MeasureLayoutDrawActivity : AppCompatActivity() {

    private lateinit var binding: ActivityMeasureLayoutDrawBinding
    private val sb = StringBuilder()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMeasureLayoutDrawBinding.inflate(layoutInflater)
        setContentView(binding.root)
        supportActionBar?.setDisplayHomeAsUpEnabled(true)

        setupListeners()
        showPerformTraversals()
    }

    private fun setupListeners() {
        binding.btnTraversals.setOnClickListener { showPerformTraversals() }
        binding.btnMeasure.setOnClickListener { showMeasureProcess() }
        binding.btnLayout.setOnClickListener { showLayoutProcess() }
        binding.btnDraw.setOnClickListener { showDrawProcess() }
        binding.btnMeasureSpec.setOnClickListener { showMeasureSpec() }
        binding.btnForceLayout.setOnClickListener { showForceLayoutProcess() }
        binding.btnInvalidate.setOnClickListener { showInvalidateProcess() }
        binding.btnRequestLayout.setOnClickListener { showRequestLayoutProcess() }
    }

    /**
     * performTraversals() 整体流程
     */
    private fun showPerformTraversals() {
        sb.clear()
        sb.appendLine("=== performTraversals() 核心流程 ===\n")
        
        sb.appendLine("【方法签名】")
        sb.appendLine("```java")
        sb.appendLine("void performTraversals() {")
        sb.appendLine("    // 这个方法非常长，超过 700 行")
        sb.appendLine("    // 但核心就是执行三个操作")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【核心流程】")
        sb.appendLine("```java")
        sb.appendLine("void performTraversals() {")
        sb.appendLine("    // 1. 获取窗口尺寸")
        sb.appendLine("    int desiredWindowWidth = mWinFrame.width();")
        sb.appendLine("    int desiredWindowHeight = mWinFrame.height();")
        sb.appendLine("    ")
        sb.appendLine("    // 2. 检查是否需要重新布局")
        sb.appendLine("    boolean layoutRequested = mLayoutRequested && (!mStopped || mReportNextDraw);")
        sb.appendLine("    ")
        sb.appendLine("    // 3. 窗口尺寸变化时")
        sb.appendLine("    if (layoutRequested) {")
        sb.appendLine("        // ... 获取 MeasureSpec")
        sb.appendLine("        // ... 测量层级")
        sb.appendLine("        ")
        sb.appendLine("        // 首次布局或窗口尺寸变化")
        sb.appendLine("        if (!mStopped || mReportNextDraw) {")
        sb.appendLine("            // 询问 WMS 是否需要重新分配窗口")
        sb.appendLine("            relayoutResult = relayoutWindow(params, viewVisibility, insetsPending);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 4. 执行测量")
        sb.appendLine("    if (!mStopped || mReportNextDraw) {")
        sb.appendLine("        performMeasure(childWidthMeasureSpec, childHeightMeasureSpec);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 5. 执行布局")
        sb.appendLine("    if (didLayout) {")
        sb.appendLine("        performLayout(lp, desiredWindowWidth, desiredWindowHeight);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 6. 执行绘制")
        sb.appendLine("    if (!cancelDraw) {")
        sb.appendLine("        performDraw();")
        sb.appendLine("    } else {")
        sb.appendLine("        // 不需要绘制")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【触发条件】")
        sb.appendLine("performTraversals() 在以下情况被触发：n")
        sb.appendLine("1. 首次 setView() 时通过 requestLayout() 触发")
        sb.appendLine("2. View 调用 requestLayout() 时")
        sb.appendLine("3. View 调用 invalidate() 时（可能跳过测量）")
        sb.appendLine("4. 窗口属性变化时")
        sb.appendLine("5. VSync 信号到来时\n")
        
        sb.appendLine("【完整流程图】")
        sb.appendLine("```\n")
        sb.appendLine("    scheduleTraversals()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("    mChoreographer.postCallback()")
        sb.appendLine("           │")
        sb.appendLine("           ↓ (VSync 信号)")
        sb.appendLine("    doTraversal()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("    performTraversals()")
        sb.appendLine("           │")
        sb.appendLine("     ┌─────┼─────┐")
        sb.appendLine("     ↓     ↓     ↓")
        sb.appendLine("  measure layout draw")
        sb.appendLine("     │     │     │")
        sb.appendLine("     ↓     ↓     ↓")
        sb.appendLine(" onMeasure onLayout onDraw")
        sb.appendLine("```")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * 测量流程详解
     */
    private fun showMeasureProcess() {
        sb.clear()
        sb.appendLine("=== 测量流程 (Measure) ===\n")
        
        sb.appendLine("【performMeasure】")
        sb.appendLine("```java")
        sb.appendLine("private void performMeasure(int widthMeasureSpec, int heightMeasureSpec) {")
        sb.appendLine("    Trace.traceBegin(Trace.TRACE_TAG_VIEW, \"measure\");")
        sb.appendLine("    try {")
        sb.appendLine("        mView.measure(widthMeasureSpec, heightMeasureSpec);")
        sb.appendLine("    } finally {")
        sb.appendLine("        Trace.traceEnd(Trace.TRACE_TAG_VIEW);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【View.measure】")
        sb.appendLine("```java")
        sb.appendLine("public final void measure(int widthMeasureSpec, int heightMeasureSpec) {")
        sb.appendLine("    // 检查是否需要强制测量或尺寸变化")
        sb.appendLine("    boolean forceLayout = (mPrivateFlags & PFLAG_FORCE_LAYOUT) == PFLAG_FORCE_LAYOUT;")
        sb.appendLine("    ")
        sb.appendLine("    // 检查 MeasureSpec 是否变化")
        sb.appendLine("    final boolean specChanged = widthMeasureSpec != mOldWidthMeasureSpec")
        sb.appendLine("            || heightMeasureSpec != mOldHeightMeasureSpec;")
        sb.appendLine("    final boolean isSpecExactly = MeasureSpec.getMode(widthMeasureSpec) == MeasureSpec.EXACTLY")
        sb.appendLine("            && MeasureSpec.getMode(heightMeasureSpec) == MeasureSpec.EXACTLY;")
        sb.appendLine("    final boolean matchesSpecSize = getMeasuredWidth() == MeasureSpec.getSize(widthMeasureSpec)")
        sb.appendLine("            && getMeasuredHeight() == MeasureSpec.getSize(heightMeasureSpec);")
        sb.appendLine("    final boolean needsLayout = specChanged && (sAlwaysRemeasureExactly || !isSpecExactly")
        sb.appendLine("            || !matchesSpecSize);")
        sb.appendLine("    ")
        sb.appendLine("    if (forceLayout || needsLayout) {")
        sb.appendLine("        // 清除测量尺寸")
        sb.appendLine("        mPrivateFlags &= ~PFLAG_MEASURED_DIMENSION_SET;")
        sb.appendLine("        ")
        sb.appendLine("        // 开始测量")
        sb.appendLine("        onMeasure(widthMeasureSpec, heightMeasureSpec);")
        sb.appendLine("        ")
        sb.appendLine("        // 检查是否调用了 setMeasuredDimension")
        sb.appendLine("        if ((mPrivateFlags & PFLAG_MEASURED_DIMENSION_SET) != PFLAG_MEASURED_DIMENSION_SET) {")
        sb.appendLine("            throw new IllegalStateException(\"View with id \" + getId() +")
        sb.appendLine("                \": onMeasure() did not set the measured dimension\");")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        // 标记已测量")
        sb.appendLine("        mPrivateFlags |= PFLAG_LAYOUT_REQUIRED;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    mOldWidthMeasureSpec = widthMeasureSpec;")
        sb.appendLine("    mOldHeightMeasureSpec = heightMeasureSpec;")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【View.onMeasure】")
        sb.appendLine("```java")
        sb.appendLine("protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {")
        sb.appendLine("    // 默认实现：使用背景最小尺寸或建议尺寸")
        sb.appendLine("    setMeasuredDimension(")
        sb.appendLine("        getDefaultSize(getSuggestedMinimumWidth(), widthMeasureSpec),")
        sb.appendLine("        getDefaultSize(getSuggestedMinimumHeight(), heightMeasureSpec)")
        sb.appendLine("    );")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【ViewGroup.onMeasure】")
        sb.appendLine("```java")
        sb.appendLine("// ViewGroup 需要测量所有子 View")
        sb.appendLine("protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {")
        sb.appendLine("    // 遍历子 View")
        sb.appendLine("    final int childCount = getChildCount();")
        sb.appendLine("    for (int i = 0; i < childCount; i++) {")
        sb.appendLine("        final View child = getChildAt(i);")
        sb.appendLine("        ")
        sb.appendLine("        // 测量子 View")
        sb.appendLine("        measureChild(child, widthMeasureSpec, heightMeasureSpec);")
        sb.appendLine("        // 或者")
        sb.appendLine("        measureChildWithMargins(child, widthMeasureSpec, ...);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 设置自己的尺寸")
        sb.appendLine("    setMeasuredDimension(width, height);")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【measureChild】")
        sb.appendLine("```java")
        sb.appendLine("protected void measureChild(View child, int parentWidthMeasureSpec,")
        sb.appendLine("        int parentHeightMeasureSpec) {")
        sb.appendLine("    final LayoutParams lp = child.getLayoutParams();")
        sb.appendLine("    ")
        sb.appendLine("    // 根据父容器的 MeasureSpec 和子 View 的 LayoutParams")
        sb.appendLine("    // 计算子 View 的 MeasureSpec")
        sb.appendLine("    final int childWidthMeasureSpec = getChildMeasureSpec(")
        sb.appendLine("            parentWidthMeasureSpec, mPaddingLeft + mPaddingRight, lp.width);")
        sb.appendLine("    final int childHeightMeasureSpec = getChildMeasureSpec(")
        sb.appendLine("            parentHeightMeasureSpec, mPaddingTop + mPaddingBottom, lp.height);")
        sb.appendLine("    ")
        sb.appendLine("    // 测量子 View")
        sb.appendLine("    child.measure(childWidthMeasureSpec, childHeightMeasureSpec);")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【测量流程图】")
        sb.appendLine("```\n")
        sb.appendLine("performMeasure()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("DecorView.measure()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("DecorView.onMeasure()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("遍历子 View → measureChild()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("child.measure()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("child.onMeasure()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("setMeasuredDimension()")
        sb.appendLine("```")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * 布局流程详解
     */
    private fun showLayoutProcess() {
        sb.clear()
        sb.appendLine("=== 布局流程 (Layout) ===\n")
        
        sb.appendLine("【performLayout】")
        sb.appendLine("```java")
        sb.appendLine("private void performLayout(WindowManager.LayoutParams lp,")
        sb.appendLine("        int desiredWindowWidth, int desiredWindowHeight) {")
        sb.appendLine("    mInLayout = true;")
        sb.appendLine("    ")
        sb.appendLine("    final View host = mView;")
        sb.appendLine("    ")
        sb.appendLine("    try {")
        sb.appendLine("        // 调用 View 的 layout 方法")
        sb.appendLine("        host.layout(0, 0, host.getMeasuredWidth(), host.getMeasuredHeight());")
        sb.appendLine("        ")
        sb.appendLine("        mInLayout = false;")
        sb.appendLine("        ")
        sb.appendLine("        // 处理布局过程中产生的 layout 请求")
        sb.appendLine("        int numViewsRequestingLayout = host.getAndClearLayoutRequests();")
        sb.appendLine("        if (numViewsRequestingLayout > 0) {")
        sb.appendLine("            // 需要重新测量和布局")
        sb.appendLine("            // ...")
        sb.appendLine("        }")
        sb.appendLine("    } finally {")
        sb.appendLine("        Trace.traceEnd(Trace.TRACE_TAG_VIEW);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【View.layout】")
        sb.appendLine("```java")
        sb.appendLine("public void layout(int l, int t, int r, int b) {")
        sb.appendLine("    // 检查尺寸是否变化")
        sb.appendLine("    boolean changed = isLayoutModeOptical(mParent) ?")
        sb.appendLine("            setOpticalFrame(l, t, r, b) : setFrame(l, t, r, b);")
        sb.appendLine("    ")
        sb.appendLine("    if (changed || (mPrivateFlags & PFLAG_LAYOUT_REQUIRED) == PFLAG_LAYOUT_REQUIRED) {")
        sb.appendLine("        // 调用 onLayout")
        sb.appendLine("        onLayout(changed, l, t, r, b);")
        sb.appendLine("        ")
        sb.appendLine("        // 清除布局请求标志")
        sb.appendLine("        mPrivateFlags &= ~PFLAG_LAYOUT_REQUIRED;")
        sb.appendLine("        ")
        sb.appendLine("        // 派发布局变化事件")
        sb.appendLine("        ListenerInfo li = mListenerInfo;")
        sb.appendLine("        if (li != null && li.mOnLayoutChangeListeners != null) {")
        sb.appendLine("            for (OnLayoutChangeListener listener : li.mOnLayoutChangeListeners) {")
        sb.appendLine("                listener.onLayoutChange(this, l, t, r, b, oldL, oldT, oldR, oldB);")
        sb.appendLine("            }")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    mPrivateFlags &= ~PFLAG_FORCE_LAYOUT;")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【setFrame - 保存位置信息】")
        sb.appendLine("```java")
        sb.appendLine("protected boolean setFrame(int left, int top, int right, int bottom) {")
        sb.appendLine("    boolean changed = false;")
        sb.appendLine("    ")
        sb.appendLine("    if (mLeft != left || mRight != right")
        sb.appendLine("            || mTop != top || mBottom != bottom) {")
        sb.appendLine("        changed = true;")
        sb.appendLine("        ")
        sb.appendLine("        // 保存位置")
        sb.appendLine("        mLeft = left;")
        sb.appendLine("        mTop = top;")
        sb.appendLine("        mRight = right;")
        sb.appendLine("        mBottom = bottom;")
        sb.appendLine("        ")
        sb.appendLine("        // 计算尺寸")
        sb.appendLine("        mWidth = right - left;")
        sb.appendLine("        mHeight = bottom - top;")
        sb.appendLine("        ")
        sb.appendLine("        // 标记需要重绘")
        sb.appendLine("        mPrivateFlags |= PFLAG_DRAWN;")
        sb.appendLine("    }")
        sb.appendLine("    return changed;")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【ViewGroup.onLayout】")
        sb.appendLine("```java")
        sb.appendLine("// ViewGroup.onLayout 是抽象方法，子类必须实现")
        sb.appendLine("protected abstract void onLayout(boolean changed,")
        sb.appendLine("        int l, int t, int r, int b);")
        sb.appendLine("")
        sb.appendLine("// 例如 LinearLayout 的实现")
        sb.appendLine("protected void onLayout(boolean changed, int l, int t, int r, int b) {")
        sb.appendLine("    if (mOrientation == VERTICAL) {")
        sb.appendLine("        layoutVertical(l, t, r, b);")
        sb.appendLine("    } else {")
        sb.appendLine("        layoutHorizontal(l, t, r, b);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("void layoutVertical(int left, int top, int right, int bottom) {")
        sb.appendLine("    int childTop = top + mPaddingTop;")
        sb.appendLine("    int childLeft = left + mPaddingLeft;")
        sb.appendLine("    ")
        sb.appendLine("    final int count = getChildCount();")
        sb.appendLine("    for (int i = 0; i < count; i++) {")
        sb.appendLine("        final View child = getChildAt(i);")
        sb.appendLine("        if (child.getVisibility() != View.GONE) {")
        sb.appendLine("            // 布局子 View")
        sb.appendLine("            child.layout(childLeft, childTop,")
        sb.appendLine("                    childLeft + child.getMeasuredWidth(),")
        sb.appendLine("                    childTop + child.getMeasuredHeight());")
        sb.appendLine("            ")
        sb.appendLine("            childTop += child.getMeasuredHeight();")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【布局流程图】")
        sb.appendLine("```\n")
        sb.appendLine("performLayout()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("DecorView.layout(0, 0, width, height)")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("setFrame() → 保存 mLeft, mTop, mRight, mBottom")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("DecorView.onLayout()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("遍历子 View → child.layout()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("child.setFrame() + child.onLayout()")
        sb.appendLine("```\n")
        
        sb.appendLine("【重要区别】")
        sb.appendLine("measure() → 测量尺寸 → getMeasuredWidth/Height()")
        sb.appendLine("layout()  → 确定位置 → getWidth/Height() = mRight - mLeft")
        sb.appendLine("draw()    → 绘制内容 → 将内容绘制到 Canvas")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * 绘制流程详解
     */
    private fun showDrawProcess() {
        sb.clear()
        sb.appendLine("=== 绘制流程 (Draw) ===\n")
        
        sb.appendLine("【performDraw】")
        sb.appendLine("```java")
        sb.appendLine("private void performDraw() {")
        sb.appendLine("    if (mAttachInfo.mTreeObserver.hasOnPreDrawListeners()) {")
        sb.appendLine("        mAttachInfo.mTreeObserver.dispatchOnPreDraw();")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    try {")
        sb.appendLine("        draw(fullRedrawNeeded);")
        sb.appendLine("    } finally {")
        sb.appendLine("        mIsDrawing = false;")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【draw 方法】")
        sb.appendLine("```java")
        sb.appendLine("private boolean draw(boolean fullRedrawNeeded) {")
        sb.appendLine("    final Surface surface = mSurface;")
        sb.appendLine("    ")
        sb.appendLine("    // 检查 Surface 是否有效")
        sb.appendLine("    if (!surface.isValid()) {")
        sb.appendLine("        return false;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 如果使用硬件加速")
        sb.appendLine("    if (mHardwareAccelerated && mThreadedRenderer != null) {")
        sb.appendLine("        mThreadedRenderer.draw(mView, mAttachInfo, this);")
        sb.appendLine("    } else {")
        sb.appendLine("        // 软件绘制")
        sb.appendLine("        if (!drawSoftware(surface, mAttachInfo, xOffset, yOffset,")
        sb.appendLine("                dirtyNeeded, new Rect())) {")
        sb.appendLine("            return false;")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("    return true;")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【drawSoftware - 软件绘制】")
        sb.appendLine("```java")
        sb.appendLine("private boolean drawSoftware(Surface surface, AttachInfo attachInfo,")
        sb.appendLine("        int xoff, int yoff, boolean scalingRequired, Rect dirty) {")
        sb.appendLine("    final Canvas canvas;")
        sb.appendLine("    ")
        sb.appendLine("    try {")
        sb.appendLine("        // 1. 锁定 Canvas")
        sb.appendLine("        canvas = mSurface.lockCanvas(dirty);")
        sb.appendLine("        ")
        sb.appendLine("        // 2. 如果需要，设置缩放")
        sb.appendLine("        if (scalingRequired) {")
        sb.appendLine("            canvas.scale(...);")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        // 3. 设置密度")
        sb.appendLine("        canvas.setDensity(mDensity);")
        sb.appendLine("        ")
        sb.appendLine("        try {")
        sb.appendLine("            // 4. 调用 View.draw")
        sb.appendLine("            mView.draw(canvas);")
        sb.appendLine("        } finally {")
        sb.appendLine("            // 5. 解锁并提交")
        sb.appendLine("            surface.unlockCanvasAndPost(canvas);")
        sb.appendLine("        }")
        sb.appendLine("    } catch (Exception e) {")
        sb.appendLine("        return false;")
        sb.appendLine("    }")
        sb.appendLine("    return true;")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【View.draw - 绘制的 6 个步骤】")
        sb.appendLine("```java")
        sb.appendLine("public void draw(Canvas canvas) {")
        sb.appendLine("    final int privateFlags = mPrivateFlags;")
        sb.appendLine("    final boolean dirtyOpaque = (privateFlags & PFLAG_DIRTY_MASK) == PFLAG_DIRTY_OPAQUE;")
        sb.appendLine("    ")
        sb.appendLine("    /*")
        sb.appendLine("     * Draw traversal performs several drawing steps which must be executed")
        sb.appendLine("     * in the appropriate order:")
        sb.appendLine("     *")
        sb.appendLine("     *      1. Draw the background")
        sb.appendLine("     *      2. If necessary, save the canvas' layers to prepare for fading")
        sb.appendLine("     *      3. Draw view's content")
        sb.appendLine("     *      4. Draw children")
        sb.appendLine("     *      5. If necessary, draw the fading edges and restore layers")
        sb.appendLine("     *      6. Draw decorations (scrollbars for instance)")
        sb.appendLine("     */")
        sb.appendLine("    ")
        sb.appendLine("    // Step 1: 绘制背景")
        sb.appendLine("    if (!dirtyOpaque) {")
        sb.appendLine("        drawBackground(canvas);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // Step 2: 保存 Canvas 图层（用于淡入淡出效果）")
        sb.appendLine("    int saveCount = 0;")
        sb.appendLine("    if (!dirtyOpaque && ... fadingEdgeRequired) {")
        sb.appendLine("        saveCount = canvas.save();")
        sb.appendLine("        // ...")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // Step 3: 绘制内容")
        sb.appendLine("    if (!dirtyOpaque) {")
        sb.appendLine("        onDraw(canvas);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // Step 4: 绘制子 View")
        sb.appendLine("    dispatchDraw(canvas);")
        sb.appendLine("    ")
        sb.appendLine("    // Step 5: 绘制淡入淡出效果")
        sb.appendLine("    if (fadingEdgeRequired) {")
        sb.appendLine("        // ...")
        sb.appendLine("        canvas.restoreToCount(saveCount);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // Step 6: 绘制装饰（滚动条、前景等）")
        sb.appendLine("    onDrawForeground(canvas);")
        sb.appendLine("    ")
        sb.appendLine("    // Step 7: 绘制默认焦点高亮")
        sb.appendLine("    drawDefaultFocusHighlight(canvas);")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【绘制步骤详解】")
        sb.appendLine("```\n")
        sb.appendLine("步骤 1: drawBackground(canvas)")
        sb.appendLine("  - 绘制背景 Drawable")
        sb.appendLine("  - 受 padding 影响")
        sb.appendLine("")
        sb.appendLine("步骤 2: 保存 Canvas 图层")
        sb.appendLine("  - 用于实现淡入淡出效果")
        sb.appendLine("  - 大多数情况下不需要")
        sb.appendLine("")
        sb.appendLine("步骤 3: onDraw(canvas)")
        sb.appendLine("  - 绘制 View 的内容")
        sb.appendLine("  - 自定义 View 必须重写")
        sb.appendLine("")
        sb.appendLine("步骤 4: dispatchDraw(canvas)")
        sb.appendLine("  - ViewGroup 实现，绘制子 View")
        sb.appendLine("  - 遍历调用 child.draw()")
        sb.appendLine("")
        sb.appendLine("步骤 5: 恢复 Canvas")
        sb.appendLine("  - 与步骤 2 对应")
        sb.appendLine("")
        sb.appendLine("步骤 6: onDrawForeground(canvas)")
        sb.appendLine("  - 绘制滚动条")
        sb.appendLine("  - 绘制前景 Drawable")
        sb.appendLine("```\n")
        
        sb.appendLine("【dispatchDraw - ViewGroup】")
        sb.appendLine("```java")
        sb.appendLine("protected void dispatchDraw(Canvas canvas) {")
        sb.appendLine("    final int childrenCount = mChildrenCount;")
        sb.appendLine("    final View[] children = mChildren;")
        sb.appendLine("    ")
        sb.appendLine("    for (int i = 0; i < childrenCount; i++) {")
        sb.appendLine("        final View child = children[i];")
        sb.appendLine("        if ((child.mViewFlags & VISIBILITY_MASK) == VISIBLE") 
        sb.appendLine("                || child.getAnimation() != null) {")
        sb.appendLine("            // 绘制子 View")
        sb.appendLine("            drawChild(canvas, child, drawingTime);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【绘制流程图】")
        sb.appendLine("```\n")
        sb.appendLine("performDraw()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("draw() → drawSoftware() 或 mThreadedRenderer.draw()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("surface.lockCanvas()  ← 获取 Canvas")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("mView.draw(canvas)")
        sb.appendLine("       │")
        sb.appendLine("       ├─→ drawBackground()    背景绘制")
        sb.appendLine("       │")
        sb.appendLine("       ├─→ onDraw()            内容绘制")
        sb.appendLine("       │")
        sb.appendLine("       ├─→ dispatchDraw()      子 View 绘制")
        sb.appendLine("       │         │")
        sb.appendLine("       │         └─→ child.draw()")
        sb.appendLine("       │")
        sb.appendLine("       └─→ onDrawForeground()  装饰绘制")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("surface.unlockCanvasAndPost()  ← 提交绘制")
        sb.appendLine("```")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * MeasureSpec 详解
     */
    private fun showMeasureSpec() {
        sb.clear()
        sb.appendLine("=== MeasureSpec 详解 ===\n")
        
        sb.appendLine("【MeasureSpec 概念】")
        sb.appendLine("MeasureSpec 是一个 32 位的 int 值，")
        sb.appendLine("用于描述父容器对子 View 的尺寸约束。\n")
        
        sb.appendLine("【结构】")
        sb.appendLine("```\n")
        sb.appendLine("┌────────────────────────────────────────────────┐\n")
        sb.appendLine("│  高 2 位：SpecMode  │  低 30 位：SpecSize     │\n")
        sb.appendLine("└────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")
        
        sb.appendLine("【三种模式】")
        sb.appendLine("```java")
        sb.appendLine("// UNSPECIFIED: 父容器对子 View 没有限制")
        sb.appendLine("// 子 View 可以是任意大小")
        sb.appendLine("public static final int UNSPECIFIED = 0 << MODE_SHIFT;  // 0")
        sb.appendLine("")
        sb.appendLine("// EXACTLY: 父容器已确定子 View 的精确大小")
        sb.appendLine("// 子 View 最终大小就是这个值")
        sb.appendLine("public static final int EXACTLY = 1 << MODE_SHIFT;      // 1 << 30")
        sb.appendLine("")
        sb.appendLine("// AT_MOST: 父容器指定一个最大值")
        sb.appendLine("// 子 View 不能超过这个大小")
        sb.appendLine("public static final int AT_MOST = 2 << MODE_SHIFT;      // 2 << 30")
        sb.appendLine("```\n")
        
        sb.appendLine("【模式对应的 LayoutParams】")
        sb.appendLine("```\n")
        sb.appendLine("┌─────────────────┬───────────────────────────────────────┐\n")
        sb.appendLine("│ LayoutParams    │ 对应的 MeasureSpec                    │\n")
        sb.appendLine("├─────────────────┼───────────────────────────────────────┤\n")
        sb.appendLine("│ match_parent    │ EXACTLY (父容器大小)                  │\n")
        sb.appendLine("│ 具体数值(100dp) │ EXACTLY (具体数值)                    │\n")
        sb.appendLine("│ wrap_content    │ AT_MOST (父容器大小)                  │\n")
        sb.appendLine("└─────────────────┴───────────────────────────────────────┘\n")
        sb.appendLine("```\n")
        
        sb.appendLine("【getChildMeasureSpec】")
        sb.appendLine("```java")
        sb.appendLine("public static int getChildMeasureSpec(int spec, int padding,")
        sb.appendLine("        int childDimension) {")
        sb.appendLine("    int specMode = MeasureSpec.getMode(spec);")
        sb.appendLine("    int specSize = MeasureSpec.getSize(spec);")
        sb.appendLine("    ")
        sb.appendLine("    int size = Math.max(0, specSize - padding);")
        sb.appendLine("    int resultSize = 0;")
        sb.appendLine("    int resultMode = 0;")
        sb.appendLine("    ")
        sb.appendLine("    switch (specMode) {")
        sb.appendLine("        case EXACTLY:")
        sb.appendLine("            if (childDimension >= 0) {")
        sb.appendLine("                resultSize = childDimension;")
        sb.appendLine("                resultMode = MeasureSpec.EXACTLY;")
        sb.appendLine("            } else if (childDimension == LayoutParams.MATCH_PARENT) {")
        sb.appendLine("                resultSize = size;")
        sb.appendLine("                resultMode = MeasureSpec.EXACTLY;")
        sb.appendLine("            } else if (childDimension == LayoutParams.WRAP_CONTENT) {")
        sb.appendLine("                resultSize = size;")
        sb.appendLine("                resultMode = MeasureSpec.AT_MOST;")
        sb.appendLine("            }")
        sb.appendLine("            break;")
        sb.appendLine("        case AT_MOST:")
        sb.appendLine("            if (childDimension >= 0) {")
        sb.appendLine("                resultSize = childDimension;")
        sb.appendLine("                resultMode = MeasureSpec.EXACTLY;")
        sb.appendLine("            } else if (childDimension == LayoutParams.MATCH_PARENT) {")
        sb.appendLine("                resultSize = size;")
        sb.appendLine("                resultMode = MeasureSpec.AT_MOST;")
        sb.appendLine("            } else if (childDimension == LayoutParams.WRAP_CONTENT) {")
        sb.appendLine("                resultSize = size;")
        sb.appendLine("                resultMode = MeasureSpec.AT_MOST;")
        sb.appendLine("            }")
        sb.appendLine("            break;")
        sb.appendLine("        case UNSPECIFIED:")
        sb.appendLine("            if (childDimension >= 0) {")
        sb.appendLine("                resultSize = childDimension;")
        sb.appendLine("                resultMode = MeasureSpec.EXACTLY;")
        sb.appendLine("            } else if (childDimension == LayoutParams.MATCH_PARENT) {")
        sb.appendLine("                resultSize = 0;")
        sb.appendLine("                resultMode = MeasureSpec.UNSPECIFIED;")
        sb.appendLine("            } else if (childDimension == LayoutParams.WRAP_CONTENT) {")
        sb.appendLine("                resultSize = 0;")
        sb.appendLine("                resultMode = MeasureSpec.UNSPECIFIED;")
        sb.appendLine("            }")
        sb.appendLine("            break;")
        sb.appendLine("    }")
        sb.appendLine("    return MeasureSpec.makeMeasureSpec(resultSize, resultMode);")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【规则表格】")
        sb.appendLine("```\n")
        sb.appendLine("父容器 SpecMode    子 View LayoutParams    子 View SpecMode    子 View Size")
        sb.appendLine("─────────────────────────────────────────────────────────────────────────────")
        sb.appendLine("EXACTLY            具体数值 (100dp)        EXACTLY             具体数值")
        sb.appendLine("EXACTLY            match_parent            EXACTLY             父容器大小")
        sb.appendLine("EXACTLY            wrap_content            AT_MOST             父容器大小")
        sb.appendLine("")
        sb.appendLine("AT_MOST            具体数值 (100dp)        EXACTLY             具体数值")
        sb.appendLine("AT_MOST            match_parent            AT_MOST             父容器大小")
        sb.appendLine("AT_MOST            wrap_content            AT_MOST             父容器大小")
        sb.appendLine("")
        sb.appendLine("UNSPECIFIED        具体数值 (100dp)        EXACTLY             具体数值")
        sb.appendLine("UNSPECIFIED        match_parent            UNSPECIFIED         0")
        sb.appendLine("UNSPECIFIED        wrap_content            UNSPECIFIED         0")
        sb.appendLine("```\n")
        
        sb.appendLine("【DecorView 的 MeasureSpec】")
        sb.appendLine("```java")
        sb.appendLine("// ViewRootImpl.getRootMeasureSpec")
        sb.appendLine("private static int getRootMeasureSpec(int windowSize, int rootDimension) {")
        sb.appendLine("    int measureSpec;")
        sb.appendLine("    switch (rootDimension) {")
        sb.appendLine("        case ViewGroup.LayoutParams.MATCH_PARENT:")
        sb.appendLine("            // 窗口大小固定，DecorView 大小 = 窗口大小")
        sb.appendLine("            measureSpec = MeasureSpec.makeMeasureSpec(windowSize, EXACTLY);")
        sb.appendLine("            break;")
        sb.appendLine("        case ViewGroup.LayoutParams.WRAP_CONTENT:")
        sb.appendLine("            // 窗口大小可变，DecorView 最大 = 窗口大小")
        sb.appendLine("            measureSpec = MeasureSpec.makeMeasureSpec(windowSize, AT_MOST);")
        sb.appendLine("            break;")
        sb.appendLine("        default:")
        sb.appendLine("            // 固定大小")
        sb.appendLine("            measureSpec = MeasureSpec.makeMeasureSpec(rootDimension, EXACTLY);")
        sb.appendLine("            break;")
        sb.appendLine("    }")
        sb.appendLine("    return measureSpec;")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【关键点】")
        sb.appendLine("1. MeasureSpec 由父容器传递给子 View")
        sb.appendLine("2. 子 View 的 MeasureSpec 取决于：")
        sb.appendLine("   - 父容器的 MeasureSpec")
        sb.appendLine("   - 子 View 的 LayoutParams")
        sb.appendLine("3. DecorView 的 MeasureSpec 由窗口大小决定")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * forceLayout 流程
     */
    private fun showForceLayoutProcess() {
        sb.clear()
        sb.appendLine("=== forceLayout 流程 ===\n")
        
        sb.appendLine("【View.forceLayout】")
        sb.appendLine("```java")
        sb.appendLine("public void forceLayout() {")
        sb.appendLine("    if (mMeasureCache != null) mMeasureCache.clear();")
        sb.appendLine("    ")
        sb.appendLine("    mPrivateFlags |= PFLAG_FORCE_LAYOUT;")
        sb.appendLine("    mPrivateFlags |= PFLAG_INVALIDATED;")
        sb.appendLine("    ")
        sb.appendLine("    // 向上传递")
        sb.appendLine("    if (mParent != null && !mParent.isLayoutRequested()) {")
        sb.appendLine("        mParent.requestLayout();")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【作用】")
        sb.appendLine("强制重新测量，即使 MeasureSpec 没有变化。\n")
        
        sb.appendLine("【使用场景】")
        sb.appendLine("1. View 的内容发生变化，需要重新测量")
        sb.appendLine("2. 强制触发完整的测量流程\n")
        
        sb.appendLine("【与 requestLayout 的区别】")
        sb.appendLine("```\n")
        sb.appendLine("forceLayout：")
        sb.appendLine("  - 只设置 PFLAG_FORCE_LAYOUT 标志")
        sb.appendLine("  - 不一定触发 scheduleTraversals")
        sb.appendLine("")
        sb.appendLine("requestLayout：")
        sb.appendLine("  - 设置 PFLAG_FORCE_LAYOUT 标志")
        sb.appendLine("  - 向上传递到 ViewRootImpl")
        sb.appendLine("  - 触发 scheduleTraversals")
        sb.appendLine("```\n")
        
        sb.appendLine("【measure 方法中的判断】")
        sb.appendLine("```java")
        sb.appendLine("public final void measure(int widthMeasureSpec, int heightMeasureSpec) {")
        sb.appendLine("    // 检查 forceLayout 标志")
        sb.appendLine("    boolean forceLayout = (mPrivateFlags & PFLAG_FORCE_LAYOUT) == PFLAG_FORCE_LAYOUT;")
        sb.appendLine("    ")
        sb.appendLine("    if (forceLayout || needsLayout) {")
        sb.appendLine("        // 执行测量")
        sb.appendLine("        onMeasure(widthMeasureSpec, heightMeasureSpec);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * invalidate 流程
     */
    private fun showInvalidateProcess() {
        sb.clear()
        sb.appendLine("=== invalidate 流程 ===\n")
        
        sb.appendLine("【View.invalidate】")
        sb.appendLine("```java")
        sb.appendLine("public void invalidate() {")
        sb.appendLine("    invalidate(true);")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("public void invalidate(boolean invalidateCache) {")
        sb.appendLine("    invalidateInternal(0, 0, mRight - mLeft, mBottom - mTop,")
        sb.appendLine("            invalidateCache, true);")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("void invalidateInternal(int l, int t, int r, int b,")
        sb.appendLine("        boolean invalidateCache, boolean fullInvalidate) {")
        sb.appendLine("    // 检查条件")
        sb.appendLine("    if (skipInvalidate()) {")
        sb.appendLine("        return;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 设置脏区域标志")
        sb.appendLine("    if ((mPrivateFlags & PFLAG_DRAWN) != 0 ||") 
        sb.appendLine("            (mPrivateFlags & PFLAG_DRAWING_CACHE_VALID) != 0) {")
        sb.appendLine("        if (fullInvalidate) {")
        sb.appendLine("            mPrivateFlags &= ~PFLAG_DRAWN;")
        sb.appendLine("            mPrivateFlags &= ~PFLAG_DRAWING_CACHE_VALID;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        // 向上传递")
        sb.appendLine("        final AttachInfo ai = mAttachInfo;")
        sb.appendLine("        final ViewParent p = mParent;")
        sb.appendLine("        if (p != null && ai != null && l < r && t < b) {")
        sb.appendLine("            final Rect damage = ai.mTmpInvalRect;")
        sb.appendLine("            damage.set(l, t, r, b);")
        sb.appendLine("            p.invalidateChild(this, damage);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【ViewGroup.invalidateChild】")
        sb.appendLine("```java")
        sb.appendLine("public final void invalidateChild(View child, final Rect dirty) {")
        sb.appendLine("    ViewParent parent = this;")
        sb.appendLine("    final AttachInfo attachInfo = mAttachInfo;")
        sb.appendLine("    ")
        sb.appendLine("    // 向上遍历")
        sb.appendLine("    do {")
        sb.appendLine("        View view = null;")
        sb.appendLine("        if (parent instanceof View) {")
        sb.appendLine("            view = (View) parent;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        if (drawAnimation) {")
        sb.appendLine("            if (view != null) {")
        sb.appendLine("                view.mRecreateDisplayList = true;")
        sb.appendLine("            }")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        // 调用父容器的 invalidateChildInParent")
        sb.appendLine("        parent = parent.invalidateChildInParent(location, dirty);")
        sb.appendLine("        ")
        sb.appendLine("    } while (parent != null);")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【ViewRootImpl.invalidateChildInParent】")
        sb.appendLine("```java")
        sb.appendLine("public ViewParent invalidateChildInParent(int[] location, Rect dirty) {")
        sb.appendLine("    checkThread();")
        sb.appendLine("    ")
        sb.appendLine("    if (dirty == null) {")
        sb.appendLine("        invalidate();")
        sb.appendLine("        return null;")
        sb.appendLine("    } else if (dirty.isEmpty()) {")
        sb.appendLine("        return null;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 检查是否需要完全重绘")
        sb.appendLine("    if (mCurScrollY != 0 || mTranslator != null) {")
        sb.appendLine("        dirty.offset(0, -mCurScrollY);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 调度绘制")
        sb.appendLine("    invalidateRectOnScreen(dirty);")
        sb.appendLine("    return null;")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("private void invalidateRectOnScreen(Rect dirty) {")
        sb.appendLine("    if (!mWillDrawSoon && (intersected || mIsAnimating)) {")
        sb.appendLine("        scheduleTraversals();")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【invalidate vs requestLayout】")
        sb.appendLine("```\n")
        sb.appendLine("invalidate：")
        sb.appendLine("  - 只触发绘制")
        sb.appendLine("  - 不触发测量和布局")
        sb.appendLine("  - 适用于内容变化但尺寸不变的情况")
        sb.appendLine("")
        sb.appendLine("requestLayout：")
        sb.appendLine("  - 触发测量 + 布局 + 绘制")
        sb.appendLine("  - 适用于尺寸变化的情况")
        sb.appendLine("```\n")
        
        sb.appendLine("【postInvalidate】")
        sb.appendLine("```java")
        sb.appendLine("// 在非 UI 线程调用")
        sb.appendLine("public void postInvalidate() {")
        sb.appendLine("    postInvalidateDelayed(0);")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("public void postInvalidateDelayed(long delayMilliseconds) {")
        sb.appendLine("    final AttachInfo attachInfo = mAttachInfo;")
        sb.appendLine("    if (attachInfo != null) {")
        sb.appendLine("        attachInfo.mViewRootImpl.dispatchInvalidateDelayed(this, delayMilliseconds);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("// 通过 Handler 发送到主线程")
        sb.appendLine("public void dispatchInvalidateDelayed(View view, long delayMilliseconds) {")
        sb.appendLine("    Message msg = mHandler.obtainMessage(MSG_INVALIDATE, view);")
        sb.appendLine("    mHandler.sendMessageDelayed(msg, delayMilliseconds);")
        sb.appendLine("}")
        sb.appendLine("```")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * requestLayout 流程
     */
    private fun showRequestLayoutProcess() {
        sb.clear()
        sb.appendLine("=== requestLayout 流程 ===\n")
        
        sb.appendLine("【View.requestLayout】")
        sb.appendLine("```java")
        sb.appendLine("public void requestLayout() {")
        sb.appendLine("    if (mMeasureCache != null) mMeasureCache.clear();")
        sb.appendLine("    ")
        sb.appendLine("    // 检查是否在布局中")
        sb.appendLine("    if (mAttachInfo != null && mAttachInfo.mViewRequestingLayout == null) {")
        sb.appendLine("        final View view = mAttachInfo.mViewRequestingLayout;")
        sb.appendLine("        ViewRootImpl viewRoot = mViewRootImpl;")
        sb.appendLine("        if (viewRoot != null && viewRoot.isInLayout()) {")
        sb.appendLine("            if (!viewRoot.requestLayoutDuringLayout(this)) {")
        sb.appendLine("                return;")
        sb.appendLine("            }")
        sb.appendLine("        }")
        sb.appendLine("        mAttachInfo.mViewRequestingLayout = this;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 设置标志")
        sb.appendLine("    mPrivateFlags |= PFLAG_FORCE_LAYOUT;")
        sb.appendLine("    mPrivateFlags |= PFLAG_INVALIDATED;")
        sb.appendLine("    ")
        sb.appendLine("    // 向上传递")
        sb.appendLine("    if (mParent != null && !mParent.isLayoutRequested()) {")
        sb.appendLine("        mParent.requestLayout();")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    if (mAttachInfo != null && mAttachInfo.mViewRequestingLayout == this) {")
        sb.appendLine("        mAttachInfo.mViewRequestingLayout = null;")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【ViewRootImpl.requestLayout】")
        sb.appendLine("```java")
        sb.appendLine("public void requestLayout() {")
        sb.appendLine("    if (!mHandlingLayoutInLayoutRequest) {")
        sb.appendLine("        // 检查线程")
        sb.appendLine("        checkThread();")
        sb.appendLine("        mLayoutRequested = true;")
        sb.appendLine("        // 调度遍历")
        sb.appendLine("        scheduleTraversals();")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【scheduleTraversals】")
        sb.appendLine("```java")
        sb.appendLine("void scheduleTraversals() {")
        sb.appendLine("    if (!mTraversalScheduled) {")
        sb.appendLine("        mTraversalScheduled = true;")
        sb.appendLine("        ")
        sb.appendLine("        // 1. 发送同步屏障")
        sb.appendLine("        mTraversalBarrier = mHandler.getLooper().getQueue().postSyncBarrier();")
        sb.appendLine("        ")
        sb.appendLine("        // 2. 通过 Choreographer 安排遍历")
        sb.appendLine("        mChoreographer.postCallback(")
        sb.appendLine("                Choreographer.CALLBACK_TRAVERSAL,")
        sb.appendLine("                mTraversalRunnable, null);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【同步屏障的作用】")
        sb.appendLine("```java")
        sb.appendLine("// 同步屏障的作用是：")
        sb.appendLine("// 阻止同步消息执行，优先执行异步消息")
        sb.appendLine("")
        sb.appendLine("// MessageQueue.next()")
        sb.appendLine("Message next() {")
        sb.appendLine("    // 如果有同步屏障，优先查找异步消息")
        sb.appendLine("    if (target == null) {  // target == null 表示同步屏障")
        sb.appendLine("        // 只返回异步消息")
        sb.appendLine("        do {")
        sb.appendLine("            if (!msg.isAsynchronous()) {")
        sb.appendLine("                continue;  // 跳过同步消息")
        sb.appendLine("            }")
        sb.appendLine("            return msg;  // 返回异步消息")
        sb.appendLine("        } while (true);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【完整流程图】")
        sb.appendLine("```\n")
        sb.appendLine("View.requestLayout()")
        sb.appendLine("       │")
        sb.appendLine("       ↓ (向上传递)")
        sb.appendLine("ViewGroup.requestLayout()")
        sb.appendLine("       │")
        sb.appendLine("       ↓ (向上传递)")
        sb.appendLine("ViewRootImpl.requestLayout()")
        sb.appendLine("       │")
        sb.appendLine("       ├─→ checkThread()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("scheduleTraversals()")
        sb.appendLine("       │")
        sb.appendLine("       ├─→ postSyncBarrier()  同步屏障")
        sb.appendLine("       │")
        sb.appendLine("       └─→ mChoreographer.postCallback()")
        sb.appendLine("                  │")
        sb.appendLine("                  ↓ (等待 VSync)")
        sb.appendLine("           doTraversal()")
        sb.appendLine("                  │")
        sb.appendLine("                  ↓")
        sb.appendLine("           performTraversals()")
       sb.appendLine("                  │")
        sb.appendLine("        ┌─────────┼─────────┐")
        sb.appendLine("        ↓         ↓         ↓")
        sb.appendLine("    measure()  layout()  draw()")
        sb.appendLine("```")
        
        binding.tvContent.text = sb.toString()
    }

    override fun onSupportNavigateUp(): Boolean {
        onBackPressedDispatcher.onBackPressed()
        return true
    }
}
