package com.peter.window.demo.activitythread.advanced

import android.os.Bundle
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import com.peter.window.demo.R

/**
 * ActivityThread 进阶篇 - Activity 启动流程
 *
 * === 完整启动流程 ===
 *
 * Activity 启动涉及多个进程：
 * 1. Launcher 进程（桌面）
 * 2. System Server 进程（AMS 所在进程）
 * 3. Zygote 进程（孵化进程）
 * 4. App 进程（目标应用进程）
 *
 * 【整体架构】
 * ```
 * Launcher 进程          System Server 进程           App 进程
 *     │                       │                          │
 *     │ startActivity()       │                          │
 *     │──────────────────────>│                          │
 *     │                       │                          │
 *     │                       │ startProcess()           │
 *     │                       │──────────────────────>Zygote
 *     │                       │                          │
 *     │                       │      fork app process    │
 *     │                       │<─────────────────────────│
 *     │                       │                          │
 *     │                       │ attachApplication()      │
 *     │                       │─────────────────────────>│
 *     │                       │                          │
 *     │                       │      scheduleLaunchActivity
 *     │                       │─────────────────────────>│
 *     │                       │                          │
 *     │                       │        handleLaunchActivity
 *     │                       │                          │
 *     │                       │        performLaunchActivity
 *     │                       │                          │
 *     │                       │        Activity.onCreate()
 *     │                       │                          │
 * ```
 */
class ActivityLaunchFlowActivity : AppCompatActivity() {

    private val sb = StringBuilder()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_activity_launch_flow)
        
        showProcessOverview()
        showLauncherToAMS()
        showAMSToApp()
        showAppInternal()
        showCompleteFlow()
        
        findViewById<TextView>(R.id.tvContent).text = sb.toString()
    }

    /**
     * 进程概览
     */
    private fun showProcessOverview() {
        sb.appendLine("═══════════════════════════════════════════════════")
        sb.appendLine("           Activity 启动流程概览")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【涉及的进程】\n")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                        Android 系统                          │\n")
        sb.appendLine("├─────────────────────────────────────────────────────────────┤\n")
        sb.appendLine("│  Launcher 进程          System Server 进程                  │\n")
        sb.appendLine("│  ┌───────────────┐      ┌───────────────────────────────┐   │\n")
        sb.appendLine("│  │ Launcher      │      │ ActivityManagerService (AMS)  │   │\n")
        sb.appendLine("│  │ (桌面应用)    │      │ PackageManagerService (PMS)   │   │\n")
        sb.appendLine("│  └───────────────┘      │ WindowManagerService (WMS)    │   │\n")
        sb.appendLine("│                         └───────────────────────────────┘   │\n")
        sb.appendLine("├─────────────────────────────────────────────────────────────┤\n")
        sb.appendLine("│  Zygote 进程              App 进程                          │\n")
        sb.appendLine("│  ┌───────────────┐      ┌───────────────────────────────┐   │\n")
        sb.appendLine("│  │ Zygote        │      │ ActivityThread                │   │\n")
        sb.appendLine("│  │ (进程孵化器)  │      │ ApplicationThread             │   │\n")
        sb.appendLine("│  └───────────────┘      │ Application                   │   │\n")
        sb.appendLine("│                         │ Activity                      │   │\n")
        sb.appendLine("│                         └───────────────────────────────┘   │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────┘\n")
        
        sb.appendLine("【启动流程时序】\n")
        sb.appendLine("1. Launcher 发起 startActivity 请求")
        sb.appendLine("2. AMS 解析 Intent，检查权限")
        sb.appendLine("3. AMS 判断目标进程是否启动")
        sb.appendLine("   - 已启动 → 直接通知目标进程创建 Activity")
        sb.appendLine("   - 未启动 → 通过 Zygote fork 新进程")
        sb.appendLine("4. 新进程执行 ActivityThread.main()")
        sb.appendLine("5. ActivityThread 绑定 Application")
        sb.appendLine("6. ActivityThread 创建并启动 Activity")
        sb.appendLine("7. Activity 生命周期回调执行\n")
    }

    /**
     * Launcher 到 AMS
     */
    private fun showLauncherToAMS() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("           第一阶段：Launcher → AMS")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【代码调用链】\n")
        sb.appendLine("```java")
        sb.appendLine("// 1. Launcher 点击图标")
        sb.appendLine("// Launcher.java")
        sb.appendLine("public void onClick(View v) {")
        sb.appendLine("    // 获取 Intent")
        sb.appendLine("    Intent intent = new Intent(Intent.ACTION_MAIN);")
        sb.appendLine("    intent.addCategory(Intent.CATEGORY_LAUNCHER);")
        sb.appendLine("    intent.setComponent(new ComponentName(packageName, className));")
        sb.appendLine("    ")
        sb.appendLine("    // 发起启动请求")
        sb.appendLine("    startActivitySafely(intent);")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("// 2. Activity.startActivity()")
        sb.appendLine("public void startActivity(Intent intent) {")
        sb.appendLine("    this.startActivity(intent, null);")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("// 3. Activity.startActivityForResult()")
        sb.appendLine("public void startActivityForResult(@RequiresPermission Intent intent, int requestCode) {")
        sb.appendLine("    options = prepareActivityResultOptions(options, intent, requestCode);")
        sb.appendLine("    // 调用 Instrumentation")
        sb.appendLine("    mInstrumentation.execStartActivity(this, mMainThread.getApplicationThread(),")
        sb.appendLine("            mToken, this, intent, requestCode, options);")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("// 4. Instrumentation.execStartActivity()")
        sb.appendLine("public ActivityResult execStartActivity(...) {")
        sb.appendLine("    // 获取 AMS 的代理对象")
        sb.appendLine("    IActivityTaskManager mgr = ActivityTaskManager.getService();")
        sb.appendLine("    ")
        sb.appendLine("    // 跨进程调用 AMS")
        sb.appendLine("    int result = mgr.startActivity(...);")
        sb.appendLine("    return null;")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("// 5. ActivityTaskManager.getService()")
        sb.appendLine("public static IActivityTaskManager getService() {")
        sb.appendLine("    // 通过 ServiceManager 获取 AMS 的 Binder 代理")
        sb.appendLine("    return IActivityTaskManagerSingleton.get();")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【时序图】\n")
        sb.appendLine("```\n")
        sb.appendLine("Launcher 进程                    System Server 进程")
        sb.appendLine("     │                                 │")
        sb.appendLine("     │ onClick()                       │")
        sb.appendLine("     │ startActivity()                 │")
        sb.appendLine("     │ startActivityForResult()        │")
        sb.appendLine("     │ Instrumentation.execStartActivity()")
        sb.appendLine("     │ ─────────────────────────────────>")
        sb.appendLine("     │        startActivity (Binder)   │")
        sb.appendLine("     │                                 │ AMS.startActivity()")
        sb.appendLine("     │                                 │")
        sb.appendLine("```\n")
    }

    /**
     * AMS 到 App
     */
    private fun showAMSToApp() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("           第二阶段：AMS → App 进程")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【场景一：目标进程已启动】\n")
        sb.appendLine("```java")
        sb.appendLine("// AMS 直接通过 ApplicationThread 通知 App")
        sb.appendLine("// ActivityManagerService.java")
        sb.appendLine("private boolean attachApplicationLocked(IApplicationThread thread,")
        sb.appendLine("        int pid, int callingUid, long startSeq) {")
        sb.appendLine("    ")
        sb.appendLine("    // 获取进程记录")
        sb.appendLine("    ProcessRecord app;")
        sb.appendLine("    ")
        sb.appendLine("    // 获取待启动的 Activity")
        sb.appendLine("    ActivityRecord activity = mPendingActivities.get(pid);")
        sb.appendLine("    ")
        sb.appendLine("    // 通过 ApplicationThread 通知 App 创建 Activity")
        sb.appendLine("    thread.scheduleLaunchActivity(...);")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【场景二：目标进程未启动】\n")
        sb.appendLine("```java")
        sb.appendLine("// 1. AMS 请求 Zygote fork 新进程")
        sb.appendLine("// ProcessList.java")
        sb.appendLine("private Process.ProcessStartResult startProcessLocked(...) {")
        sb.appendLine("    // 通过 socket 连接 Zygote")
        sb.appendLine("    return Process.start(...);")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("// 2. Zygote fork 进程")
        sb.appendLine("// ZygoteInit.java")
        sb.appendLine("public static void main(String[] argv) {")
        sb.appendLine("    // 预加载资源")
        sb.appendLine("    preload();")
        sb.appendLine("    ")
        sb.appendLine("    // 运行 select 循环，等待请求")
        sb.appendLine("    runSelectLoop();")
        sb.appendLine("    ")
        sb.appendLine("    // 收到 fork 请求后")
        sb.appendLine("    // 子进程执行 handleChildProc()")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("// 3. 新进程执行 ActivityThread.main()")
        sb.appendLine("// ZygoteConnection.java")
        sb.appendLine("private void handleChildProc(...) {")
        sb.appendLine("    // 调用 ActivityThread.main()")
        sb.appendLine("    RuntimeInit.applicationInit(...);")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【ApplicationThread - Binder 通信桥梁】\n")
        sb.appendLine("```java")
        sb.appendLine("// ActivityThread 的内部类")
        sb.appendLine("private class ApplicationThread extends IApplicationThread.Stub {")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public final void scheduleLaunchActivity(Intent intent, IBinder token,")
        sb.appendLine("            int ident, ActivityInfo info, Configuration curConfig,") 
        sb.appendLine("            Configuration overrideConfig, ...) {")
        sb.appendLine("        ")
        sb.appendLine("        // 将参数封装为 ActivityClientRecord")
        sb.appendLine("        ActivityClientRecord r = new ActivityClientRecord();")
        sb.appendLine("        r.token = token;")
        sb.appendLine("        r.ident = ident;")
        sb.appendLine("        r.intent = intent;")
        sb.appendLine("        r.activityInfo = info;")
        sb.appendLine("        r.state = state;")
        sb.appendLine("        r.persistentState = persistentState;")
        sb.appendLine("        ")
        sb.appendLine("        // 发送消息给 H (Handler)")
        sb.appendLine("        sendMessage(H.LAUNCH_ACTIVITY, r);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public final void scheduleResumeActivity(IBinder token, ...) {")
        sb.appendLine("        sendMessage(H.RESUME_ACTIVITY, token);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public final void schedulePauseActivity(IBinder token, ...) {")
        sb.appendLine("        sendMessage(H.PAUSE_ACTIVITY, token);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public final void scheduleStopActivity(IBinder token, ...) {")
        sb.appendLine("        sendMessage(H.STOP_ACTIVITY, token);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public final void scheduleDestroyActivity(IBinder token, ...) {")
        sb.appendLine("        sendMessage(H.DESTROY_ACTIVITY, token);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【时序图：进程启动】\n")
        sb.appendLine("```\n")
        sb.appendLine("System Server           Zygote              App 进程")
        sb.appendLine("     │                    │                     │")
        sb.appendLine("     │ startProcess()     │                     │")
        sb.appendLine("     │ ──────────────────>│                     │")
        sb.appendLine("     │                    │ fork()              │")
        sb.appendLine("     │                    │ ───────────────────>│")
        sb.appendLine("     │                    │                     │")
        sb.appendLine("     │                    │    ActivityThread.main()")
        sb.appendLine("     │                    │                     │")
        sb.appendLine("     │ attachApplication()│                     │")
        sb.appendLine("     │ ──────────────────────────────────────>│")
        sb.appendLine("     │                    │                     │")
        sb.appendLine("     │                    │    bindApplication()")
        sb.appendLine("     │                    │                     │")
        sb.appendLine("     │ scheduleLaunchActivity()                │")
        sb.appendLine("     │ ──────────────────────────────────────>│")
        sb.appendLine("     │                    │                     │")
        sb.appendLine("     │                    │    handleLaunchActivity()")
        sb.appendLine("```\n")
    }

    /**
     * App 内部流程
     */
    private fun showAppInternal() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("           第三阶段：App 进程内部")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【ActivityThread.main() - 进程入口】\n")
        sb.appendLine("```java")
        sb.appendLine("public static void main(String[] args) {")
        sb.appendLine("    // 1. 初始化主线程 Looper")
        sb.appendLine("    Looper.prepareMainLooper();")
        sb.appendLine("    ")
        sb.appendLine("    // 2. 创建 ActivityThread 实例")
        sb.appendLine("    ActivityThread thread = new ActivityThread();")
        sb.appendLine("    thread.attach(false, startSeq);")
        sb.appendLine("    ")
        sb.appendLine("    // 3. 获取 Handler")
        sb.appendLine("    if (sMainThreadHandler == null) {")
        sb.appendLine("        sMainThreadHandler = thread.getHandler();")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 4. 开始消息循环")
        sb.appendLine("    Looper.loop();")
        sb.appendLine("    ")
        sb.appendLine("    // 5. 循环结束抛出异常（正常情况不会执行）")
        sb.appendLine("    throw new RuntimeException(\"Main thread loop unexpectedly exited\");")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【attach() - 与 AMS 建立连接】\n")
        sb.appendLine("```java")
        sb.appendLine("private void attach(boolean system, long startSeq) {")
        sb.appendLine("    sCurrentActivityThread = this;")
        sb.appendLine("    mSystemThread = system;")
        sb.appendLine("    ")
        sb.appendLine("    if (!system) {")
        sb.appendLine("        // 获取 AMS 代理")
        sb.appendLine("        final IActivityManager mgr = ActivityManager.getService();")
        sb.appendLine("        ")
        sb.appendLine("        try {")
        sb.appendLine("            // 将 ApplicationThread 注册到 AMS")
        sb.appendLine("            // AMS 通过这个 Binder 调用 App")
        sb.appendLine("            mgr.attachApplication(mAppThread, startSeq);")
        sb.appendLine("        } catch (RemoteException ex) {")
        sb.appendLine("            throw ex.rethrowFromSystemServer();")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【handleLaunchActivity - 处理启动 Activity 消息】\n")
        sb.appendLine("```java")
        sb.appendLine("// 在 H (Handler) 中处理 LAUNCH_ACTIVITY 消息")
        sb.appendLine("public void handleMessage(Message msg) {")
        sb.appendLine("    switch (msg.what) {")
        sb.appendLine("        case LAUNCH_ACTIVITY: {")
        sb.appendLine("            ActivityClientRecord r = (ActivityClientRecord) msg.obj;")
        sb.appendLine("            r.packageInfo = getPackageInfoNoCheck(...);")
        sb.appendLine("            handleLaunchActivity(r, null, \"LAUNCH_ACTIVITY\");")
        sb.appendLine("            break;")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("private void handleLaunchActivity(ActivityClientRecord r,") 
        sb.appendLine("        Intent customIntent, String reason) {")
        sb.appendLine("    ")
        sb.appendLine("    // 1. 初始化 WindowManagerService 相关")
        sb.appendLine("    WindowManagerGlobal.initialize();")
        sb.appendLine("    ")
        sb.appendLine("    // 2. 创建 Activity")
        sb.appendLine("    Activity a = performLaunchActivity(r, customIntent);")
        sb.appendLine("    ")
        sb.appendLine("    if (a != null) {")
        sb.appendLine("        r.createdConfig = new Configuration(mConfiguration);")
        sb.appendLine("        reportSizeConfigurations(r);")
        sb.appendLine("        ")
        sb.appendLine("        // 3. 调用 Activity.onResume()")
        sb.appendLine("        handleResumeActivity(r.token, false, r.isForward,")
        sb.appendLine("                !r.activity.mFinished && !r.startsNotResumed,")
        sb.appendLine("                r.lastProcessedSeq, reason);")
        sb.appendLine("        ")
        sb.appendLine("        if (!r.activity.mFinished && r.startsNotResumed) {")
        sb.appendLine("            // 4. 如果需要，调用 Activity.onPause()")
        sb.appendLine("            performPauseActivityIfNeeded(r, reason);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【performLaunchActivity - 核心创建流程】\n")
        sb.appendLine("```java")
        sb.appendLine("private Activity performLaunchActivity(ActivityClientRecord r, Intent customIntent) {")
        sb.appendLine("    ")
        sb.appendLine("    // 1. 获取 ActivityInfo")
        sb.appendLine("    ActivityInfo aInfo = r.activityInfo;")
        sb.appendLine("    ComponentName component = new ComponentName(aInfo.applicationInfo.packageName,")
        sb.appendLine("            aInfo.name);")
        sb.appendLine("    ")
        sb.appendLine("    // 2. 创建/获取 Application")
        sb.appendLine("    Application app = r.packageInfo.makeApplication(false, mInstrumentation);")
        sb.appendLine("    ")
        sb.appendLine("    // 3. 创建 Activity 实例")
        sb.appendLine("    Activity activity = null;")
        sb.appendLine("    try {")
        sb.appendLine("        java.lang.ClassLoader cl = appContext.getClassLoader();")
        sb.appendLine("        activity = mInstrumentation.newActivity(cl, component.getClassName(), r.intent);")
        sb.appendLine("    } catch (Exception e) {")
        sb.appendLine("        // 处理异常")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    if (activity != null) {")
        sb.appendLine("        // 4. 创建 Activity 的 Context")
        sb.appendLine("        Context appContext = createBaseContextForActivity(r, activity);")
        sb.appendLine("        ")
        sb.appendLine("        // 5. 调用 Activity.attach()")
        sb.appendLine("        activity.attach(appContext, this, getInstrumentation(), r.token,")
        sb.appendLine("                r.ident, app, r.intent, r.activityInfo, title,")
        sb.appendLine("                r.parent, r.embeddedID, r.lastNonConfigurationInstances, config,")
        sb.appendLine("                r.referrer, r.voiceInteractor, window, r.configCallback,")
        sb.appendLine("                r.assistToken, r.shareableActivityToken);")
        sb.appendLine("        ")
        sb.appendLine("        // 6. 设置主题")
        sb.appendLine("        int theme = r.activityInfo.getThemeResource();")
        sb.appendLine("        if (theme != 0) {")
        sb.appendLine("            activity.setTheme(theme);")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        // 7. 调用 Activity.onCreate()")
        sb.appendLine("        if (r.isPersistable()) {")
        sb.appendLine("            mInstrumentation.callActivityOnCreate(activity, r.state, r.persistentState);")
        sb.appendLine("        } else {")
        sb.appendLine("            mInstrumentation.callActivityOnCreate(activity, r.state);")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        // 8. 保存 Activity 记录")
        sb.appendLine("        mActivities.put(r.token, r);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    return activity;")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【Activity.attach() - 初始化 Activity】\n")
        sb.appendLine("```java")
        sb.appendLine("final void attach(Context context, ActivityThread aThread,")
        sb.appendLine("        Instrumentation instr, IBinder token, int ident,")
        sb.appendLine("        Application application, Intent intent, ActivityInfo info,") 
        sb.appendLine("        CharSequence title, Activity parent, String id,") 
        sb.appendLine("        NonConfigurationInstances lastNonConfigurationInstances,") 
        sb.appendLine("        Configuration config, ...) {")
        sb.appendLine("    ")
        sb.appendLine("    attachBaseContext(context);")
        sb.appendLine("    ")
        sb.appendLine("    // 创建 PhoneWindow")
        sb.appendLine("    mWindow = new PhoneWindow(this, window, activityConfigCallback);")
        sb.appendLine("    mWindow.setWindowControllerCallback(this);")
        sb.appendLine("    mWindow.setCallback(this);")
        sb.appendLine("    mWindow.setOnWindowDismissedCallback(this);")
        sb.appendLine("    mWindow.getLayoutInflater().setPrivateFactory(this);")
        sb.appendLine("    ")
        sb.appendLine("    // 设置 WindowManager")
        sb.appendLine("    mWindow.setWindowManager(")
        sb.appendLine("            (WindowManager) context.getSystemService(Context.WINDOW_SERVICE),")
        sb.appendLine("            mToken, mComponent.flattenToString(),")
        sb.appendLine("            (info.flags & ActivityInfo.FLAG_HARDWARE_ACCELERATED) != 0);")
        sb.appendLine("    ")
        sb.appendLine("    mUiThread = Thread.currentThread();")
        sb.appendLine("    mMainThread = aThread;")
        sb.appendLine("    mInstrumentation = instr;")
        sb.appendLine("    mToken = token;")
        sb.appendLine("    mIdent = ident;")
        sb.appendLine("    mApplication = application;")
        sb.appendLine("    mIntent = intent;")
        sb.appendLine("    mActivityInfo = info;")
        sb.appendLine("    mParent = parent;")
        sb.appendLine("}")
        sb.appendLine("```\n")
    }

    /**
     * 完整流程图
     */
    private fun showCompleteFlow() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("           完整启动流程总结")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【完整时序图】\n")
        sb.appendLine("```\n")
        sb.appendLine("Launcher    AMS      Zygote    ActivityThread    Activity")
        sb.appendLine("   │        │         │             │               │")
        sb.appendLine("   │ startActivity  │             │               │")
        sb.appendLine("   │───────>│       │             │               │")
        sb.appendLine("   │        │ resolveActivity     │               │")
        sb.appendLine("   │        │       │             │               │")
        sb.appendLine("   │        │ startProcessIfNeeded│               │")
        sb.appendLine("   │        │──────>│             │               │")
        sb.appendLine("   │        │       │ fork()      │               │")
        sb.appendLine("   │        │       │────────────>│               │")
        sb.appendLine("   │        │       │             │ main()        │")
        sb.appendLine("   │        │       │             │ attach()      │")
        sb.appendLine("   │        │       │             │               │")
        sb.appendLine("   │        │ attachApplication   │               │")
        sb.appendLine("   │        │────────────────────>│               │")
        sb.appendLine("   │        │       │             │ bindApplication")
        sb.appendLine("   │        │       │             │               │")
        sb.appendLine("   │        │ scheduleLaunchActivity              │")
        sb.appendLine("   │        │────────────────────>│               │")
        sb.appendLine("   │        │       │             │ handleLaunchActivity")
        sb.appendLine("   │        │       │             │               │")
        sb.appendLine("   │        │       │             │ performLaunchActivity")
        sb.appendLine("   │        │       │             │               │")
        sb.appendLine("   │        │       │             │ newActivity() │")
        sb.appendLine("   │        │       │             │ activity.attach()")
        sb.appendLine("   │        │       │             │               │")
        sb.appendLine("   │        │       │             │ callActivityOnCreate")
        sb.appendLine("   │        │       │             │──────────────>│")
        sb.appendLine("   │        │       │             │               │ onCreate()")
        sb.appendLine("   │        │       │             │               │")
        sb.appendLine("   │        │       │             │ handleResumeActivity")
        sb.appendLine("   │        │       │             │               │")
        sb.appendLine("   │        │       │             │ callActivityOnResume")
        sb.appendLine("   │        │       │             │──────────────>│")
        sb.appendLine("   │        │       │             │               │ onResume()")
        sb.appendLine("   │        │       │             │               │")
        sb.appendLine("```\n")
        
        sb.appendLine("【关键类总结】\n")
        sb.appendLine("┌───────────────────────────┬───────────────────────────────────────┐\n")
        sb.appendLine("│ 类名                      │ 作用                                  │\n")
        sb.appendLine("├───────────────────────────┼───────────────────────────────────────┤\n")
        sb.appendLine("│ ActivityThread            │ 主线程管理类，处理所有组件消息        │\n")
        sb.appendLine("│ ApplicationThread         │ Binder 通信类，接收 AMS 指令          │\n")
        sb.appendLine("│ H                         │ 主线程 Handler，分发消息              │\n")
        sb.appendLine("│ Instrumentation           │ 生命周期回调执行器                    │\n")
        sb.appendLine("│ ActivityClientRecord      │ Activity 记录信息                     │\n")
        sb.appendLine("│ LoadedApk                 │ APK 信息封装                          │\n")
        sb.appendLine("│ ActivityManagerService    │ 系统服务，管理所有 Activity           │\n")
        sb.appendLine("│ Zygote                    │ 进程孵化器                            │\n")
        sb.appendLine("└───────────────────────────┴───────────────────────────────────────┘\n")
        
        sb.appendLine("【启动耗时分布】\n")
        sb.appendLine("┌─────────────────────────┬────────────────────────────────────┐\n")
        sb.appendLine("│ 阶段                    │ 主要耗时点                         │\n")
        sb.appendLine("├─────────────────────────┼────────────────────────────────────┤\n")
        sb.appendLine("│ 进程启动                │ Zygote fork (50-100ms)             │\n")
        sb.appendLine("│ Application 创建        │ Application.onCreate()             │\n")
        sb.appendLine("│ Activity 创建           │ 反射创建 + attach                  │\n")
        sb.appendLine("│ Activity 初始化         │ onCreate/onStart/onResume          │\n")
        sb.appendLine("│ View 绑定               │ setContentView + 布局加载          │\n")
        sb.appendLine("│ 首帧绘制                │ measure/layout/draw                │\n")
        sb.appendLine("└─────────────────────────┴────────────────────────────────────┘\n")
    }
}
