package com.peter.window.demo.activitythread.practice

import android.app.Activity
import android.app.Application
import android.app.Instrumentation
import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.os.Handler
import android.os.IBinder
import android.os.Looper
import android.os.Message
import android.util.Log
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import com.peter.window.demo.R
import java.lang.reflect.Field
import java.lang.reflect.Method

/**
 * ActivityThread 实践篇 - Hook 与监控
 *
 * === 实战应用 ===
 *
 * 通过 Hook ActivityThread，可以实现：
 * 1. 全局生命周期监控
 * 2. 启动耗时统计
 * 3. 页面跳转拦截
 * 4. 插件化框架基础
 */
class ActivityThreadHookActivity : AppCompatActivity() {

    companion object {
        private const val TAG = "ActivityThreadHook"
    }

    private val sb = StringBuilder()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_activitythread_hook)
        
        showHookOverview()
        showLifeCycleMonitor()
        showStartupTimeMonitor()
        showHandlerHook()
        showMessageLogging()
        
        findViewById<TextView>(R.id.tvContent).text = sb.toString()
    }

    /**
     * Hook 概述
     */
    private fun showHookOverview() {
        sb.appendLine("═══════════════════════════════════════════════════")
        sb.appendLine("           ActivityThread Hook 概述")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【可 Hook 的点】\n")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                   ActivityThread Hook 点                    │\n")
        sb.appendLine("├─────────────────────────────────────────────────────────────┤\n")
        sb.appendLine("│  1. mInstrumentation                                        │\n")
        sb.appendLine("│     → 监控所有 Activity 生命周期                            │\n")
        sb.appendLine("│     → 拦截 startActivity                                    │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  2. mH (Handler)                                            │\n")
        sb.appendLine("│     → 监控所有消息分发                                      │\n")
        sb.appendLine("│     → 拦截特定消息处理                                      │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  3. Looper                                                  │\n")
        sb.appendLine("│     → 监控消息循环耗时                                      │\n")
        sb.appendLine("│     → 检测卡顿                                              │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  4. mActivities                                             │\n")
        sb.appendLine("│     → 获取当前所有 Activity                                 │\n")
        sb.appendLine("│     → 管理 Activity 栈                                      │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  5. mApplication                                            │\n")
        sb.appendLine("│     → 监控 Application 生命周期                             │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────┘\n")
        
        sb.appendLine("【Hook 原理】\n")
        sb.appendLine("```\n")
        sb.appendLine("┌─────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                  ActivityThread                     │\n")
        sb.appendLine("│                                                     │\n")
        sb.appendLine("│  ┌─────────────────┐      ┌─────────────────┐      │\n")
        sb.appendLine("│  │ mInstrumentation│      │      mH         │      │\n")
        sb.appendLine("│  │ (原对象)        │      │  (原 Handler)   │      │\n")
        sb.appendLine("│  └────────┬────────┘      └────────┬────────┘      │\n")
        sb.appendLine("│           │                        │                │\n")
        sb.appendLine("│           │ 反射替换               │ 反射修改       │\n")
        sb.appendLine("│           ▼                        ▼                │\n")
        sb.appendLine("│  ┌─────────────────┐      ┌─────────────────┐      │\n")
        sb.appendLine("│  │ ProxyInstrument │      │  ProxyCallback  │      │\n")
        sb.appendLine("│  │ (代理对象)      │      │  (代理回调)     │      │\n")
        sb.appendLine("│  └─────────────────┘      └─────────────────┘      │\n")
        sb.appendLine("│                                                     │\n")
        sb.appendLine("└─────────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")
    }

    /**
     * 生命周期监控
     */
    private fun showLifeCycleMonitor() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("           生命周期监控实现")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【完整的生命周期监控类】\n")
        sb.appendLine("```java")
        sb.appendLine("public class LifecycleMonitor extends Instrumentation {")
        sb.appendLine("    ")
        sb.appendLine("    private static final String TAG = \"LifecycleMonitor\";")
        sb.appendLine("    private Instrumentation mOriginal;")
        sb.appendLine("    ")
        sb.appendLine("    // 生命周期回调接口")
        sb.appendLine("    public interface LifecycleCallback {")
        sb.appendLine("        void onActivityLifecycleChanged(Activity activity,")
        sb.appendLine("                String lifecycle, long costMs);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    private List<LifecycleCallback> mCallbacks = new ArrayList<>();")
        sb.appendLine("    ")
        sb.appendLine("    public LifecycleMonitor(Instrumentation original) {")
        sb.appendLine("        mOriginal = original;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    public void addCallback(LifecycleCallback callback) {")
        sb.appendLine("        mCallbacks.add(callback);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void callActivityOnCreate(Activity activity, Bundle icicle) {")
        sb.appendLine("        long start = System.currentTimeMillis();")
        sb.appendLine("        dispatchLifecycleStart(activity, \"onCreate\");")
        sb.appendLine("        ")
        sb.appendLine("        super.callActivityOnCreate(activity, icicle);")
        sb.appendLine("        ")
        sb.appendLine("        long cost = System.currentTimeMillis() - start;")
        sb.appendLine("        dispatchLifecycleEnd(activity, \"onCreate\", cost);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void callActivityOnStart(Activity activity) {")
        sb.appendLine("        long start = System.currentTimeMillis();")
        sb.appendLine("        dispatchLifecycleStart(activity, \"onStart\");")
        sb.appendLine("        ")
        sb.appendLine("        super.callActivityOnStart(activity);")
        sb.appendLine("        ")
        sb.appendLine("        long cost = System.currentTimeMillis() - start;")
        sb.appendLine("        dispatchLifecycleEnd(activity, \"onStart\", cost);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void callActivityOnResume(Activity activity) {")
        sb.appendLine("        long start = System.currentTimeMillis();")
        sb.appendLine("        dispatchLifecycleStart(activity, \"onResume\");")
        sb.appendLine("        ")
        sb.appendLine("        super.callActivityOnResume(activity);")
        sb.appendLine("        ")
        sb.appendLine("        long cost = System.currentTimeMillis() - start;")
        sb.appendLine("        dispatchLifecycleEnd(activity, \"onResume\", cost);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void callActivityOnPause(Activity activity) {")
        sb.appendLine("        long start = System.currentTimeMillis();")
        sb.appendLine("        dispatchLifecycleStart(activity, \"onPause\");")
        sb.appendLine("        ")
        sb.appendLine("        super.callActivityOnPause(activity);")
        sb.appendLine("        ")
        sb.appendLine("        long cost = System.currentTimeMillis() - start;")
        sb.appendLine("        dispatchLifecycleEnd(activity, \"onPause\", cost);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void callActivityOnStop(Activity activity) {")
        sb.appendLine("        long start = System.currentTimeMillis();")
        sb.appendLine("        dispatchLifecycleStart(activity, \"onStop\");")
        sb.appendLine("        ")
        sb.appendLine("        super.callActivityOnStop(activity);")
        sb.appendLine("        ")
        sb.appendLine("        long cost = System.currentTimeMillis() - start;")
        sb.appendLine("        dispatchLifecycleEnd(activity, \"onStop\", cost);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void callActivityOnDestroy(Activity activity) {")
        sb.appendLine("        long start = System.currentTimeMillis();")
        sb.appendLine("        dispatchLifecycleStart(activity, \"onDestroy\");")
        sb.appendLine("        ")
        sb.appendLine("        super.callActivityOnDestroy(activity);")
        sb.appendLine("        ")
        sb.appendLine("        long cost = System.currentTimeMillis() - start;")
        sb.appendLine("        dispatchLifecycleEnd(activity, \"onDestroy\", cost);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    private void dispatchLifecycleStart(Activity activity, String lifecycle) {")
        sb.appendLine("        Log.d(TAG, String.format(\"[%s] %s 开始\",")
        sb.appendLine("                activity.getClass().getSimpleName(), lifecycle));")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    private void dispatchLifecycleEnd(Activity activity, String lifecycle, long cost) {")
        sb.appendLine("        Log.d(TAG, String.format(\"[%s] %s 结束, 耗时: %dms\",")
        sb.appendLine("                activity.getClass().getSimpleName(), lifecycle, cost));")
        sb.appendLine("        ")
        sb.appendLine("        for (LifecycleCallback callback : mCallbacks) {")
        sb.appendLine("            callback.onActivityLifecycleChanged(activity, lifecycle, cost);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 保留原始的 execStartActivity 方法")
        sb.appendLine("    @Override")
        sb.appendLine("    public ActivityResult execStartActivity(")
        sb.appendLine("            Context who, IBinder contextThread, IBinder token, Activity target,")
        sb.appendLine("            Intent intent, int requestCode, Bundle options) {")
        sb.appendLine("        Log.d(TAG, \"启动 Activity: \" + intent.getComponent());")
        sb.appendLine("        ")
        sb.appendLine("        try {")
        sb.appendLine("            Method method = Instrumentation.class.getDeclaredMethod(")
        sb.appendLine("                    \"execStartActivity\", Context.class, IBinder.class,")
        sb.appendLine("                    IBinder.class, Activity.class, Intent.class,")
        sb.appendLine("                    int.class, Bundle.class);")
        sb.appendLine("            method.setAccessible(true);")
        sb.appendLine("            return (ActivityResult) method.invoke(mOriginal, who,")
        sb.appendLine("                    contextThread, token, target, intent, requestCode, options);")
        sb.appendLine("        } catch (Exception e) {")
        sb.appendLine("            Log.e(TAG, \"execStartActivity error\", e);")
        sb.appendLine("        }")
        sb.appendLine("        return null;")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【安装 Hook】\n")
        sb.appendLine("```java")
        sb.appendLine("public class LifecycleMonitorInstaller {")
        sb.appendLine("    ")
        sb.appendLine("    public static void install() {")
        sb.appendLine("        try {")
        sb.appendLine("            // 获取 ActivityThread")
        sb.appendLine("            Class<?> activityThreadClass = Class.forName(\"android.app.ActivityThread\");")
        sb.appendLine("            Method currentActivityThreadMethod = ")
        sb.appendLine("                    activityThreadClass.getDeclaredMethod(\"currentActivityThread\");")
        sb.appendLine("            Object activityThread = currentActivityThreadMethod.invoke(null);")
        sb.appendLine("            ")
        sb.appendLine("            // 获取原始 Instrumentation")
        sb.appendLine("            Field mInstrumentationField = ")
        sb.appendLine("                    activityThreadClass.getDeclaredField(\"mInstrumentation\");")
        sb.appendLine("            mInstrumentationField.setAccessible(true);")
        sb.appendLine("            Instrumentation original = ")
        sb.appendLine("                    (Instrumentation) mInstrumentationField.get(activityThread);")
        sb.appendLine("            ")
        sb.appendLine("            // 创建并设置监控器")
        sb.appendLine("            LifecycleMonitor monitor = new LifecycleMonitor(original);")
        sb.appendLine("            monitor.addCallback((activity, lifecycle, cost) -> {")
        sb.appendLine("                // 可以上报到监控平台")
        sb.appendLine("                if (cost > 100) {")
        sb.appendLine("                    Log.w(\"Performance\", activity.getClass().getSimpleName()")
        sb.appendLine("                            + \".\" + lifecycle + \" 耗时过长: \" + cost + \"ms\");")
        sb.appendLine("                }")
        sb.appendLine("            });")
        sb.appendLine("            ")
        sb.appendLine("            mInstrumentationField.set(activityThread, monitor);")
        sb.appendLine("            ")
        sb.appendLine("        } catch (Exception e) {")
        sb.appendLine("            Log.e(\"LifecycleMonitor\", \"安装失败\", e);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
    }

    /**
     * 启动耗时监控
     */
    private fun showStartupTimeMonitor() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("           启动耗时监控")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【应用启动时间点】\n")
        sb.appendLine("```\n")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                     应用启动时间线                          │\n")
        sb.appendLine("├─────────────────────────────────────────────────────────────┤\n")
        sb.appendLine("│  T1: Application 构造函数                                   │\n")
        sb.appendLine("│  T2: Application.attachBaseContext()                        │\n")
        sb.appendLine("│  T3: Application.onCreate()                                 │\n")
        sb.appendLine("│  T4: Activity 构造函数                                      │\n")
        sb.appendLine("│  T5: Activity.attach()                                      │\n")
        sb.appendLine("│  T6: Activity.onCreate()                                    │\n")
        sb.appendLine("│  T7: Activity.onStart()                                     │\n")
        sb.appendLine("│  T8: Activity.onResume()                                    │\n")
        sb.appendLine("│  T9: 首帧绘制完成                                           │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")
        
        sb.appendLine("【启动耗时监控实现】\n")
        sb.appendLine("```java")
        sb.appendLine("public class StartupTimeMonitor {")
        sb.appendLine("    ")
        sb.appendLine("    private static final String TAG = \"StartupTime\";")
        sb.appendLine("    ")
        sb.appendLine("    // 各阶段时间戳")
        sb.appendLine("    private static long sApplicationCreateTime;")
        sb.appendLine("    private static long sApplicationAttachTime;")
        sb.appendLine("    private static long sApplicationOnCreateTime;")
        sb.appendLine("    private static long sActivityCreateTime;")
        sb.appendLine("    private static long sActivityOnCreateTime;")
        sb.appendLine("    private static long sActivityOnResumeTime;")
        sb.appendLine("    private static long sFirstFrameTime;")
        sb.appendLine("    ")
        sb.appendLine("    // 应用构造函数时间")
        sb.appendLine("    public static void recordApplicationCreate() {")
        sb.appendLine("        sApplicationCreateTime = System.currentTimeMillis();")
        sb.appendLine("        Log.d(TAG, \"Application 构造: \" + sApplicationCreateTime);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // Application.attachBaseContext")
        sb.appendLine("    public static void recordApplicationAttach() {")
        sb.appendLine("        sApplicationAttachTime = System.currentTimeMillis();")
        sb.appendLine("        Log.d(TAG, \"Application.attachBaseContext: \" + sApplicationAttachTime);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // Application.onCreate")
        sb.appendLine("    public static void recordApplicationOnCreate() {")
        sb.appendLine("        sApplicationOnCreateTime = System.currentTimeMillis();")
        sb.appendLine("        Log.d(TAG, \"Application.onCreate: \" + sApplicationOnCreateTime);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // Activity 创建")
        sb.appendLine("    public static void recordActivityCreate() {")
        sb.appendLine("        sActivityCreateTime = System.currentTimeMillis();")
        sb.appendLine("        Log.d(TAG, \"Activity 创建: \" + sActivityCreateTime);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // Activity.onCreate")
        sb.appendLine("    public static void recordActivityOnCreate() {")
        sb.appendLine("        sActivityOnCreateTime = System.currentTimeMillis();")
        sb.appendLine("        Log.d(TAG, \"Activity.onCreate: \" + sActivityOnCreateTime);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // Activity.onResume")
        sb.appendLine("    public static void recordActivityOnResume() {")
        sb.appendLine("        sActivityOnResumeTime = System.currentTimeMillis();")
        sb.appendLine("        Log.d(TAG, \"Activity.onResume: \" + sActivityOnResumeTime);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 首帧绘制")
        sb.appendLine("    public static void recordFirstFrame() {")
        sb.appendLine("        sFirstFrameTime = System.currentTimeMillis();")
        sb.appendLine("        Log.d(TAG, \"首帧绘制: \" + sFirstFrameTime);")
        sb.appendLine("        ")
        sb.appendLine("        // 计算并输出各阶段耗时")
        sb.appendLine("        printStartupReport();")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    private static void printStartupReport() {")
        sb.appendLine("        StringBuilder sb = new StringBuilder();")
        sb.appendLine("        sb.append(\"\\n====== 启动耗时报告 ======\\n\");")
        sb.appendLine("        sb.append(String.format(\"Application 构造耗时: %dms\\n\",")
        sb.appendLine("                sApplicationAttachTime - sApplicationCreateTime));")
        sb.appendLine("        sb.append(String.format(\"Application.attachBaseContext 耗时: %dms\\n\",")
        sb.appendLine("                sApplicationOnCreateTime - sApplicationAttachTime));")
        sb.appendLine("        sb.append(String.format(\"Application.onCreate 耗时: %dms\\n\",")
        sb.appendLine("                sActivityCreateTime - sApplicationOnCreateTime));")
        sb.appendLine("        sb.append(String.format(\"Activity 创建到 onCreate 耗时: %dms\\n\",")
        sb.appendLine("                sActivityOnCreateTime - sActivityCreateTime));")
        sb.appendLine("        sb.append(String.format(\"Activity onCreate 到 onResume 耗时: %dms\\n\",")
        sb.appendLine("                sActivityOnResumeTime - sActivityOnCreateTime));")
        sb.appendLine("        sb.append(String.format(\"Activity onResume 到首帧耗时: %dms\\n\",")
        sb.appendLine("                sFirstFrameTime - sActivityOnResumeTime));")
        sb.appendLine("        sb.append(String.format(\"总启动耗时: %dms\\n\",")
        sb.appendLine("                sFirstFrameTime - sApplicationCreateTime));")
        sb.appendLine("        sb.append(\"=========================\");")
        sb.appendLine("        ")
        sb.appendLine("        Log.i(TAG, sb.toString());")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【首帧绘制检测】\n")
        sb.appendLine("```java")
        sb.appendLine("// 在 Activity.onResume 中注册")
        sb.appendLine("public class FirstFrameDetector {")
        sb.appendLine("    ")
        sb.appendLine("    public static void detect(Activity activity) {")
        sb.appendLine("        // 方式一：使用 OnWindowFocusChangeListener")
        sb.appendLine("        activity.getWindow().getDecorView().getViewTreeObserver()")
        sb.appendLine("                .addOnWindowFocusChangeListener(new ViewTreeObserver.OnWindowFocusChangeListener() {")
        sb.appendLine("                    @Override")
        sb.appendLine("                    public void onWindowFocusChanged(boolean hasFocus) {")
        sb.appendLine("                        if (hasFocus) {")
        sb.appendLine("                            StartupTimeMonitor.recordFirstFrame();")
        sb.appendLine("                            activity.getWindow().getDecorView().getViewTreeObserver()")
        sb.appendLine("                                    .removeOnWindowFocusChangeListener(this);")
        sb.appendLine("                        }")
        sb.appendLine("                    }")
        sb.appendLine("                });")
        sb.appendLine("        ")
        sb.appendLine("        // 方式二：使用 OnGlobalLayoutListener")
        sb.appendLine("        activity.getWindow().getDecorView().getViewTreeObserver()")
        sb.appendLine("                .addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {")
        sb.appendLine("                    @Override")
        sb.appendLine("                    public void onGlobalLayout() {")
        sb.appendLine("                        StartupTimeMonitor.recordFirstFrame();")
        sb.appendLine("                        activity.getWindow().getDecorView().getViewTreeObserver()")
        sb.appendLine("                                .removeOnGlobalLayoutListener(this);")
        sb.appendLine("                    }")
        sb.appendLine("                });")
        sb.appendLine("        ")
        sb.appendLine("        // 方式三：使用 Choreographer")
        sb.appendLine("        Choreographer.getInstance().postFrameCallback(new Choreographer.FrameCallback() {")
        sb.appendLine("            @Override")
        sb.appendLine("            public void doFrame(long frameTimeNanos) {")
        sb.appendLine("                StartupTimeMonitor.recordFirstFrame();")
        sb.appendLine("            }")
        sb.appendLine("        });")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
    }

    /**
     * Handler Hook
     */
    private fun showHandlerHook() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("           Handler Hook 实现")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【Hook H Handler】\n")
        sb.appendLine("```java")
        sb.appendLine("public class HandlerHook {")
        sb.appendLine("    ")
        sb.appendLine("    private static final String TAG = \"HandlerHook\";")
        sb.appendLine("    ")
        sb.appendLine("    public static void hook() {")
        sb.appendLine("        try {")
        sb.appendLine("            // 1. 获取 ActivityThread")
        sb.appendLine("            Class<?> activityThreadClass = Class.forName(\"android.app.ActivityThread\");")
        sb.appendLine("            Field currentActivityThreadField = ")
        sb.appendLine("                    activityThreadClass.getDeclaredField(\"sCurrentActivityThread\");")
        sb.appendLine("            currentActivityThreadField.setAccessible(true);")
        sb.appendLine("            Object activityThread = currentActivityThreadField.get(null);")
        sb.appendLine("            ")
        sb.appendLine("            // 2. 获取 mH")
        sb.appendLine("            Field mHField = activityThreadClass.getDeclaredField(\"mH\");")
        sb.appendLine("            mHField.setAccessible(true);")
        sb.appendLine("            Handler mH = (Handler) mHField.get(activityThread);")
        sb.appendLine("            ")
        sb.appendLine("            // 3. 获取 mCallback 字段")
        sb.appendLine("            Field mCallbackField = Handler.class.getDeclaredField(\"mCallback\");")
        sb.appendLine("            mCallbackField.setAccessible(true);")
        sb.appendLine("            ")
        sb.appendLine("            // 4. 创建代理 Callback")
        sb.appendLine("            Handler.Callback proxyCallback = new Handler.Callback() {")
        sb.appendLine("                @Override")
        sb.appendLine("                public boolean handleMessage(Message msg) {")
        sb.appendLine("                    String messageName = getMessageName(msg.what);")
        sb.appendLine("                    Log.d(TAG, \"拦截消息: \" + messageName + \" (\" + msg.what + \")\");")
        sb.appendLine("                    ")
        sb.appendLine("                    long start = System.currentTimeMillis();")
        sb.appendLine("                    ")
        sb.appendLine("                    // 可以在这里做监控或拦截")
        sb.appendLine("                    switch (msg.what) {")
        sb.appendLine("                        case 100: // LAUNCH_ACTIVITY")
        sb.appendLine("                            Log.d(TAG, \"即将启动 Activity\");")
        sb.appendLine("                            break;")
        sb.appendLine("                        case 107: // RESUME_ACTIVITY")
        sb.appendLine("                            Log.d(TAG, \"即将 Resume Activity\");")
        sb.appendLine("                            break;")
        sb.appendLine("                    }")
        sb.appendLine("                    ")
        sb.appendLine("                    // 返回 false 让原始 Handler 继续处理")
        sb.appendLine("                    return false;")
        sb.appendLine("                }")
        sb.appendLine("            };")
        sb.appendLine("            ")
        sb.appendLine("            // 5. 替换 Callback")
        sb.appendLine("            mCallbackField.set(mH, proxyCallback);")
        sb.appendLine("            ")
        sb.appendLine("            Log.d(TAG, \"Handler Hook 成功\");")
        sb.appendLine("            ")
        sb.appendLine("        } catch (Exception e) {")
        sb.appendLine("            Log.e(TAG, \"Handler Hook 失败\", e);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    private static String getMessageName(int what) {")
        sb.appendLine("        switch (what) {")
        sb.appendLine("            case 100: return \"LAUNCH_ACTIVITY\";")
        sb.appendLine("            case 101: return \"PAUSE_ACTIVITY\";")
        sb.appendLine("            case 107: return \"RESUME_ACTIVITY\";")
        sb.appendLine("            case 109: return \"DESTROY_ACTIVITY\";")
        sb.appendLine("            case 110: return \"BIND_APPLICATION\";")
        sb.appendLine("            case 114: return \"CREATE_SERVICE\";")
        sb.appendLine("            case 121: return \"BIND_SERVICE\";")
        sb.appendLine("            default: return \"UNKNOWN\";")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【消息处理流程】\n")
        sb.appendLine("```\n")
        sb.appendLine("               Handler.dispatchMessage(msg)")
        sb.appendLine("                         │")
        sb.appendLine("                         ▼")
        sb.appendLine("              ┌────────────────────┐")
        sb.appendLine("              │ msg.callback != null?│")
        sb.appendLine("              └────────────────────┘")
        sb.appendLine("                 │ Yes        │ No")
        sb.appendLine("                 ▼            ▼")
        sb.appendLine("          ┌──────────────┐  ┌─────────────────────┐")
        sb.appendLine("          │handleCallback│  │ mCallback != null?  │")
        sb.appendLine("          └──────────────┘  └─────────────────────┘")
        sb.appendLine("                                │ Yes        │ No")
        sb.appendLine("                                ▼            ▼")
        sb.appendLine("                      ┌──────────────────┐  ┌────────────────┐")
        sb.appendLine("                      │ proxyCallback    │  │ handleMessage()│")
        sb.appendLine("                      │ .handleMessage() │  │                │")
        sb.appendLine("                      └──────────────────┘  └────────────────┘")
        sb.appendLine("                                │")
        sb.appendLine("                                │ return false")
        sb.appendLine("                                ▼")
        sb.appendLine("                      ┌────────────────────┐")
        sb.appendLine("                      │ mH.handleMessage() │")
        sb.appendLine("                      │ (原始处理逻辑)     │")
        sb.appendLine("                      └────────────────────┘")
        sb.appendLine("```\n")
    }

    /**
     * 消息日志
     */
    private fun showMessageLogging() {
        sb.appendLine("\n═══════════════════════════════════════════════════")
        sb.appendLine("           消息循环监控与卡顿检测")
        sb.appendLine("═══════════════════════════════════════════════════\n")
        
        sb.appendLine("【Looper.setMessageLogging】\n")
        sb.appendLine("```java")
        sb.appendLine("public class MessageLoggingMonitor {")
        sb.appendLine("    ")
        sb.appendLine("    private static final String TAG = \"MessageLogging\";")
        sb.appendLine("    private static final long BLOCK_THRESHOLD = 100; // 100ms 卡顿阈值")
        sb.appendLine("    ")
        sb.appendLine("    public static void start() {")
        sb.appendLine("        Looper.getMainLooper().setMessageLogging(new Printer() {")
        sb.appendLine("            private long mStartTime;")
        sb.appendLine("            ")
        sb.appendLine("            @Override")
        sb.appendLine("            public void println(String x) {")
        sb.appendLine("                if (x.startsWith(\">>>>> Dispatching to\")) {")
        sb.appendLine("                    // 消息开始处理")
        sb.appendLine("                    mStartTime = System.currentTimeMillis();")
        sb.appendLine("                } else if (x.startsWith(\"<<<<< Finished to\")) {")
        sb.appendLine("                    // 消息处理完成")
        sb.appendLine("                    long cost = System.currentTimeMillis() - mStartTime;")
        sb.appendLine("                    ")
        sb.appendLine("                    if (cost > BLOCK_THRESHOLD) {")
        sb.appendLine("                        Log.w(TAG, \"检测到卡顿! 耗时: \" + cost + \"ms\");")
        sb.appendLine("                        Log.w(TAG, \"堆栈: \" + getStackTrace());")
        sb.appendLine("                    }")
        sb.appendLine("                }")
        sb.appendLine("            }")
        sb.appendLine("        });")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    private static String getStackTrace() {")
        sb.appendLine("        StringBuilder sb = new StringBuilder();")
        sb.appendLine("        StackTraceElement[] stackTrace = Looper.getMainLooper().getThread().getStackTrace();")
        sb.appendLine("        for (StackTraceElement element : stackTrace) {")
        sb.appendLine("            sb.append(\"\\n    at \").append(element.toString());")
        sb.appendLine("        }")
        sb.appendLine("        return sb.toString();")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【BlockCanary 原理】\n")
        sb.appendLine("```\n")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                    BlockCanary 原理                         │\n")
        sb.appendLine("├─────────────────────────────────────────────────────────────┤\n")
        sb.appendLine("│  1. Looper.setMessageLogging() 设置日志打印器              │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  2. 消息开始时：                                            │\n")
        sb.appendLine("│     - 记录开始时间                                          │\n")
        sb.appendLine("│     - 启动采样线程，定期采集主线程堆栈                      │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  3. 消息结束时：                                            │\n")
        sb.appendLine("│     - 计算耗时                                              │\n")
        sb.appendLine("│     - 如果超过阈值，保存堆栈信息                            │\n")
        sb.appendLine("│     - 停止采样线程                                          │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  4. 输出卡顿报告：                                          │\n")
        sb.appendLine("│     - 卡顿时间                                              │\n")
        sb.appendLine("│     - 主线程堆栈                                            │\n")
        sb.appendLine("│     - CPU 使用情况                                          │\n")
        sb.appendLine("│     - 内存使用情况                                          │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")
        
        sb.appendLine("【完整的卡顿检测实现】\n")
        sb.appendLine("```java")
        sb.appendLine("public class BlockDetector {")
        sb.appendLine("    ")
        sb.appendLine("    private static final String TAG = \"BlockDetector\";")
        sb.appendLine("    private static final long BLOCK_THRESHOLD_MS = 100;")
        sb.appendLine("    private static final long SAMPLE_INTERVAL_MS = 50;")
        sb.appendLine("    ")
        sb.appendLine("    private static volatile boolean sSampling = false;")
        sb.appendLine("    private static List<String> sStackSamples = new ArrayList<>();")
        sb.appendLine("    private static long sStartTime;")
        sb.appendLine("    ")
        sb.appendLine("    public static void install() {")
        sb.appendLine("        Looper.getMainLooper().setMessageLogging(new Printer() {")
        sb.appendLine("            @Override")
        sb.appendLine("            public void println(String x) {")
        sb.appendLine("                if (x.startsWith(\">>>>> Dispatching\")) {")
        sb.appendLine("                    startSampling();")
        sb.appendLine("                } else if (x.startsWith(\"<<<<< Finished\")) {")
        sb.appendLine("                    stopSampling();")
        sb.appendLine("                }")
        sb.appendLine("            }")
        sb.appendLine("        });")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    private static void startSampling() {")
        sb.appendLine("        sStartTime = System.currentTimeMillis();")
        sb.appendLine("        sSampling = true;")
        sb.appendLine("        sStackSamples.clear();")
        sb.appendLine("        ")
        sb.appendLine("        new Thread(() -> {")
        sb.appendLine("            while (sSampling) {")
        sb.appendLine("                try {")
        sb.appendLine("                    Thread.sleep(SAMPLE_INTERVAL_MS);")
        sb.appendLine("                    ")
        sb.appendLine("                    // 采集主线程堆栈")
        sb.appendLine("                    StringBuilder sb = new StringBuilder();")
        sb.appendLine("                    sb.append(\"\\n=== \").append(System.currentTimeMillis() - sStartTime)")
        sb.appendLine("                            .append(\"ms ===\");")
        sb.appendLine("                    ")
        sb.appendLine("                    StackTraceElement[] stack = Looper.getMainLooper()")
        sb.appendLine("                            .getThread().getStackTrace();")
        sb.appendLine("                    for (StackTraceElement e : stack) {")
        sb.appendLine("                        sb.append(\"\\n    at \").append(e.toString());")
        sb.appendLine("                    }")
        sb.appendLine("                    ")
        sb.appendLine("                    synchronized (sStackSamples) {")
        sb.appendLine("                        sStackSamples.add(sb.toString());")
        sb.appendLine("                    }")
        sb.appendLine("                    ")
        sb.appendLine("                } catch (InterruptedException e) {")
        sb.appendLine("                    break;")
        sb.appendLine("                }")
        sb.appendLine("            }")
        sb.appendLine("        }).start();")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    private static void stopSampling() {")
        sb.appendLine("        sSampling = false;")
        sb.appendLine("        long cost = System.currentTimeMillis() - sStartTime;")
        sb.appendLine("        ")
        sb.appendLine("        if (cost > BLOCK_THRESHOLD_MS) {")
        sb.appendLine("            StringBuilder report = new StringBuilder();")
        sb.appendLine("            report.append(\"\\n====== 卡顿报告 ======\\n\");")
        sb.appendLine("            report.append(\"耗时: \").append(cost).append(\"ms\\n\");")
        sb.appendLine("            ")
        sb.appendLine("            synchronized (sStackSamples) {")
        sb.appendLine("                for (String sample : sStackSamples) {")
        sb.appendLine("                    report.append(sample);")
        sb.appendLine("                }")
        sb.appendLine("            }")
        sb.appendLine("            ")
        sb.appendLine("            report.append(\"\\n=====================\");")
        sb.appendLine("            ")
        sb.appendLine("            Log.w(TAG, report.toString());")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
    }
}
