package com.peter.window.demo.viewroot.deep

import android.os.Bundle
import android.view.Choreographer
import androidx.appcompat.app.AppCompatActivity
import com.peter.window.demo.databinding.ActivityChoreographerBinding

/**
 * 深入篇：Choreographer 与 VSync
 * 
 * Choreographer 是 Android 渲染系统的核心协调者，
 * 它接收 VSync 信号并协调 UI 渲染的时机。
 * 
 * ViewRootImpl 通过 Choreographer 来调度 performTraversals()，
 * 确保在 VSync 信号到来时进行绘制，实现流畅的 60fps 渲染。
 */
class ChoreographerActivity : AppCompatActivity() {

    private lateinit var binding: ActivityChoreographerBinding
    private val sb = StringBuilder()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityChoreographerBinding.inflate(layoutInflater)
        setContentView(binding.root)
        supportActionBar?.setDisplayHomeAsUpEnabled(true)

        setupListeners()
        showChoreographerOverview()
    }

    private fun setupListeners() {
        binding.btnOverview.setOnClickListener { showChoreographerOverview() }
        binding.btnVSync.setOnClickListener { showVSyncMechanism() }
        binding.btnCallbackQueue.setOnClickListener { showCallbackQueue() }
        binding.btnFrameCallback.setOnClickListener { showFrameCallback() }
        binding.btnFrameTimeline.setOnClickListener { showFrameTimeline() }
        binding.btnViewRootRelation.setOnClickListener { showViewRootRelation() }
        binding.btnPerformance.setOnClickListener { showPerformance() }
        binding.btnPractice.setOnClickListener { demonstrateChoreographer() }
    }

    /**
     * Choreographer 概述
     */
    private fun showChoreographerOverview() {
        sb.clear()
        sb.appendLine("=== Choreographer 概述 ===\n")
        
        sb.appendLine("【什么是 Choreographer】")
        sb.appendLine("Choreographer（编舞者）是 Android 4.1 引入的，")
        sb.appendLine("用于协调 UI 渲染的时机，确保渲染与屏幕刷新同步。\n")
        
        sb.appendLine("【核心职责】")
        sb.appendLine("```\n")
        sb.appendLine("1. 接收 VSync 信号")
        sb.appendLine("2. 协调输入、动画、绘制三种回调")
        sb.appendLine("3. 计算帧时间，监控性能")
        sb.appendLine("4. 支持帧率控制和掉帧检测")
        sb.appendLine("```\n")
        
        sb.appendLine("【获取 Choreographer】")
        sb.appendLine("```java")
        sb.appendLine("// 获取当前线程的 Choreographer")
        sb.appendLine("Choreographer choreographer = Choreographer.getInstance();")
        sb.appendLine("```\n")
        
        sb.appendLine("【架构图】")
        sb.appendLine("```\n")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                        应用进程                             │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  ViewRootImpl                                               │\n")
        sb.appendLine("│       │                                                     │\n")
        sb.appendLine("│       ↓                                                     │\n")
        sb.appendLine("│  Choreographer                                              │\n")
        sb.appendLine("│       │                                                     │\n")
        sb.appendLine("│       ├─── CallbackQueue[INPUT]      输入回调              │\n")
        sb.appendLine("│       ├─── CallbackQueue[ANIMATION]  动画回调              │\n")
        sb.appendLine("│       └─── CallbackQueue[TRAVERSAL]  遍历回调              │\n")
        sb.appendLine("│       │                                                     │\n")
        sb.appendLine("│       ↓                                                     │\n")
        sb.appendLine("│  FrameDisplayEventReceiver                                 │\n")
        sb.appendLine("│       │                                                     │\n")
        sb.appendLine("└───────│─────────────────────────────────────────────────────┘\n")
        sb.appendLine("        │ (VSync 信号)")
        sb.appendLine("        ↓")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                        系统进程                             │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  SurfaceFlinger                                             │\n")
        sb.appendLine("│       │                                                     │\n")
        sb.appendLine("│       ↓                                                     │\n")
        sb.appendLine("│  HWComposer (硬件合成器)                                    │\n")
        sb.appendLine("│       │                                                     │\n")
        sb.appendLine("│       ↓                                                     │\n")
        sb.appendLine("│  Display (显示屏)  → VSync 信号                            │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")
        
        sb.appendLine("【核心方法】")
        sb.appendLine("```java")
        sb.appendLine("// 注册 FrameCallback")
        sb.appendLine("public void postFrameCallback(FrameCallback callback)")
        sb.appendLine("public void postFrameCallbackDelayed(FrameCallback callback, long delayMillis)")
        sb.appendLine("")
        sb.appendLine("// 注册其他类型回调")
        sb.appendLine("public void postCallback(int callbackType, Runnable action, Object token)")
        sb.appendLine("")
        sb.appendLine("// 移除回调")
        sb.appendLine("public void removeCallbacks(int callbackType, Runnable action, Object token)")
        sb.appendLine("")
        sb.appendLine("// 获取刷新率")
        sb.appendLine("public float getRefreshRate()")
        sb.appendLine("")
        sb.appendLine("// 获取帧间隔")
        sb.appendLine("public static long getFrameIntervalNanos()")
        sb.appendLine("```\n")
        
        sb.appendLine("【回调类型】")
        sb.appendLine("```java")
        sb.appendLine("// 回调类型常量")
        sb.appendLine("public static final int CALLBACK_INPUT = 0;        // 输入事件")
        sb.appendLine("public static final int CALLBACK_ANIMATION = 1;    // 动画")
        sb.appendLine("public static final int CALLBACK_INSETS_ANIMATION = 2; // 插入动画")
        sb.appendLine("public static final int CALLBACK_TRAVERSAL = 3;    // 遍历")
        sb.appendLine("public static final int CALLBACK_COMMIT = 4;       // 提交")
        sb.appendLine("```\n")
        
        sb.appendLine("【执行顺序】")
        sb.appendLine("```\n")
        sb.appendLine("VSync 信号到来时的执行顺序：")
        sb.appendLine("1. CALLBACK_INPUT      → 处理输入事件")
        sb.appendLine("2. CALLBACK_ANIMATION  → 执行动画")
        sb.appendLine("3. CALLBACK_INSETS_ANIMATION → 执行插入动画")
        sb.appendLine("4. CALLBACK_TRAVERSAL  → 测量、布局、绘制")
        sb.appendLine("5. CALLBACK_COMMIT     → 提交帧")
        sb.appendLine("```\n")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * VSync 机制详解
     */
    private fun showVSyncMechanism() {
        sb.clear()
        sb.appendLine("=== VSync 机制详解 ===\n")
        
        sb.appendLine("【什么是 VSync】")
        sb.appendLine("VSync（Vertical Synchronization，垂直同步）是屏幕刷新信号。")
        sb.appendLine("每当屏幕刷新完一帧后，会发出一个 VSync 信号。\n")
        
        sb.appendLine("【屏幕刷新率】")
        sb.appendLine("```\n")
        sb.appendLine("常见刷新率：")
        sb.appendLine("- 60Hz: 每 16.67ms 刷新一次")
        sb.appendLine("- 90Hz: 每 11.11ms 刷新一次")
        sb.appendLine("- 120Hz: 每 8.33ms 刷新一次")
        sb.appendLine("```\n")
        
        sb.appendLine("【VSync 的作用】")
        sb.appendLine("```\n")
        sb.appendLine("没有 VSync：")
        sb.appendLine("┌──────────────────────────────────────────────────┐\n")
        sb.appendLine("│ GPU 随时绘制 → 可能与屏幕刷新不同步 → 画面撕裂  │\n")
        sb.appendLine("└──────────────────────────────────────────────────┘\n")
        sb.appendLine("")
        sb.appendLine("有 VSync：")
        sb.appendLine("┌──────────────────────────────────────────────────┐\n")
        sb.appendLine("│ VSync 信号 → 开始绘制 → 下一帧 VSync → 显示     │\n")
        sb.appendLine("│ 确保每帧都能在屏幕刷新时完整显示                 │\n")
        sb.appendLine("└──────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")
        
        sb.appendLine("【FrameDisplayEventReceiver】")
        sb.appendLine("```java")
        sb.appendLine("// Choreographer 内部类，接收 VSync 信号")
        sb.appendLine("private final class FrameDisplayEventReceiver extends DisplayEventReceiver")
        sb.appendLine("        implements Runnable {")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void onVsync(long timestampNanos, int builtInDisplayId, int frame) {")
        sb.appendLine("        // 保存 VSync 时间戳")
        sb.appendLine("        mTimestampNanos = timestampNanos;")
        sb.appendLine("        mFrame = frame;")
        sb.appendLine("        ")
        sb.appendLine("        // 将自己作为 Runnable 发送到主线程")
        sb.appendLine("        Message msg = Message.obtain(mHandler, this);")
        sb.appendLine("        msg.setAsynchronous(true);  // 异步消息")
        sb.appendLine("        mHandler.sendMessageAtFrontOfQueue(msg);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void run() {")
        sb.appendLine("        // 在主线程执行帧处理")
        sb.appendLine("        doFrame(mTimestampNanos, mFrame);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【scheduleVsync】")
        sb.appendLine("```java")
        sb.appendLine("// 请求 VSync 信号")
        sb.appendLine("private void scheduleVsyncLocked() {")
        sb.appendLine("    mDisplayEventReceiver.scheduleVsync();")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("// DisplayEventReceiver.native 方法")
        sb.appendLine("public void scheduleVsync() {")
        sb.appendLine("    if (mReceiverPtr == 0) {")
        sb.appendLine("        return;")
        sb.appendLine("    }")
        sb.appendLine("    nativeScheduleVsync(mReceiverPtr);")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【VSync 流程图】")
        sb.appendLine("```\n")
        sb.appendLine("scheduleTraversals()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("Choreographer.postCallback(CALLBACK_TRAVERSAL)")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("scheduleVsyncLocked()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("nativeScheduleVsync() → 请求 VSync")
        sb.appendLine("       │")
        sb.appendLine("       ↓ (等待 VSync)")
        sb.appendLine("onVsync(timestampNanos)")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("Message.setAsynchronous(true)")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("doFrame(timestampNanos)")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("doCallbacks(CALLBACK_TRAVERSAL)")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("performTraversals()")
        sb.appendLine("```\n")
        
        sb.appendLine("【双重缓冲 vs 三重缓冲】")
        sb.appendLine("```\n")
        sb.appendLine("双重缓冲：")
        sb.appendLine("  - 前缓冲：正在显示")
        sb.appendLine("  - 后缓冲：正在绘制")
        sb.appendLine("  - GPU 绘制完成后等待 VSync 交换")
        sb.appendLine("")
        sb.appendLine("三重缓冲：")
        sb.appendLine("  - 前缓冲：正在显示")
        sb.appendLine("  - 后缓冲：等待显示")
        sb.appendLine("  - 第三缓冲：正在绘制")
        sb.appendLine("  - 可以让 GPU 不用等待，继续绘制下一帧")
        sb.appendLine("  - 代价是多一帧延迟")
        sb.appendLine("```\n")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * CallbackQueue 详解
     */
    private fun showCallbackQueue() {
        sb.clear()
        sb.appendLine("=== CallbackQueue 详解 ===\n")
        
        sb.appendLine("【CallbackQueue 结构】")
        sb.appendLine("```java")
        sb.appendLine("// Choreographer 内部类")
        sb.appendLine("private final class CallbackQueue {")
        sb.appendLine("    private CallbackRecord mHead;  // 链表头")
        sb.appendLine("    ")
        sb.appendLine("    // 添加回调")
        sb.appendLine("    public void addCallback(long dueTime, Runnable action, Object token) {")
        sb.appendLine("        CallbackRecord record = obtainCallbackLocked(dueTime, action, token);")
        sb.appendLine("        CallbackRecord[] callbacks = mCallbacks;")
        sb.appendLine("        // 按时间排序插入链表")
        sb.appendLine("        // ...")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 提取到期回调")
        sb.appendLine("    public CallbackRecord extractDueCallbacksLocked(long now) {")
        sb.appendLine("        // 返回所有到期的回调")
        sb.appendLine("        // ...")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【CallbackRecord】")
        sb.appendLine("```java")
        sb.appendLine("// 回调记录")
        sb.appendLine("private static final class CallbackRecord {")
        sb.appendLine("    public CallbackRecord next;      // 下一个")
        sb.appendLine("    public long dueTime;             // 到期时间")
        sb.appendLine("    public Object action;            // Runnable 或 FrameCallback")
        sb.appendLine("    public Object token;             // Token")
        sb.appendLine("    ")
        sb.appendLine("    public void run(long frameTimeNanos) {")
        sb.appendLine("        if (action instanceof Runnable) {")
        sb.appendLine("            ((Runnable) action).run();")
        sb.appendLine("        } else if (action instanceof FrameCallback) {")
        sb.appendLine("            ((FrameCallback) action).doFrame(frameTimeNanos);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【回调队列数组】")
        sb.appendLine("```java")
        sb.appendLine("// Choreographer 持有多个队列")
        sb.appendLine("private final CallbackQueue[] mCallbackQueues;")
        sb.appendLine("")
        sb.appendLine("// 初始化")
        sb.appendLine("mCallbackQueues = new CallbackQueue[CALLBACK_LAST + 1];")
        sb.appendLine("for (int i = 0; i <= CALLBACK_LAST; i++) {")
        sb.appendLine("    mCallbackQueues[i] = new CallbackQueue();")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【队列结构图】")
        sb.appendLine("```\n")
        sb.appendLine("mCallbackQueues[]")
        sb.appendLine("     │")
        sb.appendLine("     ├── [0] CALLBACK_INPUT")
        sb.appendLine("     │        │")
        sb.appendLine("     │        ↓")
        sb.appendLine("     │    CallbackRecord → CallbackRecord → ...")
        sb.appendLine("     │")
        sb.appendLine("     ├── [1] CALLBACK_ANIMATION")
        sb.appendLine("     │        │")
        sb.appendLine("     │        ↓")
        sb.appendLine("     │    CallbackRecord → CallbackRecord → ...")
        sb.appendLine("     │")
        sb.appendLine("     ├── [2] CALLBACK_INSETS_ANIMATION")
        sb.appendLine("     │")
        sb.appendLine("     ├── [3] CALLBACK_TRAVERSAL")
        sb.appendLine("     │        │")
        sb.appendLine("     │        ↓")
        sb.appendLine("     │    CallbackRecord (performTraversals)")
        sb.appendLine("     │")
        sb.appendLine("     └── [4] CALLBACK_COMMIT")
        sb.appendLine("```\n")
        
        sb.appendLine("【doCallbacks】")
        sb.appendLine("```java")
        sb.appendLine("void doCallbacks(int callbackType, long frameTimeNanos) {")
        sb.appendLine("    CallbackRecord callbacks;")
        sb.appendLine("    ")
        sb.appendLine("    synchronized (mLock) {")
        sb.appendLine("        // 获取到期的回调")
        sb.appendLine("        final long now = System.nanoTime();")
        sb.appendLine("        callbacks = mCallbackQueues[callbackType]")
        sb.appendLine("            .extractDueCallbacksLocked(now);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 执行回调")
        sb.appendLine("    try {")
        sb.appendLine("        for (CallbackRecord c = callbacks; c != null; c = c.next) {")
        sb.appendLine("            c.run(frameTimeNanos);")
        sb.appendLine("        }")
        sb.appendLine("    } finally {")
        sb.appendLine("        // 回收回调")
        sb.appendLine("        synchronized (mLock) {")
        sb.appendLine("            do {")
        sb.appendLine("                final CallbackRecord next = callbacks.next;")
        sb.appendLine("                recycleCallbackLocked(callbacks);")
        sb.appendLine("                callbacks = next;")
        sb.appendLine("            } while (callbacks != null);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * FrameCallback 详解
     */
    private fun showFrameCallback() {
        sb.clear()
        sb.appendLine("=== FrameCallback 详解 ===\n")
        
        sb.appendLine("【FrameCallback 接口】")
        sb.appendLine("```java")
        sb.appendLine("public interface FrameCallback {")
        sb.appendLine("    /**")
        sb.appendLine("     * 当 VSync 信号到来时调用")
        sb.appendLine("     * @param frameTimeNanos 帧开始时间（纳秒）")
        sb.appendLine("     */")
        sb.appendLine("    public void doFrame(long frameTimeNanos);")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【使用示例】")
        sb.appendLine("```java")
        sb.appendLine("// 注册 FrameCallback")
        sb.appendLine("Choreographer.getInstance().postFrameCallback(new Choreographer.FrameCallback() {")
        sb.appendLine("    @Override")
        sb.appendLine("    public void doFrame(long frameTimeNanos) {")
        sb.appendLine("        // 在 VSync 信号到来时执行")
        sb.appendLine("        // frameTimeNanos 是帧开始时间")
        sb.appendLine("        ")
        sb.appendLine("        // 如果需要持续监听，需要重新注册")
        sb.appendLine("        Choreographer.getInstance().postFrameCallback(this);")
        sb.appendLine("    }")
        sb.appendLine("});")
        sb.appendLine("```\n")
        
        sb.appendLine("【延迟注册】")
        sb.appendLine("```java")
        sb.appendLine("// 延迟一帧后注册")
        sb.appendLine("public void postFrameCallbackDelayed(FrameCallback callback, long delayMillis) {")
        sb.appendLine("    if (callback == null) {")
        sb.appendLine("        throw new IllegalArgumentException(\"callback must not be null\");")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 转换为纳秒")
        sb.appendLine("    final long dueTime = SystemClock.uptimeMillis() + delayMillis;")
        sb.appendLine("    postCallbackDelayedInternal(CALLBACK_ANIMATION, callback, null, dueTime);")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【计算帧时间】")
        sb.appendLine("```java")
        sb.appendLine("// 计算与上一帧的时间差")
        sb.appendLine("long frameIntervalNanos = frameTimeNanos - mLastFrameTimeNanos;")
        sb.appendLine("")
        sb.appendLine("// 标准帧间隔（60fps = 16.67ms）")
        sb.appendLine("long standardFrameInterval = (long)(1000000000 / 60);  // 约 16.67ms")
        sb.appendLine("")
        sb.appendLine("// 判断是否掉帧")
        sb.appendLine("if (frameIntervalNanos > standardFrameInterval * 2) {")
        sb.appendLine("    // 掉帧了")
        sb.appendLine("    int skippedFrames = (int)(frameIntervalNanos / standardFrameInterval);")
        sb.appendLine("    Log.d(\"Jank\", \"Skipped \" + skippedFrames + \" frames!\");")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【实用示例：帧率监控】")
        sb.appendLine("```java")
        sb.appendLine("public class FrameRateMonitor implements Choreographer.FrameCallback {")
        sb.appendLine("    private long mLastFrameTimeNanos = 0;")
        sb.appendLine("    private int mFrameCount = 0;")
        sb.appendLine("    private long mStartTimeNanos = 0;")
        sb.appendLine("    ")
        sb.appendLine("    public void start() {")
        sb.appendLine("        mStartTimeNanos = System.nanoTime();")
        sb.appendLine("        Choreographer.getInstance().postFrameCallback(this);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    public void stop() {")
        sb.appendLine("        Choreographer.getInstance().removeFrameCallback(this);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void doFrame(long frameTimeNanos) {")
        sb.appendLine("        mFrameCount++;")
        sb.appendLine("        ")
        sb.appendLine("        // 每秒计算一次 FPS")
        sb.appendLine("        long elapsedNanos = frameTimeNanos - mStartTimeNanos;")
        sb.appendLine("        if (elapsedNanos >= 1000000000L) {  // 1 秒")
        sb.appendLine("            float fps = mFrameCount * 1000000000f / elapsedNanos;")
        sb.appendLine("            Log.d(\"FPS\", String.format(\"FPS: %.1f\", fps));")
        sb.appendLine("            mFrameCount = 0;")
        sb.appendLine("            mStartTimeNanos = frameTimeNanos;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        // 掉帧检测")
        sb.appendLine("        if (mLastFrameTimeNanos != 0) {")
        sb.appendLine("            long frameInterval = frameTimeNanos - mLastFrameTimeNanos;")
        sb.appendLine("            if (frameInterval > 16666666L * 2) {  // 超过 2 帧")
        sb.appendLine("                int skipped = (int)(frameInterval / 16666666L);")
        sb.appendLine("                Log.w(\"Jank\", \"Skipped \" + skipped + \" frames\");")
        sb.appendLine("            }")
        sb.appendLine("        }")
        sb.appendLine("        mLastFrameTimeNanos = frameTimeNanos;")
        sb.appendLine("        ")
        sb.appendLine("        // 继续监听下一帧")
        sb.appendLine("        Choreographer.getInstance().postFrameCallback(this);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【注意事项】")
        sb.appendLine("1. doFrame 在主线程执行")
        sb.appendLine("2. 不要在 doFrame 中执行耗时操作")
        sb.appendLine("3. 需要持续监听要重新注册")
        sb.appendLine("4. 使用 removeFrameCallback 取消注册")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * 帧时间线详解
     */
    private fun showFrameTimeline() {
        sb.clear()
        sb.appendLine("=== 帧时间线详解 ===\n")
        
        sb.appendLine("【doFrame 方法】")
        sb.appendLine("```java")
        sb.appendLine("void doFrame(long frameTimeNanos, int frame) {")
        sb.appendLine("    final long startNanos;")
        sb.appendLine("    synchronized (mLock) {")
        sb.appendLine("        // ...")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    try {")
        sb.appendLine("        // 1. 处理输入事件")
        sb.appendLine("        doCallbacks(Choreographer.CALLBACK_INPUT, frameTimeNanos);")
        sb.appendLine("        ")
        sb.appendLine("        // 2. 处理动画")
        sb.appendLine("        doCallbacks(Choreographer.CALLBACK_ANIMATION, frameTimeNanos);")
        sb.appendLine("        ")
        sb.appendLine("        // 3. 处理插入动画")
        sb.appendLine("        doCallbacks(Choreographer.CALLBACK_INSETS_ANIMATION, frameTimeNanos);")
        sb.appendLine("        ")
        sb.appendLine("        // 4. 处理遍历（测量、布局、绘制）")
        sb.appendLine("        doCallbacks(Choreographer.CALLBACK_TRAVERSAL, frameTimeNanos);")
        sb.appendLine("        ")
        sb.appendLine("        // 5. 处理提交")
        sb.appendLine("        doCallbacks(Choreographer.CALLBACK_COMMIT, frameTimeNanos);")
        sb.appendLine("    } finally {")
        sb.appendLine("        // ...")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【帧时间线】")
        sb.appendLine("```\n")
        sb.appendLine("    VSync N")
        sb.appendLine("       │")
        sb.appendLine("       │  ← frameTimeNanos（VSync 时间戳）")
        sb.appendLine("       ↓")
        sb.appendLine("┌──────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                          Frame N                             │\n")
        sb.appendLine("│                                                              │\n")
        sb.appendLine("│  ┌─────────────┐ ┌─────────────┐ ┌─────────────┐            │\n")
        sb.appendLine("│  │   INPUT     │ │  ANIMATION  │ │  TRAVERSAL  │            │\n")
        sb.appendLine("│  │  输入事件   │ │    动画     │ │  测量/布局  │            │\n")
        sb.appendLine("│  └─────────────┘ └─────────────┘ │    绘制     │            │\n")
        sb.appendLine("│                                  └─────────────┘            │\n")
        sb.appendLine("│                                                              │\n")
        sb.appendLine("│                         ↓ 交付 Surface                      │\n")
        sb.appendLine("└──────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("       │")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("    VSync N+1 ← 显示 Frame N")
        sb.appendLine("```\n")
        
        sb.appendLine("【时间计算】")
        sb.appendLine("```java")
        sb.appendLine("// 计算帧间隔")
        sb.appendLine("long frameIntervalNanos = frameTimeNanos - mLastFrameTimeNanos;")
        sb.appendLine("")
        sb.appendLine("// 标准帧间隔")
        sb.appendLine("// 60Hz: 16,666,667 ns (约 16.67ms)")
        sb.appendLine("// 90Hz: 11,111,111 ns (约 11.11ms)")
        sb.appendLine("// 120Hz: 8,333,333 ns (约 8.33ms)")
        sb.appendLine("")
        sb.appendLine("// 计算预期帧时间")
        sb.appendLine("long intendedFrameTimeNanos = startNanos + (frameIntervalNanos);")
        sb.appendLine("")
        sb.appendLine("// 计算抖动（jitter）")
        sb.appendLine("long jitterNanos = frameTimeNanos - intendedFrameTimeNanos;")
        sb.appendLine("if (jitterNanos >= mFrameIntervalNanos) {")
        sb.appendLine("    // 帧时间抖动超过一帧，可能掉帧")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【掉帧检测】")
        sb.appendLine("```java")
        sb.appendLine("// 计算掉帧数")
        sb.appendLine("long jitterNanos = frameTimeNanos - intendedFrameTimeNanos;")
        sb.appendLine("if (jitterNanos >= mFrameIntervalNanos) {")
        sb.appendLine("    final long skippedFrames = jitterNanos / mFrameIntervalNanos;")
        sb.appendLine("    if (skippedFrames >= SKIPPED_FRAME_WARNING_LIMIT) {")
        sb.appendLine("        Log.i(TAG, \"Skipped \" + skippedFrames + \" frames!  \"")
        sb.appendLine("                + \"The application may be doing too much work \"")
        sb.appendLine("                + \"on its main thread.\");")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【帧时间可视化】")
        sb.appendLine("```\n")
        sb.appendLine("正常帧（60fps）：")
        sb.appendLine("VSync    VSync    VSync    VSync")
        sb.appendLine("  │        │        │        │")
        sb.appendLine("  ↓        ↓        ↓        ↓")
        sb.appendLine(" [Frame1] [Frame2] [Frame3] [Frame4]")
        sb.appendLine("  16ms     16ms     16ms     16ms")
        sb.appendLine("")
        sb.appendLine("掉帧情况：")
        sb.appendLine("VSync    VSync    VSync    VSync")
        sb.appendLine("  │        │        │        │")
        sb.appendLine("  ↓        ↓        ↓        ↓")
        sb.appendLine(" [Frame1] [  跳过  ] [Frame3] [Frame4]")
        sb.appendLine("  16ms        33ms      16ms")
        sb.appendLine("              ↑")
        sb.appendLine("           掉帧")
        sb.appendLine("```\n")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * ViewRootImpl 与 Choreographer 的关系
     */
    private fun showViewRootRelation() {
        sb.clear()
        sb.appendLine("=== ViewRootImpl 与 Choreographer 的关系 ===\n")
        
        sb.appendLine("【ViewRootImpl 初始化 Choreographer】")
        sb.appendLine("```java")
        sb.appendLine("public ViewRootImpl(Context context, Display display) {")
        sb.appendLine("    // ...")
        sb.appendLine("    mChoreographer = Choreographer.getInstance();")
        sb.appendLine("    // ...")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【scheduleTraversals 调用链】")
        sb.appendLine("```java")
        sb.appendLine("// ViewRootImpl.scheduleTraversals()")
        sb.appendLine("void scheduleTraversals() {")
        sb.appendLine("    if (!mTraversalScheduled) {")
        sb.appendLine("        mTraversalScheduled = true;")
        sb.appendLine("        ")
        sb.appendLine("        // 1. 发送同步屏障")
        sb.appendLine("        mTraversalBarrier = mHandler.getLooper().getQueue().postSyncBarrier();")
        sb.appendLine("        ")
        sb.appendLine("        // 2. 注册 Traversal 回调到 Choreographer")
        sb.appendLine("        mChoreographer.postCallback(")
        sb.appendLine("                Choreographer.CALLBACK_TRAVERSAL,")
        sb.appendLine("                mTraversalRunnable, null);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【TraversalRunnable】")
        sb.appendLine("```java")
        sb.appendLine("final class TraversalRunnable implements Runnable {")
        sb.appendLine("    @Override")
        sb.appendLine("    public void run() {")
        sb.appendLine("        doTraversal();")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("final TraversalRunnable mTraversalRunnable = new TraversalRunnable();")
        sb.appendLine("```\n")
        
        sb.appendLine("【doTraversal】")
        sb.appendLine("```java")
        sb.appendLine("void doTraversal() {")
        sb.appendLine("    if (mTraversalScheduled) {")
        sb.appendLine("        mTraversalScheduled = false;")
        sb.appendLine("        ")
        sb.appendLine("        // 1. 移除同步屏障")
        sb.appendLine("        mHandler.getLooper().getQueue().removeSyncBarrier(mTraversalBarrier);")
        sb.appendLine("        ")
        sb.appendLine("        // 2. 执行遍历")
        sb.appendLine("        performTraversals();")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【完整流程图】")
        sb.appendLine("```\n")
        sb.appendLine("View.requestLayout() / View.invalidate()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("ViewRootImpl.requestLayout()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("ViewRootImpl.scheduleTraversals()")
        sb.appendLine("           │")
        sb.appendLine("           ├─→ postSyncBarrier()")
        sb.appendLine("           │")
        sb.appendLine("           └─→ mChoreographer.postCallback(CALLBACK_TRAVERSAL)")
        sb.appendLine("                      │")
        sb.appendLine("                      ↓")
        sb.appendLine("              scheduleVsyncLocked()")
        sb.appendLine("                      │")
        sb.appendLine("                      ↓")
        sb.appendLine("                 nativeScheduleVsync()")
        sb.appendLine("                      │")
        sb.appendLine("                      ↓ (等待 VSync)")
        sb.appendLine("                onVsync()")
        sb.appendLine("                      │")
        sb.appendLine("                      ↓")
        sb.appendLine("                doFrame()")
        sb.appendLine("                      │")
        sb.appendLine("                      ↓")
        sb.appendLine("                doCallbacks(CALLBACK_TRAVERSAL)")
        sb.appendLine("                      │")
        sb.appendLine("                      ↓")
        sb.appendLine("           mTraversalRunnable.run()")
        sb.appendLine("                      │")
        sb.appendLine("                      ↓")
        sb.appendLine("           ViewRootImpl.doTraversal()")
        sb.appendLine("                      │")
        sb.appendLine("                      ↓")
        sb.appendLine("           ViewRootImpl.performTraversals()")
        sb.appendLine("                      │")
        sb.appendLine("        ┌─────────────┼─────────────┐")
        sb.appendLine("        ↓             ↓             ↓")
        sb.appendLine("    performMeasure  performLayout  performDraw")
        sb.appendLine("```\n")
        
        sb.appendLine("【同步屏障的作用】")
        sb.appendLine("```java")
        sb.appendLine("// 为什么需要同步屏障？")
        sb.appendLine("// ")
        sb.appendLine("// 主线程 MessageQueue 可能有大量同步消息")
        sb.appendLine("// 如果不使用同步屏障，VSync 到来时可能还在处理其他消息")
        sb.appendLine("// ")
        sb.appendLine("// 同步屏障确保：")
        sb.appendLine("// 1. VSync 信号到来时，优先执行 Traversal")
        sb.appendLine("// 2. Traversal 是异步消息，可以跳过同步屏障")
        sb.appendLine("// 3. 保证 UI 渲染的及时性")
        sb.appendLine("```")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * 性能优化
     */
    private fun showPerformance() {
        sb.clear()
        sb.appendLine("=== 性能优化 ===\n")
        
        sb.appendLine("【掉帧原因】")
        sb.appendLine("```\n")
        sb.appendLine("1. 主线程执行耗时操作")
        sb.appendLine("   - 复杂计算")
        sb.appendLine("   - 文件 I/O")
        sb.appendLine("   - 网络 I/O")
        sb.appendLine("   - 数据库操作")
        sb.appendLine("")
        sb.appendLine("2. View 层级过深")
        sb.appendLine("   - 测量、布局、绘制耗时")
        sb.appendLine("")
        sb.appendLine("3. 过度绘制")
        sb.appendLine("   - 同一像素多次绘制")
        sb.appendLine("")
        sb.appendLine("4. 频繁 requestLayout")
        sb.appendLine("   - 触发完整的测量布局")
        sb.appendLine("```\n")
        
        sb.appendLine("【性能监控方法】")
        sb.appendLine("```java")
        sb.appendLine("// 1. 使用 FrameCallback 监控帧率")
        sb.appendLine("Choreographer.getInstance().postFrameCallback(frameCallback);")
        sb.appendLine("")
        sb.appendLine("// 2. 使用 OnFrameMetricsAvailableListener (API 24+)")
        sb.appendLine("getWindow().addOnFrameMetricsAvailableListener(listener, handler);")
        sb.appendLine("")
        sb.appendLine("// 3. 使用 StrictMode")
        sb.appendLine("StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()")
        sb.appendLine("    .detectDiskReads()")
        sb.appendLine("    .detectDiskWrites()")
        sb.appendLine("    .detectNetwork()")
        sb.appendLine("    .penaltyLog()")
        sb.appendLine("    .build());")
        sb.appendLine("```\n")
        
        sb.appendLine("【FrameMetrics 使用】")
        sb.appendLine("```java")
        sb.appendLine("private void setupFrameMetrics() {")
        sb.appendLine("    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {")
        sb.appendLine("        Window.OnFrameMetricsAvailableListener listener = ")
        sb.appendLine("            new Window.OnFrameMetricsAvailableListener() {")
        sb.appendLine("            @Override")
        sb.appendLine("            public void onFrameMetricsAvailable(Window window,")
        sb.appendLine("                    FrameMetrics frameMetrics, int dropCountSinceLastInvocation) {")
        sb.appendLine("                ")
        sb.appendLine("                // 获取各种时间")
        sb.appendLine("                long totalDuration = frameMetrics.getMetric(")
        sb.appendLine("                        FrameMetrics.TOTAL_DURATION);")
        sb.appendLine("                long inputDuration = frameMetrics.getMetric(")
        sb.appendLine("                        FrameMetrics.INPUT_HANDLING_DURATION);")
        sb.appendLine("                long layoutDuration = frameMetrics.getMetric(")
        sb.appendLine("                        FrameMetrics.LAYOUT_MEASURE_DURATION);")
        sb.appendLine("                long drawDuration = frameMetrics.getMetric(")
        sb.appendLine("                        FrameMetrics.DRAW_DURATION);")
        sb.appendLine("                long syncDuration = frameMetrics.getMetric(")
        sb.appendLine("                        FrameMetrics.SYNC_DURATION);")
        sb.appendLine("                long swapDuration = frameMetrics.getMetric(")
        sb.appendLine("                        FrameMetrics.SWAP_BUFFERS_DURATION);")
        sb.appendLine("                ")
        sb.appendLine("                Log.d(\"FrameMetrics\", String.format(")
        sb.appendLine("                    \"Total: %dms, Input: %dms, Layout: %dms, Draw: %dms\",")
        sb.appendLine("                    totalDuration / 1000000,")
        sb.appendLine("                    inputDuration / 1000000,")
        sb.appendLine("                    layoutDuration / 1000000,")
        sb.appendLine("                    drawDuration / 1000000));")
        sb.appendLine("            }")
        sb.appendLine("        };")
        sb.appendLine("        ")
        sb.appendLine("        getWindow().addOnFrameMetricsAvailableListener(listener, mHandler);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【FrameMetrics 指标】")
        sb.appendLine("```\n")
        sb.appendLine("FrameMetrics 常量：")
        sb.appendLine("- TOTAL_DURATION          帧总时间")
        sb.appendLine("- INPUT_HANDLING_DURATION 输入处理时间")
        sb.appendLine("- LAYOUT_MEASURE_DURATION 测量布局时间")
        sb.appendLine("- DRAW_DURATION           绘制时间")
        sb.appendLine("- SYNC_DURATION           GPU 同步时间")
        sb.appendLine("- SWAP_BUFFERS_DURATION   交换缓冲时间")
        sb.appendLine("- COMMAND_ISSUE_DURATION  GPU 命令时间")
        sb.appendLine("- UNKNOWN_DELAY_DURATION  未知延迟")
        sb.appendLine("```\n")
        
        sb.appendLine("【优化建议】")
        sb.appendLine("```\n")
        sb.appendLine("1. 减少主线程工作量")
        sb.appendLine("   - 使用后台线程处理耗时操作")
        sb.appendLine("   - 使用异步任务")
        sb.appendLine("")
        sb.appendLine("2. 优化 View 层级")
        sb.appendLine("   - 使用 ConstraintLayout 扁平化布局")
        sb.appendLine("   - 使用 ViewStub 延迟加载")
        sb.appendLine("   - 使用 merge 标签")
        sb.appendLine("")
        sb.appendLine("3. 减少过度绘制")
        sb.appendLine("   - 移除不必要的背景")
        sb.appendLine("   - 使用 clipPath 裁剪")
        sb.appendLine("")
        sb.appendLine("4. 避免频繁 requestLayout")
        sb.appendLine("   - 使用 invalidate 代替（如果尺寸不变）")
        sb.appendLine("   - 批量更新 View 属性")
        sb.appendLine("```")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * Choreographer 实践演示
     */
    private fun demonstrateChoreographer() {
        sb.clear()
        sb.appendLine("=== Choreographer 实践演示 ===\n")
        
        sb.appendLine("【演示：使用 FrameCallback 监控帧率】\n")
        
        // 创建帧率监控器
        val frameCallback = object : Choreographer.FrameCallback {
            private var lastFrameTimeNanos = 0L
            private var frameCount = 0
            private var startTimeNanos = 0L
            
            override fun doFrame(frameTimeNanos: Long) {
                if (startTimeNanos == 0L) {
                    startTimeNanos = frameTimeNanos
                }
                
                frameCount++
                
                // 计算帧间隔
                if (lastFrameTimeNanos != 0L) {
                    val frameInterval = (frameTimeNanos - lastFrameTimeNanos) / 1_000_000
                    sb.appendLine("帧间隔: ${frameInterval}ms")
                    
                    // 检测掉帧
                    if (frameInterval > 33) {  // 超过 2 帧
                        sb.appendLine("  ⚠️ 可能掉帧!")
                    }
                }
                
                // 每秒计算一次 FPS
                val elapsed = frameTimeNanos - startTimeNanos
                if (elapsed >= 1_000_000_000L) {
                    val fps = frameCount * 1_000_000_000f / elapsed
                    sb.appendLine("\n=== FPS: ${"%.1f".format(fps)} ===\n")
                    frameCount = 0
                    startTimeNanos = frameTimeNanos
                }
                
                lastFrameTimeNanos = frameTimeNanos
                
                // 继续监听
                if (frameCount < 100) {  // 限制监听帧数
                    Choreographer.getInstance().postFrameCallback(this)
                }
                
                binding.tvContent.text = sb.toString()
            }
        }
        
        sb.appendLine("开始监听帧率...\n")
        
        // 开始监听
        Choreographer.getInstance().postFrameCallback(frameCallback)
        
        binding.tvContent.text = sb.toString()
    }

    override fun onSupportNavigateUp(): Boolean {
        onBackPressedDispatcher.onBackPressed()
        return true
    }
}
