package com.peter.window.demo.viewroot.deep

import android.os.Bundle
import android.view.MotionEvent
import androidx.appcompat.app.AppCompatActivity
import com.peter.window.demo.databinding.ActivityInputEventDispatchBinding

/**
 * 深入篇：输入事件分发机制
 * 
 * ViewRootImpl 是输入事件分发的入口点，
 * 它接收来自系统 InputManager 的事件，
 * 并分发到 View 树。
 * 
 * 事件流：
 * InputManagerService → InputEventReceiver → ViewRootImpl → View
 */
class InputEventDispatchActivity : AppCompatActivity() {

    private lateinit var binding: ActivityInputEventDispatchBinding
    private val sb = StringBuilder()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityInputEventDispatchBinding.inflate(layoutInflater)
        setContentView(binding.root)
        supportActionBar?.setDisplayHomeAsUpEnabled(true)

        setupListeners()
        showInputEventOverview()
    }

    private fun setupListeners() {
        binding.btnOverview.setOnClickListener { showInputEventOverview() }
        binding.btnInputReceiver.setOnClickListener { showInputEventReceiver() }
        binding.btnEnqueueEvent.setOnClickListener { showEnqueueInputEvent() }
        binding.btnDeliverEvent.setOnClickListener { showDeliverInputEvent() }
        binding.btnTouchEvent.setOnClickListener { showTouchEventDispatch() }
        binding.btnKeyEvent.setOnClickListener { showKeyEventDispatch() }
        binding.btnInputStage.setOnClickListener { showInputStage() }
        binding.btnUnhandledEvent.setOnClickListener { showUnhandledEvent() }
    }

    /**
     * 输入事件分发概述
     */
    private fun showInputEventOverview() {
        sb.clear()
        sb.appendLine("=== 输入事件分发概述 ===\n")
        
        sb.appendLine("【整体架构】")
        sb.appendLine("```\n")
        sb.appendLine("┌────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                    系统进程                                │\n")
        sb.appendLine("│                                                            │\n")
        sb.appendLine("│  InputManagerService                                       │\n")
        sb.appendLine("│       │                                                    │\n")
        sb.appendLine("│       ↓ (读取设备事件)                                     │\n")
        sb.appendLine("│  EventHub                                                 │\n")
        sb.appendLine("│       │                                                    │\n")
        sb.appendLine("│       ↓ (发送给目标窗口)                                   │\n")
        sb.appendLine("│  InputDispatcher                                           │\n")
        sb.appendLine("│       │                                                    │\n")
        sb.appendLine("└───────│────────────────────────────────────────────────────┘\n")
        sb.appendLine("        │ (Binder IPC + 共享内存)")
        sb.appendLine("        ↓")
        sb.appendLine("┌────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                    应用进程                                │\n")
        sb.appendLine("│                                                            │\n")
        sb.appendLine("│  InputEventReceiver                                        │\n")
        sb.appendLine("│       │                                                    │\n")
        sb.appendLine("│       ↓                                                    │\n")
        sb.appendLine("│  ViewRootImpl                                              │\n")
        sb.appendLine("│       │                                                    │\n")
        sb.appendLine("│       ├─→ deliverInputEvent()                              │\n")
        sb.appendLine("│       │         │                                          │\n")
        sb.appendLine("│       │         ↓                                          │\n")
        sb.appendLine("│       │    InputStage (责任链)                             │\n")
        sb.appendLine("│       │         │                                          │\n")
        sb.appendLine("│       │         ↓                                          │\n")
        sb.appendLine("│       └─→ mView.dispatchTouchEvent()                      │\n")
        sb.appendLine("│                                                            │\n")
        sb.appendLine("└────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")
        
        sb.appendLine("【事件类型】")
        sb.appendLine("```java")
        sb.appendLine("// KeyEvent - 键盘事件")
        sb.appendLine("public class KeyEvent extends InputEvent {")
        sb.appendLine("    int keyCode;    // 按键码")
        sb.appendLine("    int action;     // ACTION_DOWN, ACTION_UP, ACTION_MULTIPLE")
        sb.appendLine("    int repeatCount;")
        sb.appendLine("    int metaState;  // 修饰键状态")
        sb.appendLine("}")
        sb.appendLine("")
        sb.appendLine("// MotionEvent - 触摸/鼠标事件")
        sb.appendLine("public class MotionEvent extends InputEvent {")
        sb.appendLine("    int action;         // ACTION_DOWN, MOVE, UP, CANCEL...")
        sb.appendLine("    float x, y;         // 坐标")
        sb.appendLine("    int pointerCount;   // 触摸点数量")
        sb.appendLine("    long eventTime;     // 事件时间")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【核心流程】")
        sb.appendLine("```\n")
        sb.appendLine("1. InputDispatcher 发送事件到目标窗口")
        sb.appendLine("   ↓")
        sb.appendLine("2. InputEventReceiver 接收事件")
        sb.appendLine("   ↓")
        sb.appendLine("3. ViewRootImpl.enqueueInputEvent()")
        sb.appendLine("   ↓")
        sb.appendLine("4. ViewRootImpl.deliverInputEvent()")
        sb.appendLine("   ↓")
        sb.appendLine("5. InputStage 责任链处理")
        sb.appendLine("   ↓")
        sb.appendLine("6. View.dispatchTouchEvent()")
        sb.appendLine("```")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * InputEventReceiver 详解
     */
    private fun showInputEventReceiver() {
        sb.clear()
        sb.appendLine("=== InputEventReceiver ===\n")
        
        sb.appendLine("【WindowInputEventReceiver】")
        sb.appendLine("ViewRootImpl 内部类，用于接收输入事件\n")
        
        sb.appendLine("```java")
        sb.appendLine("final class WindowInputEventReceiver extends InputEventReceiver {")
        sb.appendLine("    public WindowInputEventReceiver(InputChannel inputChannel,")
        sb.appendLine("            Looper looper) {")
        sb.appendLine("        super(inputChannel, looper);")
        sb.appendLine("    }")
        sb.appendLine("")
        sb.appendLine("    @Override")
        sb.appendLine("    public void onInputEvent(InputEvent event) {")
        sb.appendLine("        // 接收到输入事件")
        sb.appendLine("        List<InputEvent> pendingEvents = mPendingEvents;")
        sb.appendLine("        pendingEvents.add(event);")
        sb.appendLine("        ")
        sb.appendLine("        // 如果处理完了上一个事件")
        sb.appendLine("        if (pendingEvents.size() == 1) {")
        sb.appendLine("            // 入队处理")
        sb.appendLine("            enqueueInputEvent(event, this, 0, true);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("")
        sb.appendLine("    @Override")
        sb.appendLine("    public void onBatchedInputEventPending() {")
        sb.appendLine("        // 批量事件待处理")
        sb.appendLine("        if (mUnbatchedInputAvailable) {")
        sb.appendLine("            // 立即调度处理")
        sb.appendLine("            scheduleConsumeBatchedInput();")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【InputChannel 创建】")
        sb.appendLine("```java")
        sb.appendLine("// 在 WMS.addWindow 时创建 InputChannel 对")
        sb.appendLine("public int addWindow(Session session, IWindow client, ...) {")
        sb.appendLine("    // 创建 InputChannel 对")
        sb.appendLine("    InputChannel[] inputChannels = InputChannel.openInputChannelPair(name);")
        sb.appendLine("    ")
        sb.appendLine("    // 服务端通道注册到 InputManagerService")
        sb.appendLine("    win.setInputChannel(inputChannels[0]);")
        sb.appendLine("    inputChannels[0].dispose();")
        sb.appendLine("    ")
        sb.appendLine("    // 客户端通道返回给应用")
        sb.appendLine("    outInputChannel[0] = inputChannels[1];")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【InputChannel 通信模型】")
        sb.appendLine("```\n")
        sb.appendLine("┌─────────────────┐          ┌─────────────────┐\n")
        sb.appendLine("│  InputDispatcher │          │ ViewRootImpl    │\n")
        sb.appendLine("│  (系统进程)      │          │ (应用进程)      │\n")
        sb.appendLine("│                 │          │                 │\n")
        sb.appendLine("│  InputChannel   │←────────→│ InputChannel    │\n")
        sb.appendLine("│  (Server)       │  共享内存 │ (Client)        │\n")
        sb.appendLine("│                 │          │                 │\n")
        sb.appendLine("│  socketpair     │          │ InputEvent      │\n")
        sb.appendLine("│                 │          │ Receiver        │\n")
        sb.appendLine("└─────────────────┘          └─────────────────┘\n")
        sb.appendLine("```\n")
        
        sb.appendLine("【Native 层】")
        sb.appendLine("```cpp")
        sb.appendLine("// android_view_InputEventReceiver.cpp")
        sb.appendLine("void NativeInputEventReceiver::consumeEvents(JNIEnv* env) {")
        sb.appendLine("    while (true) {")
        sb.appendLine("        // 从 InputChannel 读取事件")
        sb.appendLine("        InputEvent* event = mInputConsumer.consume();")
        sb.appendLine("        ")
        sb.appendLine("        if (event) {")
        sb.appendLine("            // 调用 Java 的 onInputEvent")
        sb.appendLine("            env->CallVoidMethod(mReceiverObj, gInputEventReceiverClassInfo.onInputEvent);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * enqueueInputEvent 详解
     */
    private fun showEnqueueInputEvent() {
        sb.clear()
        sb.appendLine("=== enqueueInputEvent ===\n")
        
        sb.appendLine("【方法签名】")
        sb.appendLine("```java")
        sb.appendLine("void enqueueInputEvent(InputEvent event,")
        sb.appendLine("        InputEventReceiver receiver, int flags, boolean processImmediately) {")
        sb.appendLine("    // 1. 创建 QueuedInputEvent")
        sb.appendLine("    QueuedInputEvent q = obtainQueuedInputEvent(event, receiver, flags);")
        sb.appendLine("    ")
        sb.appendLine("    // 2. 添加到队列")
        sb.appendLine("    QueuedInputEvent last = mPendingInputEventTail;")
        sb.appendLine("    if (last == null) {")
        sb.appendLine("        mPendingInputEventHead = q;")
        sb.appendLine("        mPendingInputEventTail = q;")
        sb.appendLine("    } else {")
        sb.appendLine("        last.mNext = q;")
        sb.appendLine("        mPendingInputEventTail = q;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 3. 立即处理或稍后处理")
        sb.appendLine("    if (processImmediately) {")
        sb.appendLine("        doProcessInputEvents();")
        sb.appendLine("    } else {")
        sb.appendLine("        scheduleProcessInputEvents();")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【QueuedInputEvent】")
        sb.appendLine("```java")
        sb.appendLine("final class QueuedInputEvent {")
        sb.appendLine("    InputEvent mEvent;              // 原始事件")
        sb.appendLine("    InputEventReceiver mReceiver;   // 事件接收器")
        sb.appendLine("    int mFlags;                     // 标志")
        sb.appendLine("    QueuedInputEvent mNext;         // 链表下一个")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【doProcessInputEvents】")
        sb.appendLine("```java")
        sb.appendLine("void doProcessInputEvents() {")
        sb.appendLine("    // 遍历事件队列")
        sb.appendLine("    while (mPendingInputEventHead != null) {")
        sb.appendLine("        QueuedInputEvent q = mPendingInputEventHead;")
        sb.appendLine("        mPendingInputEventHead = q.mNext;")
        sb.appendLine("        ")
        sb.appendLine("        if (mPendingInputEventHead == null) {")
        sb.appendLine("            mPendingInputEventTail = null;")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        q.mFlags |= QueuedInputEvent.FLAG_DEFERRED;")
        sb.appendLine("        ")
        sb.appendLine("        // 分发事件")
        sb.appendLine("        deliverInputEvent(q);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【事件队列模型】")
        sb.appendLine("```\n")
        sb.appendLine("InputEventReceiver.onInputEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("   ┌─────────────────┐")
        sb.appendLine("   │ QueuedInputEvent│ ← 事件 1")
        sb.appendLine("   │      ↓          │")
        sb.appendLine("   │ QueuedInputEvent│ ← 事件 2")
        sb.appendLine("   │      ↓          │")
        sb.appendLine("   │ QueuedInputEvent│ ← 事件 3")
        sb.appendLine("   └─────────────────┘")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("   doProcessInputEvents()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("   deliverInputEvent()")
        sb.appendLine("```")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * deliverInputEvent 详解
     */
    private fun showDeliverInputEvent() {
        sb.clear()
        sb.appendLine("=== deliverInputEvent ===\n")
        
        sb.appendLine("【方法签名】")
        sb.appendLine("```java")
        sb.appendLine("private void deliverInputEvent(QueuedInputEvent q) {")
        sb.appendLine("    Trace.asyncTraceBegin(...);")
        sb.appendLine("    ")
        sb.appendLine("    // 设置输入事件一致性验证器")
        sb.appendLine("    if (mInputEventConsistencyVerifier != null) {")
        sb.appendLine("        mInputEventConsistencyVerifier.onInputEvent(q.mEvent, 0);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    InputStage stage;")
        sb.appendLine("    if (q.shouldSendToSynthesizer()) {")
        sb.appendLine("        stage = mSyntheticInputStage;")
        sb.appendLine("    } else {")
        sb.appendLine("        stage = q.shouldSkipIme() ? mFirstPostImeInputStage : mFirstInputStage;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 交给 InputStage 处理")
        sb.appendLine("    if (stage != null) {")
        sb.appendLine("        stage.deliver(q);")
        sb.appendLine("    } else {")
        sb.appendLine("        finishInputEvent(q);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【finishInputEvent】")
        sb.appendLine("```java")
        sb.appendLine("private void finishInputEvent(QueuedInputEvent q) {")
        sb.appendLine("    Trace.asyncTraceEnd(...);")
        sb.appendLine("    ")
        sb.appendLine("    if (q.mReceiver != null) {")
        sb.appendLine("        // 通知 InputDispatcher 事件已处理完")
        sb.appendLine("        q.mReceiver.finishInputEvent(q.mEvent);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 回收事件")
        sb.appendLine("    recycleQueuedInputEvent(q);")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【事件处理结果】")
        sb.appendLine("```java")
        sb.appendLine("// InputStage 处理结果")
        sb.appendLine("public static final int FORWARD = 0;   // 继续传递给下一个 Stage")
        sb.appendLine("public static final int FINISH_HANDLED = 1;  // 已处理，完成")
        sb.appendLine("public static final int FINISH_NOT_HANDLED = 2;  // 未处理，完成")
        sb.appendLine("```\n")
        
        sb.appendLine("【处理流程】")
        sb.appendLine("```\n")
        sb.appendLine("deliverInputEvent()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("InputStage.deliver()")
        sb.appendLine("       │")
        sb.appendLine("       ↓")
        sb.appendLine("onProcess() → 处理事件")
        sb.appendLine("       │")
        sb.appendLine("       ├─→ FORWARD: 传递给下一个 Stage")
        sb.appendLine("       │")
        sb.appendLine("       ├─→ FINISH_HANDLED: 调用 finishInputEvent()")
        sb.appendLine("       │")
        sb.appendLine("       └─→ FINISH_NOT_HANDLED: 调用 finishInputEvent()")
        sb.appendLine("```")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * 触摸事件分发详解
     */
    private fun showTouchEventDispatch() {
        sb.clear()
        sb.appendLine("=== 触摸事件分发详解 ===\n")
        
        sb.appendLine("【ViewPostImeInputStage】")
        sb.appendLine("```java")
        sb.appendLine("final class ViewPostImeInputStage extends InputStage {")
        sb.appendLine("    @Override")
        sb.appendLine("    protected int onProcess(QueuedInputEvent q) {")
        sb.appendLine("        if (q.mEvent instanceof MotionEvent) {")
        sb.appendLine("            return processPointerEvent(q);")
        sb.appendLine("        }")
        sb.appendLine("        return FORWARD;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    private int processPointerEvent(QueuedInputEvent q) {")
        sb.appendLine("        MotionEvent event = (MotionEvent) q.mEvent;")
        sb.appendLine("        ")
        sb.appendLine("        // 转换坐标（如果需要）")
        sb.appendLine("        if (mTranslator != null) {")
        sb.appendLine("            mTranslator.translateEventInScreenToAppWindow(event);")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        // 分发给 View 树")
        sb.appendLine("        boolean handled = mView.dispatchPointerEvent(event);")
        sb.appendLine("        ")
        sb.appendLine("        return handled ? FINISH_HANDLED : FINISH_NOT_HANDLED;")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【View.dispatchPointerEvent】")
        sb.appendLine("```java")
        sb.appendLine("public final boolean dispatchPointerEvent(MotionEvent event) {")
        sb.appendLine("    if (event.isTouchEvent()) {")
        sb.appendLine("        return dispatchTouchEvent(event);")
        sb.appendLine("    } else {")
        sb.appendLine("        return dispatchGenericMotionEvent(event);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【DecorView.dispatchTouchEvent】")
        sb.appendLine("```java")
        sb.appendLine("public boolean dispatchTouchEvent(MotionEvent ev) {")
        sb.appendLine("    // 调用 Window Callback")
        sb.appendLine("    final Window.Callback cb = mWindow.getCallback();")
        sb.appendLine("    return cb != null && !mWindow.isDestroyed() && mFeatureId < 0")
        sb.appendLine("            ? cb.dispatchTouchEvent(ev) : super.dispatchTouchEvent(ev);")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【Activity.dispatchTouchEvent】")
        sb.appendLine("```java")
        sb.appendLine("public boolean dispatchTouchEvent(MotionEvent ev) {")
        sb.appendLine("    if (ev.getAction() == MotionEvent.ACTION_DOWN) {")
        sb.appendLine("        onUserInteraction();")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    if (getWindow().superDispatchTouchEvent(ev)) {")
        sb.appendLine("        return true;")
        sb.appendLine("    }")
        sb.appendLine("    return onTouchEvent(ev);")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【完整分发流程】")
        sb.appendLine("```\n")
        sb.appendLine("InputEventReceiver.onInputEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("ViewRootImpl.deliverInputEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("ViewPostImeInputStage.processPointerEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("DecorView.dispatchPointerEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("DecorView.dispatchTouchEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("Activity.dispatchTouchEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("PhoneWindow.superDispatchTouchEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("DecorView.superDispatchTouchEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("ViewGroup.dispatchTouchEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("View.dispatchTouchEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("View.onTouchEvent()")
        sb.appendLine("```\n")
        
        sb.appendLine("【ViewGroup.dispatchTouchEvent 简化版】")
        sb.appendLine("```java")
        sb.appendLine("public boolean dispatchTouchEvent(MotionEvent ev) {")
        sb.appendLine("    // 检查是否被拦截")
        sb.appendLine("    final boolean intercepted;")
        sb.appendLine("    if (actionMasked == MotionEvent.ACTION_DOWN || mFirstTouchTarget != null) {")
        sb.appendLine("        final boolean disallowIntercept = (mGroupFlags & FLAG_DISALLOW_INTERCEPT) != 0;")
        sb.appendLine("        if (!disallowIntercept) {")
        sb.appendLine("            intercepted = onInterceptTouchEvent(ev);")
        sb.appendLine("        } else {")
        sb.appendLine("            intercepted = false;")
        sb.appendLine("        }")
        sb.appendLine("    } else {")
        sb.appendLine("        intercepted = true;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 如果没被拦截，分发给子 View")
        sb.appendLine("    if (!intercepted) {")
        sb.appendLine("        for (int i = childrenCount - 1; i >= 0; i--) {")
        sb.appendLine("            View child = children[i];")
        sb.appendLine("            ")
        sb.appendLine("            // 检查事件是否在子 View 内")
        sb.appendLine("            if (!isTransformedTouchPointInView(x, y, child, null)) {")
        sb.appendLine("                continue;")
        sb.appendLine("            }")
        sb.appendLine("            ")
        sb.appendLine("            // 分发给子 View")
        sb.appendLine("            if (dispatchTransformedTouchEvent(ev, child)) {")
        sb.appendLine("                // 子 View 消费了事件")
        sb.appendLine("                newTouchTarget = addTouchTarget(child, idBitToAssign);")
        sb.appendLine("                break;")
        sb.appendLine("            }")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 处理触摸目标")
        sb.appendLine("    if (mFirstTouchTarget == null) {")
        sb.appendLine("        // 没有子 View 消费，自己处理")
        sb.appendLine("        dispatchTransformedTouchEvent(ev, null);")
        sb.appendLine("    } else {")
        sb.appendLine("        // 分发给触摸目标")
        sb.appendLine("        TouchTarget target = mFirstTouchTarget;")
        sb.appendLine("        while (target != null) {")
        sb.appendLine("            dispatchTransformedTouchEvent(ev, target.child);")
        sb.appendLine("            target = target.next;")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("    return handled;")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【关键点】")
        sb.appendLine("1. ViewRootImpl 是事件分发的入口")
        sb.appendLine("2. InputStage 是责任链模式")
        sb.appendLine("3. DecorView 分发给 Activity")
        sb.appendLine("4. Activity 再分发给 ViewGroup")
        sb.appendLine("5. ViewGroup 根据 onInterceptTouchEvent 决定是否拦截")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * 键盘事件分发详解
     */
    private fun showKeyEventDispatch() {
        sb.clear()
        sb.appendLine("=== 键盘事件分发详解 ===\n")
        
        sb.appendLine("【NativePostImeInputStage】")
        sb.appendLine("```java")
        sb.appendLine("final class NativePostImeInputStage extends InputStage {")
        sb.appendLine("    @Override")
        sb.appendLine("    protected int onProcess(QueuedInputEvent q) {")
        sb.appendLine("        if (q.mEvent instanceof KeyEvent) {")
        sb.appendLine("            return processKeyEvent(q);")
        sb.appendLine("        }")
        sb.appendLine("        return FORWARD;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    private int processKeyEvent(QueuedInputEvent q) {")
        sb.appendLine("        KeyEvent event = (KeyEvent) q.mEvent;")
        sb.appendLine("        ")
        sb.appendLine("        // 检查快捷键")
        sb.appendLine("        if (event.getAction() == KeyEvent.ACTION_DOWN) {")
        sb.appendLine("            // 处理面板快捷键")
        sb.appendLine("            if (fallbackEventHandler.dispatchKeyEvent(event)) {")
        sb.appendLine("                return FINISH_HANDLED;")
        sb.appendLine("            }")
        sb.appendLine("        }")
        sb.appendLine("        return FORWARD;")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【ViewPostImeInputStage.processKeyEvent】")
        sb.appendLine("```java")
        sb.appendLine("private int processKeyEvent(QueuedInputEvent q) {")
        sb.appendLine("    KeyEvent event = (KeyEvent) q.mEvent;")
        sb.appendLine("    ")
        sb.appendLine("    // 1. 先分发给 View 树")
        sb.appendLine("    if (mView.dispatchKeyEvent(event)) {")
        sb.appendLine("        return FINISH_HANDLED;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 2. 处理焦点导航")
        sb.appendLine("    if (event.getAction() == KeyEvent.ACTION_DOWN) {")
        sb.appendLine("        int direction = 0;")
        sb.appendLine("        switch (event.getKeyCode()) {")
        sb.appendLine("            case KeyEvent.KEYCODE_DPAD_UP:")
        sb.appendLine("                direction = View.FOCUS_UP;")
        sb.appendLine("                break;")
        sb.appendLine("            case KeyEvent.KEYCODE_DPAD_DOWN:")
        sb.appendLine("                direction = View.FOCUS_DOWN;")
        sb.appendLine("                break;")
        sb.appendLine("            // ...")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        if (direction != 0) {")
        sb.appendLine("            View focused = mView.findFocus();")
        sb.appendLine("            if (focused != null) {")
        sb.appendLine("                View v = focused.focusSearch(direction);")
        sb.appendLine("                if (v != null && v != focused) {")
        sb.appendLine("                    v.requestFocus(direction);")
        sb.appendLine("                    return FINISH_HANDLED;")
        sb.appendLine("                }")
        sb.appendLine("            }")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    return FORWARD;")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【View.dispatchKeyEvent】")
        sb.appendLine("```java")
        sb.appendLine("public boolean dispatchKeyEvent(KeyEvent event) {")
        sb.appendLine("    // 1. 分发给 OnKeyListener")
        sb.appendLine("    ListenerInfo li = mListenerInfo;")
        sb.appendLine("    if (li != null && li.mOnKeyListener != null") 
        sb.appendLine("            && (mViewFlags & ENABLED_MASK) == ENABLED") 
        sb.appendLine("            && li.mOnKeyListener.onKey(this, event.getKeyCode(), event)) {")
        sb.appendLine("        return true;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 2. 分发给 KeyEvent.DispatcherState")
        sb.appendLine("    if (event.dispatch(this, mAttachInfo != null ? mAttachInfo.mKeyDispatchState : null, this)) {")
        sb.appendLine("        return true;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    return false;")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【KeyEvent.dispatch】")
        sb.appendLine("```java")
        sb.appendLine("public final boolean dispatch(Callback receiver, DispatcherState state, Object target) {")
        sb.appendLine("    switch (mAction) {")
        sb.appendLine("        case ACTION_DOWN: {")
        sb.appendLine("            if (state != null) {")
        sb.appendLine("                // 检查是否重复按键")
        sb.appendLine("                if (mRepeatCount == 0) {")
        sb.appendLine("                    state.startTracking(this, target);")
        sb.appendLine("                } else if ((mFlags & FLAG_LONG_PRESS) != 0) {")
        sb.appendLine("                    // 长按处理")
        sb.appendLine("                    return receiver.onKeyLongPress(this);")
        sb.appendLine("                }")
        sb.appendLine("            }")
        sb.appendLine("            return receiver.onKeyDown(mKeyCode, this);")
        sb.appendLine("        }")
        sb.appendLine("        case ACTION_UP:")
        sb.appendLine("            if (state != null && state.isTracking(this)) {")
        sb.appendLine("                state.handleUpEvent(this);")
        sb.appendLine("            }")
        sb.appendLine("            return receiver.onKeyUp(mKeyCode, this);")
        sb.appendLine("        case ACTION_MULTIPLE:")
        sb.appendLine("            return receiver.onKeyMultiple(mKeyCode, mRepeatCount, this);")
        sb.appendLine("    }")
        sb.appendLine("    return false;")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【键盘事件分发流程】")
        sb.appendLine("```\n")
        sb.appendLine("InputEventReceiver.onInputEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("ViewRootImpl.deliverInputEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("NativePostImeInputStage.processKeyEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("ViewPostImeInputStage.processKeyEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("DecorView.dispatchKeyEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("Activity.dispatchKeyEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("ViewGroup.dispatchKeyEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("View.dispatchKeyEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ├─→ OnKeyListener.onKey()")
        sb.appendLine("           │")
        sb.appendLine("           └─→ onKeyDown() / onKeyUp()")
        sb.appendLine("```")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * InputStage 责任链详解
     */
    private fun showInputStage() {
        sb.clear()
        sb.appendLine("=== InputStage 责任链 ===\n")
        
        sb.appendLine("【InputStage 结构】")
        sb.appendLine("```java")
        sb.appendLine("abstract class InputStage {")
        sb.appendLine("    private final InputStage mNext;  // 下一个 Stage")
        sb.appendLine("    ")
        sb.appendLine("    public InputStage(InputStage next) {")
        sb.appendLine("        mNext = next;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    public final void deliver(QueuedInputEvent q) {")
        sb.appendLine("        if ((q.mFlags & QueuedInputEvent.FLAG_FINISHED) != 0) {")
        sb.appendLine("            forward(q);")
        sb.appendLine("        } else if (shouldDropInputEvent(q)) {")
        sb.appendLine("            finish(q, false);")
        sb.appendLine("        } else {")
        sb.appendLine("            apply(q, onProcess(q));")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    protected abstract int onProcess(QueuedInputEvent q);")
        sb.appendLine("    ")
        sb.appendLine("    protected void finish(QueuedInputEvent q, boolean handled) {")
        sb.appendLine("        q.mFlags |= QueuedInputEvent.FLAG_FINISHED;")
        sb.appendLine("        if (mNext != null) {")
        sb.appendLine("            mNext.deliver(q);")
        sb.appendLine("        } else {")
        sb.appendLine("            finishInputEvent(q);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    protected void forward(QueuedInputEvent q) {")
        sb.appendLine("        if (mNext != null) {")
        sb.appendLine("            mNext.deliver(q);")
        sb.appendLine("        } else {")
        sb.appendLine("            finishInputEvent(q);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【ViewRootImpl 中的 InputStage 链】")
        sb.appendLine("```\n")
        sb.appendLine("mSyntheticInputStage")
        sb.appendLine("        │")
        sb.appendLine("        ↓")
        sb.appendLine("mSynthesizedInputStage")
        sb.appendLine("        │")
        sb.appendLine("        ↓")
        sb.appendLine("mImeInputStage ← 输入法处理")
        sb.appendLine("        │")
        sb.appendLine("        ↓")
        sb.appendLine("mEarlyPostImeInputStage")
        sb.appendLine("        │")
        sb.appendLine("        ↓")
        sb.appendLine("mNativePostImeInputStage ← Native 键盘事件")
        sb.appendLine("        │")
        sb.appendLine("        ↓")
        sb.appendLine("mViewPostImeInputStage ← View 事件分发")
        sb.appendLine("        │")
        sb.appendLine("        ↓")
        sb.appendLine("mImeInputStage (post)")
        sb.appendLine("        │")
        sb.appendLine("        ↓")
        sb.appendLine("mEarlyInputStage")
        sb.appendLine("        │")
        sb.appendLine("        ↓")
        sb.appendLine("mNativePreImeInputStage")
        sb.appendLine("        │")
        sb.appendLine("        ↓")
        sb.appendLine("mViewPreImeInputStage")
        sb.appendLine("```\n")
        
        sb.appendLine("【各 Stage 职责】")
        sb.appendLine("```java")
        sb.appendLine("// SynthesizeInputStage - 处理合成事件")
        sb.appendLine("// 如：键盘导航、轨迹球等")
        sb.appendLine("")
        sb.appendLine("// ImeInputStage - 输入法处理")
        sb.appendLine("// 在分发给 View 之前，先让输入法处理")
        sb.appendLine("")
        sb.appendLine("// EarlyPostImeInputStage - IME 后的早期处理")
        sb.appendLine("// 处理一些需要在 IME 之后立即处理的事件")
        sb.appendLine("")
        sb.appendLine("// NativePostImeInputStage - Native 层处理")
        sb.appendLine("// 处理键盘快捷键、面板快捷键等")
        sb.appendLine("")
        sb.appendLine("// ViewPostImeInputStage - View 事件分发")
        sb.appendLine("// 核心的事件分发，将事件分发给 View 树")
        sb.appendLine("```\n")
        
        sb.appendLine("【责任链模式图】")
        sb.appendLine("```\n")
        sb.appendLine("              InputEvent")
        sb.appendLine("                  │")
        sb.appendLine("                  ↓")
        sb.appendLine("        ┌─────────────────────┐")
        sb.appendLine("        │  Stage 1            │")
        sb.appendLine("        │  onProcess()        │")
        sb.appendLine("        │    ↓                │")
        sb.appendLine("        │  FORWARD? ──────────┼──→ Stage 2 → Stage 3 → ...")
        sb.appendLine("        │    ↓                │")
        sb.appendLine("        │  FINISH_HANDLED? ───┼──→ finish()")
        sb.appendLine("        │    ↓                │")
        sb.appendLine("        │  FINISH_NOT_HANDLED?┼──→ finish()")
        sb.appendLine("        └─────────────────────┘")
        sb.appendLine("```")
        
        binding.tvContent.text = sb.toString()
    }

    /**
     * 未处理事件详解
     */
    private fun showUnhandledEvent() {
        sb.clear()
        sb.appendLine("=== 未处理事件 ===\n")
        
        sb.appendLine("【事件未被任何 View 处理】")
        sb.appendLine("```java")
        sb.appendLine("// 如果事件未被任何 View 处理，最终会走到：")
        sb.appendLine("// Activity.onTouchEvent()")
        sb.appendLine("")
        sb.appendLine("public boolean onTouchEvent(MotionEvent event) {")
        sb.appendLine("    if (mWindow.shouldCloseOnTouch(this, event)) {")
        sb.appendLine("        finish();")
        sb.appendLine("        return true;")
        sb.appendLine("    }")
        sb.appendLine("    return false;")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【返回给 InputDispatcher】")
        sb.appendLine("```java")
        sb.appendLine("// 当事件处理完成，会调用 finishInputEvent")
        sb.appendLine("private void finishInputEvent(QueuedInputEvent q) {")
        sb.appendLine("    // 通知 InputEventReceiver 完成")
        sb.appendLine("    if (q.mReceiver != null) {")
        sb.appendLine("        q.mReceiver.finishInputEvent(q.mEvent);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 回收事件对象")
        sb.appendLine("    recycleQueuedInputEvent(q);")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【InputEventReceiver.finishInputEvent】")
        sb.appendLine("```java")
        sb.appendLine("public final void finishInputEvent(InputEvent event) {")
        sb.appendLine("    // Native 方法，通知 InputDispatcher")
        sb.appendLine("    nativeFinishInputEvent(event.getSequenceNumber(), handled);")
        sb.appendLine("}")
        sb.appendLine("```\n")
        
        sb.appendLine("【ANR 风险】")
        sb.appendLine("```java")
        sb.appendLine("// 如果事件没有被及时处理，会触发 ANR")
        sb.appendLine("// InputDispatcher 会设置超时监听")
        sb.appendLine("")
        sb.appendLine("// 派发超时时间：")
        sb.appendLine("// - 普通事件：5 秒")
        sb.appendLine("// - 前台按键：5 秒")
        sb.appendLine("// - 后台按键：10 秒")
        sb.appendLine("")
        sb.appendLine("// 如果应用在超时时间内没有调用 finishInputEvent")
        sb.appendLine("// InputDispatcher 会认为应用无响应，触发 ANR")
        sb.appendLine("```\n")
        
        sb.appendLine("【事件处理时序】")
        sb.appendLine("```\n")
        sb.appendLine("InputDispatcher.dispatchMotionEvent()")
        sb.appendLine("           │")
        sb.appendLine("           ↓ (设置超时监听)")
        sb.appendLine("     ┌─────────────┐")
        sb.appendLine("     │  等待响应    │ ← 5 秒超时")
        sb.appendLine("     └─────────────┘")
        sb.appendLine("           │")
        sb.appendLine("     ┌─────┴─────┐")
        sb.appendLine("     ↓           ↓")
        sb.appendLine("  正常响应    超时无响应")
        sb.appendLine("     │           │")
        sb.appendLine("     ↓           ↓")
        sb.appendLine("继续派发    触发 ANR")
        sb.appendLine("```")
        
        binding.tvContent.text = sb.toString()
    }

    override fun onSupportNavigateUp(): Boolean {
        onBackPressedDispatcher.onBackPressed()
        return true
    }
}
