package com.peter.window.demo.viewroot.deep

import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Rect
import android.os.Bundle
import android.view.Surface
import android.view.SurfaceHolder
import android.view.SurfaceView
import android.view.View
import androidx.appcompat.app.AppCompatActivity
import com.peter.window.demo.databinding.ActivitySurfaceRenderBinding

/**
 * 深入篇：Surface 与渲染详解
 *
 * ViewRootImpl 持有一个 Surface 对象，所有的 UI 绘制最终
 * 都是通过这个 Surface 完成的。
 *
 * 核心概念：
 * 1. Surface - 绘图的画布，底层是 GraphicBuffer
 * 2. Canvas - 绘图的 API 封装
 * 3. HardwareRenderer - 硬件加速渲染器
 * 4. SurfaceFlinger - 系统合成服务
 */
class SurfaceRenderActivity : AppCompatActivity() {

    private lateinit var binding: ActivitySurfaceRenderBinding
    private val sb = StringBuilder()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivitySurfaceRenderBinding.inflate(layoutInflater)
        setContentView(binding.root)
        supportActionBar?.setDisplayHomeAsUpEnabled(true)

        setupListeners()
        showOverview()
    }

    private fun setupListeners() {
        binding.btnOverview.setOnClickListener { showOverview() }
        binding.btnSurface.setOnClickListener { showSurfaceDetails() }
        binding.btnHardwareAccel.setOnClickListener { showHardwareAcceleration() }
        binding.btnRenderNode.setOnClickListener { showRenderNode() }
        binding.btnDrawProcess.setOnClickListener { showDrawProcess() }
        binding.btnSurfaceFlinger.setOnClickListener { showSurfaceFlinger() }
        binding.btnDoubleBuffer.setOnClickListener { showDoubleBuffer() }
        binding.btnPractice.setOnClickListener { demonstrateSurface() }
    }

    /**
     * Surface 渲染概述
     */
    private fun showOverview() {
        sb.clear()
        sb.appendLine("=== Surface 与渲染概述 ===\n")

        sb.appendLine("【整体架构】")
        sb.appendLine("```\n")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                        应用进程                             │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  ViewRootImpl                                               │\n")
        sb.appendLine("│       │                                                     │\n")
        sb.appendLine("│       ├── mSurface (Surface)                                │\n")
        sb.appendLine("│       │                                                     │\n")
        sb.appendLine("│       └── mAttachInfo.mHardwareRenderer                     │\n")
        sb.appendLine("│                    │                                        │\n")
        sb.appendLine("│                    ↓                                        │\n")
        sb.appendLine("│           ┌────────────────────┐                            │\n")
        sb.appendLine("│           │  ThreadedRenderer  │                            │\n")
        sb.appendLine("│           │       │            │                            │\n")
        sb.appendLine("│           │  RenderNode 树     │                            │\n")
        sb.appendLine("│           │       │            │                            │\n")
        sb.appendLine("│           │  CanvasContext     │                            │\n")
        sb.appendLine("│           └────────────────────┘                            │\n")
        sb.appendLine("│                    │                                        │\n")
        sb.appendLine("└────────────────────│────────────────────────────────────────┘\n")
        sb.appendLine("                     │ (Binder IPC)")
        sb.appendLine("                     ↓")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                        系统进程                             │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│           ┌────────────────────┐                            │\n")
        sb.appendLine("│           │  SurfaceFlinger    │                            │\n")
        sb.appendLine("│           │       │            │                            │\n")
        sb.appendLine("│           │  GraphicBuffer     │                            │\n")
        sb.appendLine("│           │       │            │                            │\n")
        sb.appendLine("│           │  HWComposer        │                            │\n")
        sb.appendLine("│           └────────────────────┘                            │\n")
        sb.appendLine("│                    │                                        │\n")
        sb.appendLine("│                    ↓                                        │\n")
        sb.appendLine("│              Display (屏幕)                                 │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")

        sb.appendLine("【Surface 的本质】")
        sb.appendLine("```java")
        sb.appendLine("// Surface 是一个绘图表面的抽象")
        sb.appendLine("public class Surface implements Parcelable {")
        sb.appendLine("    // 指向 Native Surface 的指针")
        sb.appendLine("    private long mNativeObject;")
        sb.appendLine("    ")
        sb.appendLine("    // 画布（软件绘制用）")
        sb.appendLine("    private Canvas mCanvas;")
        sb.appendLine("    ")
        sb.appendLine("    // 名称")
        sb.appendLine("    private String mName;")
        sb.appendLine("    ")
        sb.appendLine("    // 是否有效")
        sb.appendLine("    public boolean isValid() {")
        sb.appendLine("        return mNativeObject != 0;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 锁定画布进行绘制")
        sb.appendLine("    public Canvas lockCanvas(Rect inOutDirty);")
        sb.appendLine("    ")
        sb.appendLine("    // 解锁并提交")
        sb.appendLine("    public void unlockCanvasAndPost(Canvas canvas);")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【渲染方式对比】")
        sb.appendLine("```\n")
        sb.appendLine("┌────────────────┬────────────────┬────────────────┐\n")
        sb.appendLine("│                │   软件绘制     │   硬件绘制     │\n")
        sb.appendLine("├────────────────┼────────────────┼────────────────┤\n")
        sb.appendLine("│ Canvas         │ Skia Canvas    │ RecordingCanvas│\n")
        sb.appendLine("│ 渲染线程       │ 主线程         │ RenderThread   │\n")
        sb.appendLine("│ 内存           │ Bitmap 内存    │ GPU 显存       │\n")
        sb.appendLine("│ 性能           │ 较低           │ 较高           │\n")
        sb.appendLine("│ 兼容性         │ 最好           │ 部分不支持     │\n")
        sb.appendLine("│ 调试           │ 简单           │ 复杂           │\n")
        sb.appendLine("└────────────────┴────────────────┴────────────────┘\n")
        sb.appendLine("```\n")

        sb.appendLine("【ViewRootImpl 中的 Surface】")
        sb.appendLine("```java")
        sb.appendLine("// ViewRootImpl 持有 Surface")
        sb.appendLine("public final class ViewRootImpl {")
        sb.appendLine("    // Surface 对象")
        sb.appendLine("    final Surface mSurface = new Surface();")
        sb.appendLine("    ")
        sb.appendLine("    // 硬件渲染器")
        sb.appendLine("    ThreadedRenderer mAttachInfo.mHardwareRenderer;")
        sb.appendLine("    ")
        sb.appendLine("    // 绘制方法")
        sb.appendLine("    private boolean draw(boolean fullRedrawNeeded) {")
        sb.appendLine("        if (mAttachInfo.mHardwareRenderer != null) {")
        sb.appendLine("            // 硬件绘制")
        sb.appendLine("            mAttachInfo.mHardwareRenderer.draw(mView, mAttachInfo);")
        sb.appendLine("        } else {")
        sb.appendLine("            // 软件绘制")
        sb.appendLine("            Canvas canvas = mSurface.lockCanvas(dirty);")
        sb.appendLine("            mView.draw(canvas);")
        sb.appendLine("            mSurface.unlockCanvasAndPost(canvas);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【Surface 状态】")
        sb.appendLine("```\n")
        sb.appendLine("1. 创建状态")
        sb.appendLine("   - new Surface() 只是创建 Java 对象")
        sb.appendLine("   - mNativeObject = 0，此时无效\n")

        sb.appendLine("2. 有效状态")
        sb.appendLine("   - 通过 relayoutWindow 从 WMS 获取")
        sb.appendLine("   - mNativeObject != 0，可以绘制\n")

        sb.appendLine("3. 销毁状态")
        sb.appendLine("   - destroySurface() 后")
        sb.appendLine("   - mNativeObject = 0，不可绘制")
        sb.appendLine("```")

        binding.tvContent.text = sb.toString()
    }

    /**
     * Surface 详解
     */
    private fun showSurfaceDetails() {
        sb.clear()
        sb.appendLine("=== Surface 详解 ===\n")

        sb.appendLine("【Surface 创建流程】")
        sb.appendLine("```java")
        sb.appendLine("// 1. ViewRootImpl 创建 Surface")
        sb.appendLine("final Surface mSurface = new Surface();  // 空 Surface\n")

        sb.appendLine("// 2. 通过 relayoutWindow 从 WMS 获取有效的 Surface")
        sb.appendLine("private int relayoutWindow(WindowManager.LayoutParams params,")
        sb.appendLine("        int viewVisibility, boolean insetsPending) {")
        sb.appendLine("    ")
        sb.appendLine("    // 调用 WMS 的 relayout")
        sb.appendLine("    int relayoutResult = mWindowSession.relayout(")
        sb.appendLine("        mWindow, mSeq, params,")
        sb.appendLine("        (int) (mView.getMeasuredWidth() * appScale + 0.5f),")
        sb.appendLine("        (int) (mView.getMeasuredHeight() * appScale + 0.5f),")
        sb.appendLine("        viewVisibility, insetsPending ? WindowManagerGlobal.RELAYOUT_HINT_INSETS_PENDING : 0,")
        sb.appendLine("        mWinFrame, mPendingOverscanInsets, mPendingContentInsets,")
        sb.appendLine("        mPendingStableInsets, mPendingOutsets, mPendingBackDropFrame,")
        sb.appendLine("        mPendingDisplayCutout, mPendingMergedConfiguration, mSurface);")
        sb.appendLine("    ")
        sb.appendLine("    // 此时 mSurface 已经有效")
        sb.appendLine("    return relayoutResult;")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【Native 层 Surface】")
        sb.appendLine("```cpp")
        sb.appendLine("// frameworks/native/libs/gui/Surface.cpp")
        sb.appendLine("class Surface : public ANativeObjectBase<ANativeWindow, Surface, RefBase> {")
        sb.appendLine("private:")
        sb.appendLine("    // 图形缓冲区生产者")
        sb.appendLine("    sp<IGraphicBufferProducer> mGraphicBufferProducer;")
        sb.appendLine("    ")
        sb.appendLine("    // 当前缓冲区")
        sb.appendLine("    sp<GraphicBuffer> mLockedBuffer;")
        sb.appendLine("    sp<GraphicBuffer> mPostedBuffer;")
        sb.appendLine("    ")
        sb.appendLine("    // 缓冲区槽位")
        sb.appendLine("    BufferSlot mSlots[NUM_BUFFER_SLOTS];")
        sb.appendLine("};")
        sb.appendLine("```\n")

        sb.appendLine("【GraphicBuffer】")
        sb.appendLine("```\n")
        sb.appendLine("GraphicBuffer 是真正的图形缓冲区：")
        sb.appendLine("┌────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                    GraphicBuffer                          │\n")
        sb.appendLine("│                                                            │\n")
        sb.appendLine("│  ┌──────────────────────────────────────────────────────┐ │\n")
        sb.appendLine("│  │                  Pixel Data                          │ │\n")
        sb.appendLine("│  │                                                      │ │\n")
        sb.appendLine("│  │    width * height * bytesPerPixel 字节的像素数据     │ │\n")
        sb.appendLine("│  │                                                      │ │\n")
        sb.appendLine("│  │    例如：1080x1920 * 4 = 8,294,400 字节 ≈ 8MB       │ │\n")
        sb.appendLine("│  │                                                      │ │\n")
        sb.appendLine("│  └──────────────────────────────────────────────────────┘ │\n")
        sb.appendLine("│                                                            │\n")
        sb.appendLine("│  属性：                                                    │\n")
        sb.appendLine("│  - width, height: 尺寸                                    │\n")
        sb.appendLine("│  - format: 像素格式 (RGBA_8888, RGB_565...)              │\n")
        sb.appendLine("│  - usage: 用途 (纹理、渲染目标、CPU读写...)              │\n")
        sb.appendLine("│  - handle: 共享内存句柄                                   │\n")
        sb.appendLine("└────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")

        sb.appendLine("【Surface 锁定与提交】")
        sb.appendLine("```java")
        sb.appendLine("// 软件绘制的完整流程")
        sb.appendLine("private void softwareDraw() {")
        sb.appendLine("    // 1. 锁定 Surface，获取 Canvas")
        sb.appendLine("    Rect dirty = mDirty;")
        sb.appendLine("    Canvas canvas = mSurface.lockCanvas(dirty);")
        sb.appendLine("    ")
        sb.appendLine("    if (canvas != null) {")
        sb.appendLine("        try {")
        sb.appendLine("            // 2. 在 Canvas 上绘制")
        sb.appendLine("            canvas.drawColor(Color.WHITE);  // 清空背景")
        sb.appendLine("            mView.draw(canvas);  // 绘制 View 树")
        sb.appendLine("            ")
        sb.appendLine("        } finally {")
        sb.appendLine("            // 3. 解锁并提交")
        sb.appendLine("            mSurface.unlockCanvasAndPost(canvas);")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【lockCanvas Native 实现】")
        sb.appendLine("```cpp")
        sb.appendLine("// Surface::lockCanvas 最终调用")
        sb.appendLine("status_t Surface::lock(BufferBase* buffer, bool blocking) {")
        sb.appendLine("    // 1. 从 BufferQueue 获取一个空闲缓冲区")
        sb.appendLine("    status_t err = dequeueBuffer(&buf, &fenceFd);")
        sb.appendLine("    ")
        sb.appendLine("    // 2. 等待缓冲区可用")
        sb.appendLine("    waitFence(fenceFd);")
        sb.appendLine("    ")
        sb.appendLine("    // 3. 锁定缓冲区，获取内存地址")
        sb.appendLine("    void* vaddr;")
        sb.appendLine("    buf->lock(GRALLOC_USAGE_SW_WRITE_OFTEN, &vaddr);")
        sb.appendLine("    ")
        sb.appendLine("    // 4. 创建 Skia Canvas")
        sb.appendLine("    mLockedBuffer = buf;")
        sb.appendLine("    return NO_ERROR;")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【unlockCanvasAndPost 实现】")
        sb.appendLine("```cpp")
        sb.appendLine("status_t Surface::unlockAndPost() {")
        sb.appendLine("    // 1. 解锁缓冲区")
        sb.appendLine("    mLockedBuffer->unlock();")
        sb.appendLine("    ")
        sb.appendLine("    // 2. 将缓冲区入队到 BufferQueue")
        sb.appendLine("    // SurfaceFlinger 会从这里取走并合成")
        sb.appendLine("    status_t err = queueBuffer(mLockedBuffer, ...);")
        sb.appendLine("    ")
        sb.appendLine("    // 3. 通知 SurfaceFlinger 有新帧")
        sb.appendLine("    mGraphicBufferProducer->queueBuffer(...);")
        sb.appendLine("    ")
        sb.appendLine("    mPostedBuffer = mLockedBuffer;")
        sb.appendLine("    mLockedBuffer = 0;")
        sb.appendLine("    return err;")
        sb.appendLine("}")
        sb.appendLine("```")

        binding.tvContent.text = sb.toString()
    }

    /**
     * 硬件加速详解
     */
    private fun showHardwareAcceleration() {
        sb.clear()
        sb.appendLine("=== 硬件加速详解 ===\n")

        sb.appendLine("【硬件加速开关】")
        sb.appendLine("```xml")
        sb.appendLine("<!-- AndroidManifest.xml -->")
        sb.appendLine("<!-- Application 级别 -->")
        sb.appendLine("<application android:hardwareAccelerated=\"true\" ...>")
        sb.appendLine("    ")
        sb.appendLine("    <!-- Activity 级别 -->")
        sb.appendLine("    <activity android:hardwareAccelerated=\"false\" ...>")
        sb.appendLine("    </application>")
        sb.appendLine("```\n")

        sb.appendLine("【代码控制】")
        sb.appendLine("```java")
        sb.appendLine("// 禁用硬件加速（仅对当前 View）")
        sb.appendLine("view.setLayerType(View.LAYER_TYPE_SOFTWARE, null);")
        sb.appendLine("")
        sb.appendLine("// 启用硬件加速")
        sb.appendLine("view.setLayerType(View.LAYER_TYPE_HARDWARE, null);")
        sb.appendLine("")
        sb.appendLine("// 检查是否启用硬件加速")
        sb.appendLine("boolean isHardwareAccelerated = view.isHardwareAccelerated();")
        sb.appendLine("boolean isCanvasHardware = canvas.isHardwareAccelerated();")
        sb.appendLine("```\n")

        sb.appendLine("【ThreadedRenderer】")
        sb.appendLine("```java")
        sb.appendLine("// 硬件渲染器")
        sb.appendLine("public class ThreadedRenderer extends HardwareRenderer {")
        sb.appendLine("    // 根 RenderNode")
        sb.appendLine("    private RenderNode mRootNode;")
        sb.appendLine("    ")
        sb.appendLine("    // 渲染线程代理")
        sb.appendLine("    private RenderProxy mRenderProxy;")
        sb.appendLine("    ")
        sb.appendLine("    // 绘制方法")
        sb.appendLine("    void draw(View view, AttachInfo attachInfo) {")
        sb.appendLine("        // 1. 更新 DisplayList")
        sb.appendLine("        updateViewTreeDisplayList(view);")
        sb.appendLine("        ")
        sb.appendLine("        // 2. 同步到渲染线程")
        sb.appendLine("        int syncResult = nSyncAndDrawFrame(...);")
        sb.appendLine("        ")
        sb.appendLine("        // 3. 渲染线程执行绘制")
        sb.appendLine("        // (异步执行)")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【硬件绘制流程】")
        sb.appendLine("```\n")
        sb.appendLine("┌──────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                        主线程                                │\n")
        sb.appendLine("│                                                              │\n")
        sb.appendLine("│  performDraw()                                               │\n")
        sb.appendLine("│       │                                                      │\n")
        sb.appendLine("│       ↓                                                      │\n")
        sb.appendLine("│  ThreadedRenderer.draw()                                     │\n")
        sb.appendLine("│       │                                                      │\n")
        sb.appendLine("│       ├─→ updateViewTreeDisplayList()                       │\n")
        sb.appendLine("│       │         │                                            │\n")
        sb.appendLine("│       │         ↓                                            │\n")
        sb.appendLine("│       │    view.updateDisplayListIfDirty()                   │\n")
        sb.appendLine("│       │         │                                            │\n")
        sb.appendLine("│       │         ↓                                            │\n")
        sb.appendLine("│       │    RecordingCanvas 记录绘制命令                      │\n")
        sb.appendLine("│       │                                                      │\n")
        sb.appendLine("│       └─→ syncAndDrawFrame() 同步到渲染线程                  │\n")
        sb.appendLine("│                                                              │\n")
        sb.appendLine("└──────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("                       │")
        sb.appendLine("                       ↓")
        sb.appendLine("┌──────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                      RenderThread                            │\n")
        sb.appendLine("│                                                              │\n")
        sb.appendLine("│  drawFrame()                                                 │\n")
        sb.appendLine("│       │                                                      │\n")
        sb.appendLine("│       ├─→ 同步 DisplayList                                   │\n")
        sb.appendLine("│       │                                                      │\n")
        sb.appendLine("│       ├─→ 读取 Surface                                       │\n")
        sb.appendLine("│       │                                                      │\n")
        sb.appendLine("│       ├─→ 执行 OpenGL 命令                                   │\n")
        sb.appendLine("│       │                                                      │\n")
        sb.appendLine("│       └─→ swapBuffers() 提交帧                               │\n")
        sb.appendLine("│                                                              │\n")
        sb.appendLine("└──────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")

        sb.appendLine("【DisplayList】")
        sb.appendLine("```java")
        sb.appendLine("// DisplayList 是绘制命令的记录")
        sb.appendLine("public class DisplayList {")
        sb.appendLine("    // 指向 Native DisplayList")
        sb.appendLine("    private long mNativePtr;")
        sb.appendLine("    ")
        sb.appendLine("    // 记录的绘制操作：")
        sb.appendLine("    // - drawRect")
        sb.appendLine("    // - drawCircle")
        sb.appendLine("    // - drawPath")
        sb.appendLine("    // - drawBitmap")
        sb.appendLine("    // - save/restore")
        sb.appendLine("    // - translate/scale/rotate")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【RecordingCanvas】")
        sb.appendLine("```java")
        sb.appendLine("// 硬件绘制使用的 Canvas")
        sb.appendLine("public final class RecordingCanvas extends BaseRecordingCanvas {")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void drawRect(float left, float top, float right, float bottom, Paint paint) {")
        sb.appendLine("        // 不是真正绘制，而是记录命令")
        sb.appendLine("        nDrawRect(mNativeCanvasWrapper, left, top, right, bottom, paint.getNativeInstance());")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    @Override")
        sb.appendLine("    public void drawBitmap(Bitmap bitmap, float left, float top, Paint paint) {")
        sb.appendLine("        // 记录 drawBitmap 命令")
        sb.appendLine("        nDrawBitmap(mNativeCanvasWrapper, bitmap, left, top, paint.getNativeInstance());")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 所有绘制操作都被记录到 DisplayList")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【硬件加速的优势】")
        sb.appendLine("```\n")
        sb.appendLine("1. 分离渲染线程")
        sb.appendLine("   - 主线程只负责记录命令")
        sb.appendLine("   - RenderThread 负责执行 OpenGL 命令")
        sb.appendLine("   - 可以并行工作\n")

        sb.appendLine("2. 缓存机制")
        sb.appendLine("   - DisplayList 可以复用")
        sb.appendLine("   - 只有变化的 View 需要重绘")
        sb.appendLine("   - RenderNode 缓存变换矩阵\n")

        sb.appendLine("3. GPU 加速")
        sb.appendLine("   - OpenGL/Vulkan 渲染")
        sb.appendLine("   - 利用 GPU 并行计算能力")
        sb.appendLine("   - 特效（模糊、阴影）更快\n")

        sb.appendLine("4. 内存效率")
        sb.appendLine("   - 不需要软件位图")
        sb.appendLine("   - 直接使用 GPU 显存")
        sb.appendLine("```")

        binding.tvContent.text = sb.toString()
    }

    /**
     * RenderNode 详解
     */
    private fun showRenderNode() {
        sb.clear()
        sb.appendLine("=== RenderNode 详解 ===\n")

        sb.appendLine("【RenderNode 概念】")
        sb.appendLine("```java")
        sb.appendLine("// RenderNode 是硬件加速渲染的基本单位")
        sb.appendLine("public class RenderNode {")
        sb.appendLine("    // 每个 View 对应一个 RenderNode")
        sb.appendLine("    private final long mNativeRenderNode;")
        sb.appendLine("    ")
        sb.appendLine("    // 属性")
        sb.appendLine("    private String mName;")
        sb.appendLine("    ")
        sb.appendLine("    // 设置变换")
        sb.appendLine("    public boolean setTranslationX(float translationX);")
        sb.appendLine("    public boolean setTranslationY(float translationY);")
        sb.appendLine("    public boolean setScaleX(float scaleX);")
        sb.appendLine("    public boolean setRotation(float rotation);")
        sb.appendLine("    ")
        sb.appendLine("    // 设置透明度")
        sb.appendLine("    public boolean setAlpha(float alpha);")
        sb.appendLine("    ")
        sb.appendLine("    // 设置裁剪")
        sb.appendLine("    public boolean setClipRect(Rect clipRect);")
        sb.appendLine("    ")
        sb.appendLine("    // 设置 DisplayList")
        sb.appendLine("    public boolean setDisplayList(DisplayList displayList);")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【RenderNode 树】")
        sb.appendLine("```\n")
        sb.appendLine("每个 View 都有一个 RenderNode：")
        sb.appendLine("")
        sb.appendLine("View")
        sb.appendLine(" └── mRenderNode (RenderNode)")
        sb.appendLine("")
        sb.appendLine("ViewGroup 的 RenderNode 包含子节点的引用：")
        sb.appendLine("")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                     DecorView                              │\n")
        sb.appendLine("│                     RenderNode                             │\n")
        sb.appendLine("│                          │                                 │\n")
        sb.appendLine("│            ┌─────────────┼─────────────┐                   │\n")
        sb.appendLine("│            ↓             ↓             ↓                   │\n")
        sb.appendLine("│      LinearLayout   FrameLayout   ActionBar                │\n")
        sb.appendLine("│      RenderNode     RenderNode    RenderNode               │\n")
        sb.appendLine("│            │             │                                   │\n")
        sb.appendLine("│            ↓             ↓                                   │\n")
        sb.appendLine("│      TextView       Content                                │\n")
        sb.appendLine("│      RenderNode     RenderNode                             │\n")
        sb.appendLine("│                          │                                 │\n")
        sb.appendLine("│                          ↓                                 │\n")
        sb.appendLine("│                    ...更多子节点...                        │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")

        sb.appendLine("【View 与 RenderNode 的关系】")
        sb.appendLine("```java")
        sb.appendLine("public class View {")
        sb.appendLine("    // View 的 RenderNode")
        sb.appendLine("    RenderNode mRenderNode;")
        sb.appendLine("    ")
        sb.appendLine("    // 获取 RenderNode")
        sb.appendLine("    public RenderNode getRenderNode() {")
        sb.appendLine("        if (mRenderNode == null) {")
        sb.appendLine("            mRenderNode = new RenderNode(\"view_\" + hashCode());")
        sb.appendLine("        }")
        sb.appendLine("        return mRenderNode;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 更新 DisplayList")
        sb.appendLine("    public RenderNode updateDisplayListIfDirty() {")
        sb.appendLine("        RenderNode renderNode = mRenderNode;")
        sb.appendLine("        ")
        sb.appendLine("        if (canHaveDisplayList()) {")
        sb.appendLine("            // 获取 RecordingCanvas")
        sb.appendLine("            RecordingCanvas canvas = renderNode.beginRecording();")
        sb.appendLine("            try {")
        sb.appendLine("                // 记录绘制命令")
        sb.appendLine("                onDraw(canvas);  // 调用自定义绘制")
        sb.appendLine("                dispatchDraw(canvas);  // 分发给子 View")
        sb.appendLine("            } finally {")
        sb.appendLine("                // 结束记录")
        sb.appendLine("                renderNode.endRecording();")
        sb.appendLine("            }")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        return renderNode;")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【RenderNode 优化】")
        sb.appendLine("```java")
        sb.appendLine("// 1. 使用 RenderNode 属性动画（不需要重绘）")
        sb.appendLine("view.setTranslationX(100);  // 只更新 RenderNode 属性")
        sb.appendLine("view.setAlpha(0.5f);        // 不触发 invalidate")
        sb.appendLine("view.setScaleX(1.5f);       // GPU 直接处理变换\n")

        sb.appendLine("// 2. 使用硬件层（复杂动画）")
        sb.appendLine("view.setLayerType(View.LAYER_TYPE_HARDWARE, null);")
        sb.appendLine("// 动画期间，View 的 DisplayList 被缓存为纹理")
        sb.appendLine("// 只有变换属性变化，不需要重新记录命令")
        sb.appendLine("view.animate().translationX(100).start();")
        sb.appendLine("// 动画结束后移除硬件层")
        sb.appendLine("view.setLayerType(View.LAYER_TYPE_NONE, null);\n")

        sb.appendLine("// 3. 检查是否使用 DisplayList")
        sb.appendLine("if (view.canHaveDisplayList()) {")
        sb.appendLine("    // 硬件加速启用，使用 DisplayList")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【属性动画 vs 重绘】")
        sb.appendLine("```\n")
        sb.appendLine("传统方式（触发重绘）：")
        sb.appendLine("view.setX(x);")
        sb.appendLine("  → requestLayout()")
        sb.appendLine("  → scheduleTraversals()")
        sb.appendLine("  → performTraversals()")
        sb.appendLine("  → measure/layout/draw")
        sb.appendLine("  → 耗时！\n")

        sb.appendLine("RenderNode 属性（无重绘）：")
        sb.appendLine("view.setTranslationX(x);")
        sb.appendLine("  → mRenderNode.setTranslationX(x)")
        sb.appendLine("  → 直接更新 GPU 变换矩阵")
        sb.appendLine("  → 不需要重新记录 DisplayList")
        sb.appendLine("  → 快速！")
        sb.appendLine("```")

        binding.tvContent.text = sb.toString()
    }

    /**
     * 绘制流程详解
     */
    private fun showDrawProcess() {
        sb.clear()
        sb.appendLine("=== 绘制流程详解 ===\n")

        sb.appendLine("【performDraw】")
        sb.appendLine("```java")
        sb.appendLine("// ViewRootImpl.performDraw()")
        sb.appendLine("private void performDraw() {")
        sb.appendLine("    // ... 省略部分代码")
        sb.appendLine("    ")
        sb.appendLine("    try {")
        sb.appendLine("        boolean canUseAsync = draw(fullRedrawNeeded);")
        sb.appendLine("        if (canUseAsync) {")
        sb.appendLine("            // 异步绘制完成")
        sb.appendLine("        }")
        sb.appendLine("    } finally {")
        sb.appendLine("        mIsDrawing = false;")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【draw 方法】")
        sb.appendLine("```java")
        sb.appendLine("private boolean draw(boolean fullRedrawNeeded) {")
        sb.appendLine("    Surface surface = mSurface;")
        sb.appendLine("    ")
        sb.appendLine("    // 检查 Surface 是否有效")
        sb.appendLine("    if (!surface.isValid()) {")
        sb.appendLine("        return false;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 获取脏区域")
        sb.appendLine("    final Rect dirty = mDirty;")
        sb.appendLine("    ")
        sb.appendLine("    // 判断渲染方式")
        sb.appendLine("    if (mAttachInfo.mHardwareRenderer != null &&")
        sb.appendLine("            mAttachInfo.mHardwareRenderer.isEnabled()) {")
        sb.appendLine("        // 硬件渲染")
        sb.appendLine("        mAttachInfo.mHardwareRenderer.draw(mView, mAttachInfo, this);")
        sb.appendLine("    } else {")
        sb.appendLine("        // 软件渲染")
        sb.appendLine("        if (!drawSoftware(surface, mAttachInfo, xOffset, yOffset,")
        sb.appendLine("                scalingRequired, dirty)) {")
        sb.appendLine("            return false;")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    return mUseAsync;")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【软件绘制】")
        sb.appendLine("```java")
        sb.appendLine("private boolean drawSoftware(Surface surface, AttachInfo attachInfo,")
        sb.appendLine("        int xOff, int yOff, boolean scalingRequired, Rect dirty) {")
        sb.appendLine("    ")
        sb.appendLine("    final Canvas canvas;")
        sb.appendLine("    try {")
        sb.appendLine("        // 1. 锁定 Canvas")
        sb.appendLine("        canvas = mSurface.lockCanvas(dirty);")
        sb.appendLine("        ")
        sb.appendLine("        // 2. 设置密度")
        sb.appendLine("        canvas.setDensity(mDensity);")
        sb.appendLine("        ")
        sb.appendLine("    } catch (Surface.OutOfResourcesException e) {")
        sb.appendLine("        return false;")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    try {")
        sb.appendLine("        // 3. 在 Canvas 上绘制")
        sb.appendLine("        canvas.translate(-xOff, -yOff);")
        sb.appendLine("        ")
        sb.appendLine("        if (mTranslator != null) {")
        sb.appendLine("            mTranslator.translateCanvas(canvas);")
        sb.appendLine("        }")
        sb.appendLine("        ")
        sb.appendLine("        // 4. 调用 View 树的 draw")
        sb.appendLine("        mView.draw(canvas);")
        sb.appendLine("        ")
        sb.appendLine("    } finally {")
        sb.appendLine("        // 5. 解锁并提交")
        sb.appendLine("        surface.unlockCanvasAndPost(canvas);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    return true;")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【View.draw 流程】")
        sb.appendLine("```java")
        sb.appendLine("// View.draw()")
        sb.appendLine("public void draw(Canvas canvas) {")
        sb.appendLine("    final int privateFlags = mPrivateFlags;")
        sb.appendLine("    final boolean dirtyOpaque = (privateFlags & PFLAG_DIRTY_MASK) == PFLAG_DIRTY_OPAQUE;")
        sb.appendLine("    ")
        sb.appendLine("    /*")
        sb.appendLine("     * 绘制步骤：")
        sb.appendLine("     * 1. 绘制背景")
        sb.appendLine("     * 2. 如果需要，保存 Canvas 层")
        sb.appendLine("     * 3. 绘制内容")
        sb.appendLine("     * 4. 绘制子 View")
        sb.appendLine("     * 5. 如果需要，绘制边缘和恢复 Canvas")
        sb.appendLine("     * 6. 绘制装饰（滚动条等）")
        sb.appendLine("     */")
        sb.appendLine("    ")
        sb.appendLine("    // Step 1: 绘制背景")
        sb.appendLine("    if (!dirtyOpaque) {")
        sb.appendLine("        drawBackground(canvas);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // Step 2-5: 省略...")
        sb.appendLine("    ")
        sb.appendLine("    // Step 3: 绘制内容")
        sb.appendLine("    if (!dirtyOpaque) onDraw(canvas);")
        sb.appendLine("    ")
        sb.appendLine("    // Step 4: 绘制子 View")
        sb.appendLine("    dispatchDraw(canvas);")
        sb.appendLine("    ")
        sb.appendLine("    // Step 6: 绘制装饰")
        sb.appendLine("    onDrawForeground(canvas);")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【绘制顺序】")
        sb.appendLine("```\n")
        sb.appendLine("┌────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                        View                                │\n")
        sb.appendLine("│                                                            │\n")
        sb.appendLine("│  ① drawBackground()    ──── 绘制背景                      │\n")
        sb.appendLine("│     ┌────────────────────┐                                │\n")
        sb.appendLine("│     │   Background       │                                │\n")
        sb.appendLine("│     └────────────────────┘                                │\n")
        sb.appendLine("│                                                            │\n")
        sb.appendLine("│  ② onDraw()            ──── 绘制内容                      │\n")
        sb.appendLine("│     ┌────────────────────┐                                │\n")
        sb.appendLine("│     │   Custom Content   │                                │\n")
        sb.appendLine("│     └────────────────────┘                                │\n")
        sb.appendLine("│                                                            │\n")
        sb.appendLine("│  ③ dispatchDraw()      ──── 绘制子 View                   │\n")
        sb.appendLine("│     ┌────────────────────┐                                │\n")
        sb.appendLine("│     │   Child Views      │                                │\n")
        sb.appendLine("│     └────────────────────┘                                │\n")
        sb.appendLine("│                                                            │\n")
        sb.appendLine("│  ④ onDrawForeground()  ──── 绘制前景装饰                  │\n")
        sb.appendLine("│     ┌────────────────────┐                                │\n")
        sb.appendLine("│     │   Scrollbars       │                                │\n")
        sb.appendLine("│     │   Fading Edge      │                                │\n")
        sb.appendLine("│     └────────────────────┘                                │\n")
        sb.appendLine("└────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```")

        binding.tvContent.text = sb.toString()
    }

    /**
     * SurfaceFlinger 详解
     */
    private fun showSurfaceFlinger() {
        sb.clear()
        sb.appendLine("=== SurfaceFlinger 详解 ===\n")

        sb.appendLine("【SurfaceFlinger 概述】")
        sb.appendLine("SurfaceFlinger 是 Android 的系统合成服务，")
        sb.appendLine("负责将多个应用的 Surface 合成到屏幕上。\n")

        sb.appendLine("【架构图】")
        sb.appendLine("```\n")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                        应用进程                             │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  App A Surface    App B Surface    App C Surface           │\n")
        sb.appendLine("│       │                │                │                  │\n")
        sb.appendLine("└───────│────────────────│────────────────│──────────────────┘\n")
        sb.appendLine("        │                │                │")
        sb.appendLine("        ↓                ↓                ↓")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                        SurfaceFlinger                       │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  ┌──────────────────────────────────────────────────────┐  │\n")
        sb.appendLine("│  │                    Layer 栈                          │  │\n")
        sb.appendLine("│  │                                                      │  │\n")
        sb.appendLine("│  │  ┌────────┐  ┌────────┐  ┌────────┐                 │  │\n")
        sb.appendLine("│  │  │ Layer A│  │ Layer B│  │ Layer C│                 │  │\n")
        sb.appendLine("│  │  └────────┘  └────────┘  └────────┘                 │  │\n")
        sb.appendLine("│  │       │           │           │                      │  │\n")
        sb.appendLine("│  │       └───────────┼───────────┘                      │  │\n")
        sb.appendLine("│  │                   ↓                                  │  │\n")
        sb.appendLine("│  │            ┌────────────┐                            │  │\n")
        sb.appendLine("│  │            │  合成器    │                            │  │\n")
        sb.appendLine("│  │            └────────────┘                            │  │\n")
        sb.appendLine("│  └──────────────────────────────────────────────────────┘  │\n")
        sb.appendLine("│                          │                                 │\n")
        sb.appendLine("└──────────────────────────│─────────────────────────────────┘\n")
        sb.appendLine("                           ↓")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                        HWComposer                           │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  Hardware Composer (硬件合成器)                             │\n")
        sb.appendLine("│  - 使用 GPU 或专用硬件合成                                   │\n")
        sb.appendLine("│  - 支持多平面 Overlay                                        │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("                           │")
        sb.appendLine("                           ↓")
        sb.appendLine("                       Display")
        sb.appendLine("```\n")

        sb.appendLine("【Layer】")
        sb.appendLine("```java")
        sb.appendLine("// 每个 Surface 对应一个 Layer")
        sb.appendLine("class Layer {")
        sb.appendLine("    // 图形缓冲区队列")
        sb.appendLine("    BufferQueue mBufferQueue;")
        sb.appendLine("    ")
        sb.appendLine("    // 当前显示的缓冲区")
        sb.appendLine("    sp<GraphicBuffer> mActiveBuffer;")
        sb.appendLine("    ")
        sb.appendLine("    // Layer 属性")
        sb.appendLine("    Rect mBounds;         // 边界")
        sb.appendLine("    float mAlpha;         // 透明度")
        sb.appendLine("    Rect mCrop;           // 裁剪区域")
        sb.appendLine("    int mZOrder;          // Z 序")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【合成流程】")
        sb.appendLine("```\n")
        sb.appendLine("1. 应用提交帧")
        sb.appendLine("   Surface.unlockCanvasAndPost()")
        sb.appendLine("          │")
        sb.appendLine("          ↓")
        sb.appendLine("   BufferQueue.queueBuffer()")
        sb.appendLine("          │")
        sb.appendLine("          ↓")
        sb.appendLine("   SurfaceFlinger 接收新帧\n")

        sb.appendLine("2. SurfaceFlinger 合成")
        sb.appendLine("   VSync 信号到来")
        sb.appendLine("          │")
        sb.appendLine("          ↓")
        sb.appendLine("   handleMessageVSync()")
        sb.appendLine("          │")
        sb.appendLine("          ↓")
        sb.appendLine("   onVSyncReceived()")
        sb.appendLine("          │")
        sb.appendLine("          ↓")
        sb.appendLine("   handlePageFlip()  // 获取最新帧")
        sb.appendLine("          │")
        sb.appendLine("          ↓")
        sb.appendLine("   handleWorkList()   // 准备合成\n")

        sb.appendLine("3. 硬件合成")
        sb.appendLine("   HWComposer::prepare()")
        sb.appendLine("          │")
        sb.appendLine("          ↓")
        sb.appendLine("   判断哪些 Layer 可以 Overlay")
        sb.appendLine("          │")
        sb.appendLine("          ↓")
        sb.appendLine("   HWComposer::set() // 设置到硬件")
        sb.appendLine("          │")
        sb.appendLine("          ↓")
        sb.appendLine("   Display 显示")
        sb.appendLine("```\n")

        sb.appendLine("【Overlay 优化】")
        sb.appendLine("```\n")
        sb.appendLine("硬件 Overlay 可以避免合成开销：")
        sb.appendLine("")
        sb.appendLine("无 Overlay（GPU 合成）：")
        sb.appendLine("┌─────────────────────────────────────────┐\n")
        sb.appendLine("│ App A Surface + App B Surface + ...     │\n")
        sb.appendLine("│                  │                      │\n")
        sb.appendLine("│                  ↓                      │\n")
        sb.appendLine("│            GPU 合成                     │\n")
        sb.appendLine("│                  │                      │\n")
        sb.appendLine("│                  ↓                      │\n")
        sb.appendLine("│             Display                     │\n")
        sb.appendLine("└─────────────────────────────────────────┘\n")

        sb.appendLine("有 Overlay（硬件直接显示）：")
        sb.appendLine("┌─────────────────────────────────────────┐\n")
        sb.appendLine("│ App A Surface → Overlay 0 ─┐            │\n")
        sb.appendLine("│ App B Surface → Overlay 1 ─┼→ Display  │\n")
        sb.appendLine("│ App C Surface → Overlay 2 ─┘            │\n")
        sb.appendLine("│                                         │\n")
        sb.appendLine("│ (显示控制器直接合成，无需 GPU)          │\n")
        sb.appendLine("└─────────────────────────────────────────┘\n")
        sb.appendLine("```")

        binding.tvContent.text = sb.toString()
    }

    /**
     * 双缓冲机制
     */
    private fun showDoubleBuffer() {
        sb.clear()
        sb.appendLine("=== 缓冲机制详解 ===\n")

        sb.appendLine("【双缓冲】")
        sb.appendLine("```\n")
        sb.appendLine("双缓冲避免画面撕裂：")
        sb.appendLine("")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                        BufferQueue                         │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│   ┌───────────────┐    ┌───────────────┐                   │\n")
        sb.appendLine("│   │   Front Buffer│    │   Back Buffer │                   │\n")
        sb.appendLine("│   │   (显示中)    │    │   (绘制中)    │                   │\n")
        sb.appendLine("│   └───────────────┘    └───────────────┘                   │\n")
        sb.appendLine("│          │                     │                            │\n")
        sb.appendLine("│          │                     │                            │\n")
        sb.appendLine("│          ↓                     ↓                            │\n")
        sb.appendLine("│     显示给用户            GPU/CPU 绘制                      │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│                    VSync 信号                               │\n")
        sb.appendLine("│                         │                                   │\n")
        sb.appendLine("│                         ↓                                   │\n")
        sb.appendLine("│                    交换缓冲区                               │\n")
        sb.appendLine("│                    Front ←→ Back                           │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")

        sb.appendLine("【三重缓冲】")
        sb.appendLine("```\n")
        sb.appendLine("三重缓冲减少掉帧：")
        sb.appendLine("")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                        BufferQueue                         │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│   ┌─────────┐    ┌─────────┐    ┌─────────┐               │\n")
        sb.appendLine("│   │ Buffer 1│    │ Buffer 2│    │ Buffer 3│               │\n")
        sb.appendLine("│   │ (显示)  │    │ (待显示)│    │ (绘制中)│               │\n")
        sb.appendLine("│   └─────────┘    └─────────┘    └─────────┘               │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│   优点：GPU 不用等待，可以继续绘制下一帧                    │\n")
        sb.appendLine("│   缺点：多一帧延迟（约 16ms）                               │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")

        sb.appendLine("【BufferQueue 状态】")
        sb.appendLine("```java")
        sb.appendLine("enum BufferState {")
        sb.appendLine("    FREE,      // 空闲，可用")
        sb.appendLine("    DEQUEUED,  // 已出队，正在被生产者填充")
        sb.appendLine("    QUEUED,    // 已入队，等待消费者获取")
        sb.appendLine("    ACQUIRED   // 已获取，正在被消费者使用")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【缓冲区流转】")
        sb.appendLine("```\n")
        sb.appendLine("         ┌────────────────────────────────────────────────┐\n")
        sb.appendLine("         │                 BufferQueue                    │\n")
        sb.appendLine("         │                                                │\n")
        sb.appendLine("         │  ┌──────┐  ┌──────┐  ┌──────┐                 │\n")
        sb.appendLine("         │  │ FREE │  │ FREE │  │ FREE │                 │\n")
        sb.appendLine("         │  └──────┘  └──────┘  └──────┘                 │\n")
        sb.appendLine("         │      ↑                                   │     │\n")
        sb.appendLine("         │      │                                   │     │\n")
        sb.appendLine("┌────────┴──────┴───────────────────────────────────┴─────┐│\n")
        sb.appendLine("│     dequeueBuffer()          queueBuffer()              ││\n")
        sb.appendLine("│            ↑                       │                     ││\n")
        sb.appendLine("│            │                       ↓                     ││\n")
        sb.appendLine("│  ┌──────────────┐          ┌──────────────┐             ││\n")
        sb.appendLine("│  │  DEQUEUED    │ ───────→ │   QUEUED     │             ││\n")
        sb.appendLine("│  │  (生产者)    │          │  (等待消费)  │             ││\n")
        sb.appendLine("│  └──────────────┘          └──────────────┘             ││\n")
        sb.appendLine("│        应用绘制                     │                    ││\n")
        sb.appendLine("└─────────────────────────────────────│────────────────────┘│\n")
        sb.appendLine("                                      │                    │\n")
        sb.appendLine("                                      ↓                    │\n")
        sb.appendLine("┌────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│     acquireBuffer()          releaseBuffer()              │\n")
        sb.appendLine("│            ↑                       │                      │\n")
        sb.appendLine("│            │                       ↓                      │\n")
        sb.appendLine("│  ┌──────────────┐          ┌──────────────┐              │\n")
        sb.appendLine("│  │  ACQUIRED    │ ───────→ │    FREE      │              │\n")
        sb.appendLine("│  │  (消费者)    │          │   (回收)     │              │\n")
        sb.appendLine("│  └──────────────┘          └──────────────┘              │\n")
        sb.appendLine("│     SurfaceFlinger 合成                                    │\n")
        sb.appendLine("└────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")

        sb.appendLine("【VSync 与缓冲区交换】")
        sb.appendLine("```\n")
        sb.appendLine("时间线：")
        sb.appendLine("")
        sb.appendLine("VSync 1    VSync 2    VSync 3    VSync 4")
        sb.appendLine("   │         │         │         │")
        sb.appendLine("   ↓         ↓         ↓         ↓")
        sb.appendLine("  ┌───┐     ┌───┐     ┌───┐     ┌───┐")
        sb.appendLine("  │ F1│     │ F2│     │ F3│     │ F4│")
        sb.appendLine("  └───┘     └───┘     └───┘     └───┘")
        sb.appendLine("   │         │         │         │")
        sb.appendLine("   │         │         │         │")
        sb.appendLine("   ↓         ↓         ↓         ↓")
        sb.appendLine(" 显示 F1   显示 F2   显示 F3   显示 F4")
        sb.appendLine("")
        sb.appendLine("每个 VSync：")
        sb.appendLine("1. 显示上一帧绘制的内容")
        sb.appendLine("2. 开始绘制下一帧")
        sb.appendLine("3. 交换前后缓冲区")
        sb.appendLine("```")

        binding.tvContent.text = sb.toString()
    }

    /**
     * Surface 实践演示
     */
    private fun demonstrateSurface() {
        sb.clear()
        sb.appendLine("=== Surface 实践演示 ===\n")

        sb.appendLine("【演示：SurfaceView 绘制】\n")

        // 创建一个自定义的 SurfaceView 来演示
        val surfaceView = SurfaceView(this)
        surfaceView.holder.addCallback(object : SurfaceHolder.Callback {
            private var drawThread: DrawThread? = null

            override fun surfaceCreated(holder: SurfaceHolder) {
                drawThread = DrawThread(holder.surface)
                drawThread?.start()
            }

            override fun surfaceDestroyed(holder: SurfaceHolder) {
                drawThread?.stopDrawing()
                drawThread = null
            }

            override fun surfaceChanged(holder: SurfaceHolder, format: Int, width: Int, height: Int) {
                // 不需要处理
            }
        })

        binding.demoContainer.removeAllViews()
        binding.demoContainer.addView(surfaceView)

        sb.appendLine("SurfaceView 已添加，正在绘制...\n")

        sb.appendLine("【代码示例：SurfaceView 绘制】")
        sb.appendLine("```java")
        sb.appendLine("class DrawThread(private val surface: Surface) : Thread() {")
        sb.appendLine("    private var running = true")
        sb.appendLine("    private var frameCount = 0")
        sb.appendLine("    ")
        sb.appendLine("    override fun run() {")
        sb.appendLine("        while (running) {")
        sb.appendLine("            // 1. 锁定 Canvas")
        sb.appendLine("            val canvas = surface.lockCanvas(null)")
        sb.appendLine("            try {")
        sb.appendLine("                // 2. 绘制")
        sb.appendLine("                canvas.drawColor(Color.WHITE)")
        sb.appendLine("                val paint = Paint().apply {")
        sb.appendLine("                    color = Color.BLUE")
        sb.appendLine("                    textSize = 50f")
        sb.appendLine("                }")
        sb.appendLine("                canvas.drawText(\"Frame: \${'$'}frameCount\", 50f, 100f, paint)")
        sb.appendLine("                frameCount++")
        sb.appendLine("            } finally {")
        sb.appendLine("                // 3. 解锁并提交")
        sb.appendLine("                surface.unlockCanvasAndPost(canvas)")
        sb.appendLine("            }")
        sb.appendLine("            // 4. 控制帧率")
        sb.appendLine("            Thread.sleep(16)")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    fun stopDrawing() {")
        sb.appendLine("        running = false")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【注意事项】")
        sb.appendLine("1. SurfaceView 有独立的 Surface")
        sb.appendLine("2. 可以在子线程绘制")
        sb.appendLine("3. lockCanvas/unlockCanvasAndPost 必须配对")
        sb.appendLine("4. 避免长时间持有 Canvas")

        binding.tvContent.text = sb.toString()
    }

    /**
     * 绘制线程
     */
    private inner class DrawThread(private val surface: Surface) : Thread() {
        private var running = true
        private var frameCount = 0
        private val paint = Paint()

        override fun run() {
            paint.color = Color.BLUE
            paint.textSize = 40f
            paint.isAntiAlias = true

            while (running) {
                var canvas: Canvas? = null
                try {
                    canvas = surface.lockCanvas(null)
                    if (canvas != null) {
                        // 清空背景
                        canvas.drawColor(Color.WHITE)

                        // 绘制帧计数
                        canvas.drawText("Frame: $frameCount", 50f, 80f, paint)

                        // 绘制一个简单的动画
                        val x = (frameCount % 200).toFloat()
                        paint.color = Color.RED
                        canvas.drawCircle(x + 50, 120f, 30f, paint)

                        frameCount++
                    }
                } finally {
                    if (canvas != null) {
                        try {
                            surface.unlockCanvasAndPost(canvas)
                        } catch (e: Exception) {
                            // Surface 可能已销毁
                        }
                    }
                }

                try {
                    Thread.sleep(16) // 约 60fps
                } catch (e: InterruptedException) {
                    break
                }
            }
        }

        fun stopDrawing() {
            running = false
            interrupt()
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        // 清理演示容器
        binding.demoContainer.removeAllViews()
    }

    override fun onSupportNavigateUp(): Boolean {
        onBackPressedDispatcher.onBackPressed()
        return true
    }
}
