package com.peter.window.demo.viewroot.deep

import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.os.Message
import android.os.MessageQueue
import androidx.appcompat.app.AppCompatActivity
import com.peter.window.demo.databinding.ActivityThreadModelBinding

/**
 * 深入篇：ViewRootImpl 线程模型与 Handler
 *
 * ViewRootImpl 对线程有严格的要求：
 * 1. 只能在创建它的线程（通常是主线程）操作 View
 * 2. 使用 Handler 接收和处理消息
 * 3. 使用同步屏障确保 VSync 优先处理
 *
 * 核心概念：
 * - Thread 检查机制
 * - ViewRootHandler 消息处理
 * - 同步屏障
 * - HandlerActionQueue
 */
class ThreadModelActivity : AppCompatActivity() {

    private lateinit var binding: ActivityThreadModelBinding
    private val sb = StringBuilder()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityThreadModelBinding.inflate(layoutInflater)
        setContentView(binding.root)
        supportActionBar?.setDisplayHomeAsUpEnabled(true)

        setupListeners()
        showOverview()
    }

    private fun setupListeners() {
        binding.btnOverview.setOnClickListener { showOverview() }
        binding.btnThreadCheck.setOnClickListener { showThreadCheck() }
        binding.btnHandler.setOnClickListener { showHandler() }
        binding.btnSyncBarrier.setOnClickListener { showSyncBarrier() }
        binding.btnMessages.setOnClickListener { showMessages() }
        binding.btnRunQueue.setOnClickListener { showRunQueue() }
        binding.btnThreadException.setOnClickListener { showThreadException() }
        binding.btnPractice.setOnClickListener { demonstrateThreadModel() }
    }

    /**
     * 线程模型概述
     */
    private fun showOverview() {
        sb.clear()
        sb.appendLine("=== 线程模型概述 ===\n")

        sb.appendLine("【ViewRootImpl 线程模型】")
        sb.appendLine("```\n")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                        主线程                               │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  ┌─────────────────────────────────────────────────────┐   │\n")
        sb.appendLine("│  │                  ViewRootImpl                       │   │\n")
        sb.appendLine("│  │                                                     │   │\n")
        sb.appendLine("│  │   mThread = Thread.currentThread()                  │   │\n")
        sb.appendLine("│  │          ↓                                          │   │\n")
        sb.appendLine("│  │   mHandler = ViewRootHandler()                      │   │\n")
        sb.appendLine("│  │          ↓                                          │   │\n")
        sb.appendLine("│  │   mChoreographer = Choreographer.getInstance()      │   │\n")
        sb.appendLine("│  │                                                     │   │\n")
        sb.appendLine("│  └─────────────────────────────────────────────────────┘   │\n")
        sb.appendLine("│                          │                                 │\n")
        sb.appendLine("│                          ↓                                 │\n")
        sb.appendLine("│  ┌─────────────────────────────────────────────────────┐   │\n")
        sb.appendLine("│  │                 Looper                               │   │\n")
        sb.appendLine("│  │                                                     │   │\n")
        sb.appendLine("│  │   MessageQueue ←─ 消息队列                          │   │\n")
        sb.appendLine("│  │        │                                            │   │\n")
        sb.appendLine("│  │        ├── 普通消息                                 │   │\n")
        sb.appendLine("│  │        ├── 异步消息 (VSync)                         │   │\n")
        sb.appendLine("│  │        └── 同步屏障                                 │   │\n")
        sb.appendLine("│  │                                                     │   │\n")
        sb.appendLine("│  └─────────────────────────────────────────────────────┘   │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```\n")

        sb.appendLine("【核心原则】")
        sb.appendLine("```\n")
        sb.appendLine("1. 单线程模型")
        sb.appendLine("   - View 只能在主线程操作")
        sb.appendLine("   - ViewRootImpl 创建时记录线程")
        sb.appendLine("   - 后续操作检查线程一致性\n")

        sb.appendLine("2. 消息驱动")
        sb.appendLine("   - 所有操作通过 Handler 发送消息")
        sb.appendLine("   - Looper 循环处理消息")
        sb.appendLine("   - VSync 使用异步消息\n")

        sb.appendLine("3. 优先级调度")
        sb.appendLine("   - 同步屏障保证 VSync 优先")
        sb.appendLine("   - UI 渲染优先于其他消息")
        sb.appendLine("   - 避免消息饥饿")
        sb.appendLine("```\n")

        sb.appendLine("【线程检查时机】")
        sb.appendLine("```java")
        sb.appendLine("// 以下操作会检查线程：")
        sb.appendLine("requestLayout()     → checkThread()")
        sb.appendLine("invalidate()        → checkThread()")
        sb.appendLine("setLayoutParams()   → checkThread()")
        sb.appendLine("setViewVisibility() → checkThread()")
        sb.appendLine("dispatchKeyEvent()  → checkThread()")
        sb.appendLine("dispatchTouchEvent()→ checkThread()")
        sb.appendLine("// ...")
        sb.appendLine("```\n")

        sb.appendLine("【Handler 消息类型】")
        sb.appendLine("```java")
        sb.appendLine("// ViewRootImpl 处理的消息")
        sb.appendLine("static final int MSG_INVALIDATE = 1;          // 无效化")
        sb.appendLine("static final int MSG_INVALIDATE_RECT = 2;     // 区域无效化")
        sb.appendLine("static final int MSG_DIE = 3;                 // 销毁")
        sb.appendLine("static final int MSG_DISPATCH_KEY = 4;        // 分发按键")
        sb.appendLine("static final int MSG_DISPATCH_TOUCH = 5;      // 分发触摸")
        sb.appendLine("static final int MSG_DISPATCH_APP_VISIBILITY = 6;")
        sb.appendLine("static final int MSG_DISPATCH_GET_NEW_SURFACE = 7;")
        sb.appendLine("static final int MSG_RESIZED = 8;             // 尺寸变化")
        sb.appendLine("static final int MSG_WINDOW_FOCUS_CHANGED = 9;")
        sb.appendLine("// ... 更多消息")
        sb.appendLine("```")

        binding.tvContent.text = sb.toString()
    }

    /**
     * 线程检查详解
     */
    private fun showThreadCheck() {
        sb.clear()
        sb.appendLine("=== 线程检查机制 ===\n")

        sb.appendLine("【checkThread 方法】")
        sb.appendLine("```java")
        sb.appendLine("// ViewRootImpl.java")
        sb.appendLine("void checkThread() {")
        sb.appendLine("    if (mThread != Thread.currentThread()) {")
        sb.appendLine("        throw new CalledFromWrongThreadException(")
        sb.appendLine("            \"Only the original thread that created a view hierarchy can touch its views.\");")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【线程记录】")
        sb.appendLine("```java")
        sb.appendLine("public ViewRootImpl(Context context, Display display) {")
        sb.appendLine("    // 记录当前线程")
        sb.appendLine("    mThread = Thread.currentThread();")
        sb.appendLine("    ")
        sb.appendLine("    // 获取当前线程的 Looper")
        sb.appendLine("    mLooper = Looper.myLooper();")
        sb.appendLine("    if (mLooper == null) {")
        sb.appendLine("        throw new IllegalStateException(")
        sb.appendLine("            \"The specified thread does not have a looper.\");")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 创建 Handler")
        sb.appendLine("    mHandler = new ViewRootHandler();")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【典型错误】")
        sb.appendLine("```java")
        sb.appendLine("// 错误：在子线程更新 UI")
        sb.appendLine("new Thread(() -> {")
        sb.appendLine("    textView.setText(\"Hello\");  // 抛出异常！")
        sb.appendLine("}).start();\n")

        sb.appendLine("// 错误信息：")
        sb.appendLine("android.view.ViewRootImpl\${'$'}CalledFromWrongThreadException:")
        sb.appendLine("Only the original thread that created a view hierarchy can touch its views.")
        sb.appendLine("```\n")

        sb.appendLine("【正确做法】")
        sb.appendLine("```java")
        sb.appendLine("// 方法 1：使用 runOnUiThread")
        sb.appendLine("new Thread(() -> {")
        sb.appendLine("    runOnUiThread(() -> {")
        sb.appendLine("        textView.setText(\"Hello\");")
        sb.appendLine("    });")
        sb.appendLine("}).start();\n")

        sb.appendLine("// 方法 2：使用 Handler")
        sb.appendLine("Handler handler = new Handler(Looper.getMainLooper());")
        sb.appendLine("new Thread(() -> {")
        sb.appendLine("    handler.post(() -> {")
        sb.appendLine("        textView.setText(\"Hello\");")
        sb.appendLine("    });")
        sb.appendLine("}).start();\n")

        sb.appendLine("// 方法 3：使用 View.post")
        sb.appendLine("new Thread(() -> {")
        sb.appendLine("    textView.post(() -> {")
        sb.appendLine("        textView.setText(\"Hello\");")
        sb.appendLine("    });")
        sb.appendLine("}).start();")
        sb.appendLine("```\n")

        sb.appendLine("【特殊情况】")
        sb.appendLine("```java")
        sb.appendLine("// 在 View attach 之前可以跨线程操作")
        sb.appendLine("// 因为此时还没有 ViewRootImpl")
        sb.appendLine("TextView tv = new TextView(context);")
        sb.appendLine("new Thread(() -> {")
        sb.appendLine("    tv.setText(\"Hello\");  // OK，View 还未 attach")
        sb.appendLine("}).start();\n")

        sb.appendLine("// setContentView 后才创建 ViewRootImpl")
        sb.appendLine("setContentView(tv);  // 这之后就会检查线程")
        sb.appendLine("```\n")

        sb.appendLine("【线程检查的调用链】")
        sb.appendLine("```\n")
        sb.appendLine("textView.setText(\"text\")")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("textView.checkForRelayout()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("requestLayout()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("ViewParent.requestLayout()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("ViewRootImpl.requestLayout()")
        sb.appendLine("           │")
        sb.appendLine("           ↓")
        sb.appendLine("checkThread()  ← 在这里检查")
        sb.appendLine("```")

        binding.tvContent.text = sb.toString()
    }

    /**
     * Handler 详解
     */
    private fun showHandler() {
        sb.clear()
        sb.appendLine("=== ViewRootHandler 详解 ===\n")

        sb.appendLine("【ViewRootHandler】")
        sb.appendLine("```java")
        sb.appendLine("final class ViewRootHandler extends Handler {")
        sb.appendLine("    @Override")
        sb.appendLine("    public String getMessageName(Message message) {")
        sb.appendLine("        switch (message.what) {")
        sb.appendLine("            case MSG_INVALIDATE:")
        sb.appendLine("                return \"MSG_INVALIDATE\";")
        sb.appendLine("            case MSG_INVALIDATE_RECT:")
        sb.appendLine("                return \"MSG_INVALIDATE_RECT\";")
        sb.appendLine("            // ...")
        sb.appendLine("            default:")
        sb.appendLine("                return super.getMessageName(message);")
        sb.appendLine("        }")
        sb.appendLine("    }\n")

        sb.appendLine("    @Override")
        sb.appendLine("    public void handleMessage(Message msg) {")
        sb.appendLine("        switch (msg.what) {")
        sb.appendLine("            case MSG_INVALIDATE:")
        sb.appendLine("                ((View) msg.obj).invalidate();")
        sb.appendLine("                break;")
        sb.appendLine("                ")
        sb.appendLine("            case MSG_INVALIDATE_RECT:")
        sb.appendLine("                final View.AttachInfo.InvalidateInfo info = ")
        sb.appendLine("                    (View.AttachInfo.InvalidateInfo) msg.obj;")
        sb.appendLine("                info.target.invalidate(info.left, info.top, ")
        sb.appendLine("                    info.right, info.bottom);")
        sb.appendLine("                break;")
        sb.appendLine("                ")
        sb.appendLine("            case MSG_PROCESS_INPUT_EVENTS:")
        sb.appendLine("                doProcessInputEvents();")
        sb.appendLine("                break;")
        sb.appendLine("                ")
        sb.appendLine("            case MSG_DISPATCH_APP_VISIBILITY:")
        sb.appendLine("                handleAppVisibility(msg.arg1 != 0);")
        sb.appendLine("                break;")
        sb.appendLine("                ")
        sb.appendLine("            case MSG_DISPATCH_GET_NEW_SURFACE:")
        sb.appendLine("                handleGetNewSurface();")
        sb.appendLine("                break;")
        sb.appendLine("                ")
        sb.appendLine("            case MSG_RESIZED:")
        sb.appendLine("                // 窗口尺寸变化")
        sb.appendLine("                handleResized(msg);")
        sb.appendLine("                break;")
        sb.appendLine("                ")
        sb.appendLine("            case MSG_WINDOW_FOCUS_CHANGED:")
        sb.appendLine("                // 窗口焦点变化")
        sb.appendLine("                handleWindowFocusChanged();")
        sb.appendLine("                break;")
        sb.appendLine("                ")
        sb.appendLine("            case MSG_DIE:")
        sb.appendLine("                // 销毁")
        sb.appendLine("                doDie();")
        sb.appendLine("                break;")
        sb.appendLine("                ")
        sb.appendLine("            // ... 更多消息处理")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【消息发送示例】")
        sb.appendLine("```java")
        sb.appendLine("// 发送 invalidate 消息")
        sb.appendLine("void invalidateWorld(View view) {")
        sb.appendLine("    Message msg = mHandler.obtainMessage(MSG_INVALIDATE, view);")
        sb.appendLine("    mHandler.sendMessage(msg);")
        sb.appendLine("}\n")

        sb.appendLine("// 发送区域 invalidate 消息")
        sb.appendLine("void invalidateRect(View view, int l, int t, int r, int b) {")
        sb.appendLine("    View.AttachInfo.InvalidateInfo info = ")
        sb.appendLine("        View.AttachInfo.InvalidateInfo.obtain();")
        sb.appendLine("    info.target = view;")
        sb.appendLine("    info.left = l;")
        sb.appendLine("    info.top = t;")
        sb.appendLine("    info.right = r;")
        sb.appendLine("    info.bottom = b;")
        sb.appendLine("    ")
        sb.appendLine("    Message msg = mHandler.obtainMessage(MSG_INVALIDATE_RECT, info);")
        sb.appendLine("    mHandler.sendMessage(msg);")
        sb.appendLine("}\n")

        sb.appendLine("// 发送销毁消息")
        sb.appendLine("void die(boolean immediate) {")
        sb.appendLine("    if (immediate) {")
        sb.appendLine("        doDie();")
        sb.appendLine("    } else {")
        sb.appendLine("        mHandler.sendEmptyMessage(MSG_DIE);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【Handler 与 Looper】")
        sb.appendLine("```\n")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                        主线程                               │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  ┌──────────────────────────────────────────────────────┐  │\n")
        sb.appendLine("│  │                   Looper.loop()                      │  │\n")
        sb.appendLine("│  │                                                      │  │\n")
        sb.appendLine("│  │   while (true) {                                     │  │\n")
        sb.appendLine("│  │       Message msg = queue.next();  // 获取消息       │  │\n")
        sb.appendLine("│  │       if (msg == null) return;                       │  │\n")
        sb.appendLine("│  │                                                      │  │\n")
        sb.appendLine("│  │       msg.target.dispatchMessage(msg);  // 分发      │  │\n")
        sb.appendLine("│  │       msg.recycle();  // 回收                        │  │\n")
        sb.appendLine("│  │   }                                                  │  │\n")
        sb.appendLine("│  │                                                      │  │\n")
        sb.appendLine("│  └──────────────────────────────────────────────────────┘  │\n")
        sb.appendLine("│                           │                                │\n")
        sb.appendLine("│                           ↓                                │\n")
        sb.appendLine("│  ┌──────────────────────────────────────────────────────┐  │\n")
        sb.appendLine("│  │              ViewRootHandler                         │  │\n")
        sb.appendLine("│  │                                                      │  │\n")
        sb.appendLine("│  │   dispatchMessage(msg) {                             │  │\n")
        sb.appendLine("│  │       if (msg.callback != null) {                    │  │\n")
        sb.appendLine("│  │           msg.callback.run();                        │  │\n")
        sb.appendLine("│  │       } else {                                       │  │\n")
        sb.appendLine("│  │           handleMessage(msg);                        │  │\n")
        sb.appendLine("│  │       }                                              │  │\n")
        sb.appendLine("│  │   }                                                  │  │\n")
        sb.appendLine("│  │                                                      │  │\n")
        sb.appendLine("│  └──────────────────────────────────────────────────────┘  │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```")

        binding.tvContent.text = sb.toString()
    }

    /**
     * 同步屏障详解
     */
    private fun showSyncBarrier() {
        sb.clear()
        sb.appendLine("=== 同步屏障详解 ===\n")

        sb.appendLine("【什么是同步屏障】")
        sb.appendLine("同步屏障是一种特殊的 Message，它会阻止 MessageQueue ")
        sb.appendLine("处理同步消息，只允许异步消息通过。\n")

        sb.appendLine("【为什么需要同步屏障】")
        sb.appendLine("```\n")
        sb.appendLine("问题场景：")
        sb.appendLine("主线程 MessageQueue 中可能有大量同步消息")
        sb.appendLine("┌──────┐┌──────┐┌──────┐┌──────┐┌──────┐")
        sb.appendLine("│ Msg1 ││ Msg2 ││ Msg3 ││ Msg4 ││ Msg5 │ ...")
        sb.appendLine("└──────┘└──────┘└──────┘└──────┘└──────┘")
        sb.appendLine("如果 VSync 到来时，还在处理 Msg2...")
        sb.appendLine("→ UI 渲染被延迟")
        sb.appendLine("→ 可能导致掉帧\n")

        sb.appendLine("使用同步屏障后：")
        sb.appendLine("┌──────┐┌──────┐┌──────┐┌──────┐┌──────┐")
        sb.appendLine("│ Msg1 ││屏障  ││ Msg2 ││ Msg3 ││ Msg4 │")
        sb.appendLine("└──────┘└──────┘└──────┘└──────┘└──────┘")
        sb.appendLine("           ↓")
        sb.appendLine("      跳过同步消息")
        sb.appendLine("           ↓")
        sb.appendLine("    优先处理异步的 VSync")
        sb.appendLine("           ↓")
        sb.appendLine("    移除屏障后继续处理")
        sb.appendLine("```\n")

        sb.appendLine("【ViewRootImpl 使用同步屏障】")
        sb.appendLine("```java")
        sb.appendLine("// ViewRootImpl.scheduleTraversals()")
        sb.appendLine("void scheduleTraversals() {")
        sb.appendLine("    if (!mTraversalScheduled) {")
        sb.appendLine("        mTraversalScheduled = true;")
        sb.appendLine("        ")
        sb.appendLine("        // 1. 发送同步屏障")
        sb.appendLine("        mTraversalBarrier = mHandler.getLooper().getQueue()")
        sb.appendLine("                .postSyncBarrier();")
        sb.appendLine("        ")
        sb.appendLine("        // 2. 注册 Traversal 回调（异步消息）")
        sb.appendLine("        mChoreographer.postCallback(")
        sb.appendLine("                Choreographer.CALLBACK_TRAVERSAL,")
        sb.appendLine("                mTraversalRunnable, null);")
        sb.appendLine("    }")
        sb.appendLine("}\n")

        sb.appendLine("// ViewRootImpl.doTraversal()")
        sb.appendLine("void doTraversal() {")
        sb.appendLine("    if (mTraversalScheduled) {")
        sb.appendLine("        mTraversalScheduled = false;")
        sb.appendLine("        ")
        sb.appendLine("        // 3. 移除同步屏障")
        sb.appendLine("        mHandler.getLooper().getQueue()")
        sb.appendLine("                .removeSyncBarrier(mTraversalBarrier);")
        sb.appendLine("        ")
        sb.appendLine("        // 4. 执行遍历")
        sb.appendLine("        performTraversals();")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【MessageQueue 中的同步屏障】")
        sb.appendLine("```java")
        sb.appendLine("// MessageQueue.next()")
        sb.appendLine("Message next() {")
        sb.appendLine("    for (;;) {")
        sb.appendLine("        synchronized (this) {")
        sb.appendLine("            // 获取下一条消息")
        sb.appendLine("            Message msg = mMessages;")
        sb.appendLine("            ")
        sb.appendLine("            // 检查是否有同步屏障")
        sb.appendLine("            if (msg != null && msg.target == null) {")
        sb.appendLine("                // 遇到同步屏障，只查找异步消息")
        sb.appendLine("                do {")
        sb.appendLine("                    Message prev = msg;")
        sb.appendLine("                    msg = prev.next;")
        sb.appendLine("                } while (msg != null && !msg.isAsynchronous());")
        sb.appendLine("            }")
        sb.appendLine("            ")
        sb.appendLine("            if (msg != null) {")
        sb.appendLine("                // 返回消息")
        sb.appendLine("                return msg;")
        sb.appendLine("            }")
        sb.appendLine("            // ...")
        sb.appendLine("        }")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【同步屏障原理】")
        sb.appendLine("```\n")
        sb.appendLine("MessageQueue 结构：")
        sb.appendLine("")
        sb.appendLine("没有屏障时：")
        sb.appendLine("mMessages → [Msg1] → [Msg2] → [Msg3] → null")
        sb.appendLine("             按时间顺序处理\n")

        sb.appendLine("插入屏障后：")
        sb.appendLine("mMessages → [Msg1] → [屏障] → [Msg2] → [Msg3(异步)] → [Msg4] → null")
        sb.appendLine("                      ↑")
        sb.appendLine("              target = null (屏障标志)")
        sb.appendLine("                      ")
        sb.appendLine("next() 时会跳过 Msg2，直接返回 Msg3（异步消息）")
        sb.appendLine("```\n")

        sb.appendLine("【异步消息】")
        sb.appendLine("```java")
        sb.appendLine("// 设置异步消息")
        sb.appendLine("Message msg = Message.obtain();")
        sb.appendLine("msg.what = MSG_TRAVERSAL;")
        sb.appendLine("msg.setAsynchronous(true);  // 设置为异步")
        sb.appendLine("handler.sendMessage(msg);\n")

        sb.appendLine("// Choreographer 使用的就是异步消息")
        sb.appendLine("private void scheduleVsyncLocked() {")
        sb.appendLine("    mDisplayEventReceiver.scheduleVsync();")
        sb.appendLine("    // 接收 VSync 时发送异步消息")
        sb.appendLine("}")
        sb.appendLine("```")

        binding.tvContent.text = sb.toString()
    }

    /**
     * 消息类型详解
     */
    private fun showMessages() {
        sb.clear()
        sb.appendLine("=== ViewRootImpl 消息类型 ===\n")

        sb.appendLine("【消息常量】")
        sb.appendLine("```java")
        sb.appendLine("// ViewRootImpl 中定义的消息类型")
        sb.appendLine("static final int MSG_INVALIDATE = 1;")
        sb.appendLine("static final int MSG_INVALIDATE_RECT = 2;")
        sb.appendLine("static final int MSG_DIE = 3;")
        sb.appendLine("static final int MSG_DISPATCH_KEY = 4;")
        sb.appendLine("static final int MSG_DISPATCH_POINTER = 5;")
        sb.appendLine("static final int MSG_DISPATCH_APP_VISIBILITY = 6;")
        sb.appendLine("static final int MSG_DISPATCH_GET_NEW_SURFACE = 7;")
        sb.appendLine("static final int MSG_RESIZED = 11;")
        sb.appendLine("static final int MSG_RESIZED_REPORT = 12;")
        sb.appendLine("static final int MSG_WINDOW_FOCUS_CHANGED = 13;")
        sb.appendLine("static final int MSG_DISPATCH_KEY_FROM_IME = 15;")
        sb.appendLine("static final int MSG_DISPATCH_DRAW_MARGINS = 16;")
        sb.appendLine("static final int MSG_CHECK_FOCUS = 17;")
        sb.appendLine("static final int MSG_CLOSE_SYSTEM_DIALOGS = 18;")
        sb.appendLine("static final int MSG_DISPATCH_WINDOW_SHOWN = 19;")
        sb.appendLine("static final int MSG_UPDATE_CONFIGURATION = 20;")
        sb.appendLine("static final int MSG_PROCESS_INPUT_EVENTS = 21;")
        sb.appendLine("static final int MSG_CLEAR_ACCESSIBILITY_FOCUS = 22;")
        sb.appendLine("static final int MSG_DISPATCH_DONE_ANIMATING = 23;")
        sb.appendLine("static final int MSG_WINDOW_MOVED = 24;")
        sb.appendLine("static final int MSG_SYNTHESIZE_INPUT_EVENT = 25;")
        sb.appendLine("static final int MSG_DISPATCH_POINTER_DOWN = 26;")
        sb.appendLine("static final int MSG_DISPATCH_POINTER_UP = 27;")
        sb.appendLine("// ...")
        sb.appendLine("```\n")

        sb.appendLine("【主要消息详解】\n")

        sb.appendLine("【MSG_INVALIDATE / MSG_INVALIDATE_RECT】")
        sb.appendLine("```java")
        sb.appendLine("// 触发 View 重绘")
        sb.appendLine("// 非立即执行，通过消息队列")
        sb.appendLine("void scheduleInvalidate(View view) {")
        sb.appendLine("    Message msg = mHandler.obtainMessage(MSG_INVALIDATE, view);")
        sb.appendLine("    mHandler.sendMessage(msg);")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【MSG_DIE】")
        sb.appendLine("```java")
        sb.appendLine("// 销毁 ViewRootImpl")
        sb.appendLine("void die(boolean immediate) {")
        sb.appendLine("    if (immediate) {")
        sb.appendLine("        // 立即销毁")
        sb.appendLine("        doDie();")
        sb.appendLine("    } else {")
        sb.appendLine("        // 通过消息销毁")
        sb.appendLine("        mHandler.sendEmptyMessage(MSG_DIE);")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【MSG_RESIZED】")
        sb.appendLine("```java")
        sb.appendLine("// 窗口尺寸变化（来自 WMS）")
        sb.appendLine("case MSG_RESIZED: {")
        sb.appendLine("    SomeArgs args = (SomeArgs) msg.obj;")
        sb.appendLine("    // 更新窗口尺寸")
        sb.appendLine("    mWinFrame.set((Rect) args.arg1);")
        sb.appendLine("    mPendingOverscanInsets.set((Rect) args.arg2);")
        sb.appendLine("    mPendingContentInsets.set((Rect) args.arg3);")
        sb.appendLine("    // ...")
        sb.appendLine("    // 触发重新布局")
        sb.appendLine("    requestLayout();")
        sb.appendLine("    break;")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【MSG_WINDOW_FOCUS_CHANGED】")
        sb.appendLine("```java")
        sb.appendLine("// 窗口焦点变化")
        sb.appendLine("case MSG_WINDOW_FOCUS_CHANGED: {")
        sb.appendLine("    boolean hasWindowFocus = msg.arg1 != 0;")
        sb.appendLine("    ")
        sb.appendLine("    // 更新焦点状态")
        sb.appendLine("    mAttachInfo.mHasWindowFocus = hasWindowFocus;")
        sb.appendLine("    ")
        sb.appendLine("    // 通知 View 树")
        sb.appendLine("    if (mView != null) {")
        sb.appendLine("        mView.dispatchWindowFocusChanged(hasWindowFocus);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // 通知输入法")
        sb.appendLine("    if (hasWindowFocus) {")
        sb.appendLine("        mImeFocusController.onWindowFocusChanged();")
        sb.appendLine("    }")
        sb.appendLine("    break;")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【消息处理时序】")
        sb.appendLine("```\n")
        sb.appendLine("┌─────────────────────────────────────────────────────────────┐\n")
        sb.appendLine("│                    消息处理时序                             │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  1. VSync 信号                                              │\n")
        sb.appendLine("│     └─→ Choreographer.doFrame()                            │\n")
        sb.appendLine("│          └─→ doTraversal()                                 │\n")
        sb.appendLine("│               └─→ performTraversals()                      │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  2. 系统消息（来自 WMS）                                    │\n")
        sb.appendLine("│     └─→ MSG_RESIZED                                        │\n")
        sb.appendLine("│     └─→ MSG_WINDOW_FOCUS_CHANGED                          │\n")
        sb.appendLine("│     └─→ MSG_DISPATCH_APP_VISIBILITY                       │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  3. 输入事件                                                │\n")
        sb.appendLine("│     └─→ MSG_DISPATCH_KEY                                   │\n")
        sb.appendLine("│     └─→ MSG_DISPATCH_POINTER                               │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  4. View 更新                                               │\n")
        sb.appendLine("│     └─→ MSG_INVALIDATE                                     │\n")
        sb.appendLine("│     └─→ MSG_INVALIDATE_RECT                                │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("│  5. 生命周期                                                │\n")
        sb.appendLine("│     └─→ MSG_DIE                                            │\n")
        sb.appendLine("│                                                             │\n")
        sb.appendLine("└─────────────────────────────────────────────────────────────┘\n")
        sb.appendLine("```")

        binding.tvContent.text = sb.toString()
    }

    /**
     * HandlerActionQueue 详解
     */
    private fun showRunQueue() {
        sb.clear()
        sb.appendLine("=== RunQueue 详解 ===\n")

        sb.appendLine("【View.post 原理】")
        sb.appendLine("```java")
        sb.appendLine("// View.post()")
        sb.appendLine("public boolean post(Runnable action) {")
        sb.appendLine("    final AttachInfo attachInfo = mAttachInfo;")
        sb.appendLine("    if (attachInfo != null) {")
        sb.appendLine("        // View 已 attach，直接 post 到 Handler")
        sb.appendLine("        return attachInfo.mHandler.post(action);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    // View 未 attach，加入 RunQueue")
        sb.appendLine("    getRunQueue().post(action);")
        sb.appendLine("    return true;")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【HandlerActionQueue】")
        sb.appendLine("```java")
        sb.appendLine("// View 内部类，用于在 attach 前缓存 Runnable")
        sb.appendLine("private HandlerActionQueue getRunQueue() {")
        sb.appendLine("    if (mRunQueue == null) {")
        sb.appendLine("        mRunQueue = new HandlerActionQueue();")
        sb.appendLine("    }")
        sb.appendLine("    return mRunQueue;")
        sb.appendLine("}\n")

        sb.appendLine("// HandlerActionQueue")
        sb.appendLine("class HandlerActionQueue {")
        sb.appendLine("    private HandlerAction[] mActions;")
        sb.appendLine("    private int mCount;")
        sb.appendLine("    ")
        sb.appendLine("    public void post(Runnable action) {")
        sb.appendLine("        postDelayed(action, 0);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    public void postDelayed(Runnable action, long delayMillis) {")
        sb.appendLine("        // 将 Runnable 存入数组")
        sb.appendLine("        HandlerAction[] actions = mActions;")
        sb.appendLine("        // ... 扩容逻辑")
        sb.appendLine("        actions[mCount++] = new HandlerAction(action, delayMillis);")
        sb.appendLine("    }")
        sb.appendLine("    ")
        sb.appendLine("    public void executeActions(Handler handler) {")
        sb.appendLine("        // 将所有缓存的 Runnable 发送到 Handler")
        sb.appendLine("        for (int i = 0; i < mCount; i++) {")
        sb.appendLine("            HandlerAction action = mActions[i];")
        sb.appendLine("            handler.postDelayed(action.action, action.delay);")
        sb.appendLine("        }")
        sb.appendLine("        mCount = 0;")
        sb.appendLine("    }")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【执行时机】")
        sb.appendLine("```java")
        sb.appendLine("// ViewRootImpl.setView()")
        sb.appendLine("public void setView(View view, ...) {")
        sb.appendLine("    // ...")
        sb.appendLine("    view.assignParent(this);")
        sb.appendLine("    ")
        sb.appendLine("    // 执行缓存的 Runnable")
        sb.appendLine("    mRunQueue.executeActions(mAttachInfo.mHandler);")
        sb.appendLine("}")
        sb.appendLine("```\n")

        sb.appendLine("【RunQueue 流程图】")
        sb.appendLine("```\n")
        sb.appendLine("View 创建（未 attach）")
        sb.appendLine("        │")
        sb.appendLine("        ↓")
        sb.appendLine("view.post(runnable1)")
        sb.appendLine("        │")
        sb.appendLine("        ↓")
        sb.appendLine("    ┌─────────────────────┐")
        sb.appendLine("    │  HandlerActionQueue │")
        sb.appendLine("    │  [runnable1]        │")
        sb.appendLine("    │  [runnable2]        │")
        sb.appendLine("    │  [runnable3]        │")
        sb.appendLine("    └─────────────────────┘")
        sb.appendLine("        │")
        sb.appendLine("        ↓")
        sb.appendLine("ViewRootImpl.setView()")
        sb.appendLine("        │")
        sb.appendLine("        ↓")
        sb.appendLine("executeActions(handler)")
        sb.appendLine("        │")
        sb.appendLine("        ↓")
        sb.appendLine("  所有 Runnable 被发送到 Handler")
        sb.appendLine("        │")
        sb.appendLine("        ↓")
        sb.appendLine("  在下一帧执行")
        sb.appendLine("```\n")

        sb.appendLine("【注意事项】")
        sb.appendLine("```java")
        sb.appendLine("// 1. 在构造函数中使用 post")
        sb.appendLine("public MyView(Context context) {")
        sb.appendLine("    super(context);")
        sb.appendLine("    // 此时 View 未 attach，Runnable 被缓存")
        sb.appendLine("    post(() -> {")
        sb.appendLine("        // 在 attach 后执行")
        sb.appendLine("        // 此时可以获取 View 的宽高")
        sb.appendLine("        int width = getWidth();")
        sb.appendLine("    });")
        sb.appendLine("}\n")

        sb.appendLine("// 2. 不要在 post 中执行耗时操作")
        sb.appendLine("post(() -> {")
        sb.appendLine("    // 错误！会阻塞主线程")
        sb.appendLine("    Thread.sleep(1000);")
        sb.appendLine("});\n")

        sb.appendLine("// 3. 使用 postDelayed 延迟执行")
        sb.appendLine("postDelayed(() -> {")
        sb.appendLine("    // 延迟 100ms 后执行")
        sb.appendLine("}, 100);")
        sb.appendLine("```")

        binding.tvContent.text = sb.toString()
    }

    /**
     * 线程异常详解
     */
    private fun showThreadException() {
        sb.clear()
        sb.appendLine("=== 线程异常详解 ===\n")

        sb.appendLine("【CalledFromWrongThreadException】")
        sb.appendLine("```java")
        sb.appendLine("// 最常见的异常")
        sb.appendLine("android.view.ViewRootImpl\${'$'}CalledFromWrongThreadException:")
        sb.appendLine("Only the original thread that created a view hierarchy can touch its views.")
        sb.appendLine("```\n")

        sb.appendLine("【异常触发场景】")
        sb.appendLine("```java")
        sb.appendLine("// 1. 在子线程更新 UI")
        sb.appendLine("new Thread(() -> {")
        sb.appendLine("    textView.setText(\"text\");  // ❌ 抛异常")
        sb.appendLine("}).start();\n")

        sb.appendLine("// 2. 在子线程调用 requestLayout")
        sb.appendLine("new Thread(() -> {")
        sb.appendLine("    view.requestLayout();  // ❌ 抛异常")
        sb.appendLine("}).start();\n")

        sb.appendLine("// 3. 在子线程调用 invalidate")
        sb.appendLine("new Thread(() -> {")
        sb.appendLine("    view.invalidate();  // ❌ 抛异常")
        sb.appendLine("}).start();\n")

        sb.appendLine("// 4. 在子线程修改 View 属性")
        sb.appendLine("new Thread(() -> {")
        sb.appendLine("    view.setVisibility(View.GONE);  // ❌ 抛异常")
        sb.appendLine("}).start();")
        sb.appendLine("```\n")

        sb.appendLine("【正确的跨线程操作】")
        sb.appendLine("```java")
        sb.appendLine("// 方法 1：Activity.runOnUiThread")
        sb.appendLine("new Thread(() -> {")
        sb.appendLine("    // 子线程执行耗时操作")
        sb.appendLine("    String result = doWork();")
        sb.appendLine("    ")
        sb.appendLine("    // 切换到主线程更新 UI")
        sb.appendLine("    runOnUiThread(() -> {")
        sb.appendLine("        textView.setText(result);  // ✓")
        sb.appendLine("    });")
        sb.appendLine("}).start();\n")

        sb.appendLine("// 方法 2：View.post")
        sb.appendLine("new Thread(() -> {")
        sb.appendLine("    String result = doWork();")
        sb.appendLine("    ")
        sb.appendLine("    textView.post(() -> {")
        sb.appendLine("        textView.setText(result);  // ✓")
        sb.appendLine("    });")
        sb.appendLine("}).start();\n")

        sb.appendLine("// 方法 3：Handler.post")
        sb.appendLine("Handler mainHandler = new Handler(Looper.getMainLooper());")
        sb.appendLine("new Thread(() -> {")
        sb.appendLine("    String result = doWork();")
        sb.appendLine("    ")
        sb.appendLine("    mainHandler.post(() -> {")
        sb.appendLine("        textView.setText(result);  // ✓")
        sb.appendLine("    });")
        sb.appendLine("}).start();")
        sb.appendLine("```\n")

        sb.appendLine("【特殊情况】")
        sb.appendLine("```java")
        sb.appendLine("// 1. View 未 attach 时可以跨线程")
        sb.appendLine("TextView tv = new TextView(context);")
        sb.appendLine("new Thread(() -> {")
        sb.appendLine("    tv.setText(\"text\");  // ✓ View 未 attach")
        sb.appendLine("}).start();\n")

        sb.appendLine("// 2. 非 UI 操作可以跨线程")
        sb.appendLine("new Thread(() -> {")
        sb.appendLine("    textView.setTag(\"tag\");  // ✓ tag 不是 UI 属性")
        sb.appendLine("}).start();\n")

        sb.appendLine("// 3. SurfaceView 可以在子线程绘制")
        sb.appendLine("surfaceView.getHolder().addCallback(new SurfaceHolder.Callback() {")
        sb.appendLine("    @Override")
        sb.appendLine("    public void surfaceCreated(SurfaceHolder holder) {")
        sb.appendLine("        new Thread(() -> {")
        sb.appendLine("            Canvas canvas = holder.lockCanvas();")
        sb.appendLine("            // 在子线程绘制")
        sb.appendLine("            canvas.drawColor(Color.RED);")
        sb.appendLine("            holder.unlockCanvasAndPost(canvas);")
        sb.appendLine("        }).start();")
        sb.appendLine("    }")
        sb.appendLine("});")
        sb.appendLine("```\n")

        sb.appendLine("【调试技巧】")
        sb.appendLine("```java")
        sb.appendLine("// 1. 打印当前线程")
        sb.appendLine("Log.d(\"Thread\", \"Current thread: \" + Thread.currentThread().getName());")
        sb.appendLine("Log.d(\"Thread\", \"Main thread: \" + Looper.getMainLooper().getThread().getName());\n")

        sb.appendLine("// 2. 检查是否在主线程")
        sb.appendLine("boolean isMainThread = Looper.myLooper() == Looper.getMainLooper();\n")

        sb.appendLine("// 3. 使用 StrictMode 检测")
        sb.appendLine("StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()")
        sb.appendLine("    .detectDiskReads()")
        sb.appendLine("    .detectDiskWrites()")
        sb.appendLine("    .detectNetwork()")
        sb.appendLine("    .penaltyLog()")
        sb.appendLine("    .build());")
        sb.appendLine("```")

        binding.tvContent.text = sb.toString()
    }

    /**
     * 线程模型实践演示
     */
    private fun demonstrateThreadModel() {
        sb.clear()
        sb.appendLine("=== 线程模型实践演示 ===\n")

        sb.appendLine("【当前线程信息】\n")

        // 获取当前线程信息
        val currentThread = Thread.currentThread()
        val mainThread = Looper.getMainLooper().thread

        sb.appendLine("当前线程: ${currentThread.name}")
        sb.appendLine("主线程: ${mainThread.name}")
        sb.appendLine("是否在主线程: ${currentThread == mainThread}\n")

        // 演示 Handler 使用
        sb.appendLine("【Handler 演示】\n")

        val handler = Handler(Looper.getMainLooper())

        sb.appendLine("发送消息到主线程...\n")

        handler.post {
            sb.appendLine("✓ 消息在主线程执行: ${Thread.currentThread().name}")
            binding.tvContent.text = sb.toString()
        }

        sb.appendLine("消息已发送，等待执行...\n")

        sb.appendLine("【代码示例】")
        sb.appendLine("```java")
        sb.appendLine("// 获取当前线程信息")
        sb.appendLine("Thread currentThread = Thread.currentThread();")
        sb.appendLine("Thread mainThread = Looper.getMainLooper().getThread();")
        sb.appendLine("")
        sb.appendLine("// 检查是否在主线程")
        sb.appendLine("boolean isMainThread = currentThread == mainThread;")
        sb.appendLine("")
        sb.appendLine("// 使用 Handler 切换线程")
        sb.appendLine("Handler handler = new Handler(Looper.getMainLooper());")
        sb.appendLine("handler.post(() -> {")
        sb.appendLine("    // 这里的代码在主线程执行")
        sb.appendLine("});")
        sb.appendLine("```")

        binding.tvContent.text = sb.toString()
    }

    override fun onSupportNavigateUp(): Boolean {
        onBackPressedDispatcher.onBackPressed()
        return true
    }
}
