// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1218447063;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_flutter_rust_demo',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<CalcResult>> crateApiSimpleBatchCalculate({
    required List<CalcRequest> requests,
  });

  Future<CalcResult> crateApiSimpleCalculateAsync({
    required double a,
    required double b,
    required Operation operation,
  });

  Future<CalcResult> crateApiSimpleCalculateSync({
    required double a,
    required double b,
    required Operation operation,
  });

  Future<CalculatorStats> crateApiSimpleComputeStats({
    required List<CalculationRecord> records,
  });

  Future<CalculationRecord> crateApiSimpleCreateRecord({
    required double a,
    required double b,
    required Operation operation,
  });

  Future<String> crateApiSimpleFormatResult({
    required double a,
    required double b,
    required Operation operation,
    required CalcResult result,
  });

  Future<List<String>> crateApiSimpleGetSupportedOperations();

  Future<double> crateApiSimpleHeavyComputation({required int iterations});

  Future<void> crateApiSimpleInitApp();

  Future<String> crateApiSimpleOperationSymbol({required Operation that});

  Future<Operation?> crateApiSimpleParseOperation({required String s});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<CalcResult>> crateApiSimpleBatchCalculate({
    required List<CalcRequest> requests,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_calc_request(requests, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_calc_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleBatchCalculateConstMeta,
        argValues: [requests],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleBatchCalculateConstMeta =>
      const TaskConstMeta(debugName: "batch_calculate", argNames: ["requests"]);

  @override
  Future<CalcResult> crateApiSimpleCalculateAsync({
    required double a,
    required double b,
    required Operation operation,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(a, serializer);
          sse_encode_f_64(b, serializer);
          sse_encode_operation(operation, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_calc_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCalculateAsyncConstMeta,
        argValues: [a, b, operation],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCalculateAsyncConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_async",
        argNames: ["a", "b", "operation"],
      );

  @override
  Future<CalcResult> crateApiSimpleCalculateSync({
    required double a,
    required double b,
    required Operation operation,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(a, serializer);
          sse_encode_f_64(b, serializer);
          sse_encode_operation(operation, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_calc_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCalculateSyncConstMeta,
        argValues: [a, b, operation],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCalculateSyncConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_sync",
        argNames: ["a", "b", "operation"],
      );

  @override
  Future<CalculatorStats> crateApiSimpleComputeStats({
    required List<CalculationRecord> records,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_calculation_record(records, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_calculator_stats,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleComputeStatsConstMeta,
        argValues: [records],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleComputeStatsConstMeta =>
      const TaskConstMeta(debugName: "compute_stats", argNames: ["records"]);

  @override
  Future<CalculationRecord> crateApiSimpleCreateRecord({
    required double a,
    required double b,
    required Operation operation,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(a, serializer);
          sse_encode_f_64(b, serializer);
          sse_encode_operation(operation, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_calculation_record,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCreateRecordConstMeta,
        argValues: [a, b, operation],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCreateRecordConstMeta => const TaskConstMeta(
    debugName: "create_record",
    argNames: ["a", "b", "operation"],
  );

  @override
  Future<String> crateApiSimpleFormatResult({
    required double a,
    required double b,
    required Operation operation,
    required CalcResult result,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(a, serializer);
          sse_encode_f_64(b, serializer);
          sse_encode_operation(operation, serializer);
          sse_encode_box_autoadd_calc_result(result, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleFormatResultConstMeta,
        argValues: [a, b, operation, result],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleFormatResultConstMeta => const TaskConstMeta(
    debugName: "format_result",
    argNames: ["a", "b", "operation", "result"],
  );

  @override
  Future<List<String>> crateApiSimpleGetSupportedOperations() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetSupportedOperationsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetSupportedOperationsConstMeta =>
      const TaskConstMeta(debugName: "get_supported_operations", argNames: []);

  @override
  Future<double> crateApiSimpleHeavyComputation({required int iterations}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(iterations, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleHeavyComputationConstMeta,
        argValues: [iterations],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleHeavyComputationConstMeta =>
      const TaskConstMeta(
        debugName: "heavy_computation",
        argNames: ["iterations"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiSimpleOperationSymbol({required Operation that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_operation(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleOperationSymbolConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleOperationSymbolConstMeta =>
      const TaskConstMeta(debugName: "operation_symbol", argNames: ["that"]);

  @override
  Future<Operation?> crateApiSimpleParseOperation({required String s}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(s, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_operation,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleParseOperationConstMeta,
        argValues: [s],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleParseOperationConstMeta =>
      const TaskConstMeta(debugName: "parse_operation", argNames: ["s"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  CalcResult dco_decode_box_autoadd_calc_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_calc_result(raw);
  }

  @protected
  Operation dco_decode_box_autoadd_operation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_operation(raw);
  }

  @protected
  CalcRequest dco_decode_calc_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CalcRequest(
      a: dco_decode_f_64(arr[0]),
      b: dco_decode_f_64(arr[1]),
      operation: dco_decode_operation(arr[2]),
    );
  }

  @protected
  CalcResult dco_decode_calc_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CalcResult_Success(value: dco_decode_f_64(raw[1]));
      case 1:
        return CalcResult_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  CalculationRecord dco_decode_calculation_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CalculationRecord(
      a: dco_decode_f_64(arr[0]),
      b: dco_decode_f_64(arr[1]),
      operation: dco_decode_operation(arr[2]),
      result: dco_decode_calc_result(arr[3]),
      timestamp: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  CalculatorStats dco_decode_calculator_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CalculatorStats(
      totalCalculations: dco_decode_i_32(arr[0]),
      successCount: dco_decode_i_32(arr[1]),
      errorCount: dco_decode_i_32(arr[2]),
      averageValue: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CalcRequest> dco_decode_list_calc_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_calc_request).toList();
  }

  @protected
  List<CalcResult> dco_decode_list_calc_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_calc_result).toList();
  }

  @protected
  List<CalculationRecord> dco_decode_list_calculation_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_calculation_record).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Operation dco_decode_operation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Operation.values[raw as int];
  }

  @protected
  Operation? dco_decode_opt_box_autoadd_operation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_operation(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  CalcResult sse_decode_box_autoadd_calc_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_calc_result(deserializer));
  }

  @protected
  Operation sse_decode_box_autoadd_operation(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_operation(deserializer));
  }

  @protected
  CalcRequest sse_decode_calc_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_a = sse_decode_f_64(deserializer);
    var var_b = sse_decode_f_64(deserializer);
    var var_operation = sse_decode_operation(deserializer);
    return CalcRequest(a: var_a, b: var_b, operation: var_operation);
  }

  @protected
  CalcResult sse_decode_calc_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_value = sse_decode_f_64(deserializer);
        return CalcResult_Success(value: var_value);
      case 1:
        var var_message = sse_decode_String(deserializer);
        return CalcResult_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  CalculationRecord sse_decode_calculation_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_a = sse_decode_f_64(deserializer);
    var var_b = sse_decode_f_64(deserializer);
    var var_operation = sse_decode_operation(deserializer);
    var var_result = sse_decode_calc_result(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    return CalculationRecord(
      a: var_a,
      b: var_b,
      operation: var_operation,
      result: var_result,
      timestamp: var_timestamp,
    );
  }

  @protected
  CalculatorStats sse_decode_calculator_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalCalculations = sse_decode_i_32(deserializer);
    var var_successCount = sse_decode_i_32(deserializer);
    var var_errorCount = sse_decode_i_32(deserializer);
    var var_averageValue = sse_decode_f_64(deserializer);
    return CalculatorStats(
      totalCalculations: var_totalCalculations,
      successCount: var_successCount,
      errorCount: var_errorCount,
      averageValue: var_averageValue,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CalcRequest> sse_decode_list_calc_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CalcRequest>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_calc_request(deserializer));
    }
    return ans_;
  }

  @protected
  List<CalcResult> sse_decode_list_calc_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CalcResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_calc_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<CalculationRecord> sse_decode_list_calculation_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CalculationRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_calculation_record(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Operation sse_decode_operation(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Operation.values[inner];
  }

  @protected
  Operation? sse_decode_opt_box_autoadd_operation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_operation(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_calc_result(
    CalcResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_calc_result(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_operation(
    Operation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_operation(self, serializer);
  }

  @protected
  void sse_encode_calc_request(CalcRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.a, serializer);
    sse_encode_f_64(self.b, serializer);
    sse_encode_operation(self.operation, serializer);
  }

  @protected
  void sse_encode_calc_result(CalcResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CalcResult_Success(value: final value):
        sse_encode_i_32(0, serializer);
        sse_encode_f_64(value, serializer);
      case CalcResult_Error(message: final message):
        sse_encode_i_32(1, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_calculation_record(
    CalculationRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.a, serializer);
    sse_encode_f_64(self.b, serializer);
    sse_encode_operation(self.operation, serializer);
    sse_encode_calc_result(self.result, serializer);
    sse_encode_i_64(self.timestamp, serializer);
  }

  @protected
  void sse_encode_calculator_stats(
    CalculatorStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.totalCalculations, serializer);
    sse_encode_i_32(self.successCount, serializer);
    sse_encode_i_32(self.errorCount, serializer);
    sse_encode_f_64(self.averageValue, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_calc_request(
    List<CalcRequest> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_calc_request(item, serializer);
    }
  }

  @protected
  void sse_encode_list_calc_result(
    List<CalcResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_calc_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_calculation_record(
    List<CalculationRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_calculation_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_operation(Operation self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_operation(
    Operation? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_operation(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
